### ISSUE TITLE
fbs freeze (pyinstaller) does not work with PySide2/QML 

### ISSUE THREAD

**Issue by Vyeadiai** [mherrmann/fbs#101]
First off thank you for fbs @mherrmann, the problem lies with PyInstaller but I am not sure how to resolve it.
I have the most basic example that is not working, I removed all of my code for simplification. 
Before anything else I am using 
Python 3.5.x
PyInstaller 3.4
PySide2 5.12

> Ed-MacBook-Air:client ed$ python -V
Python 3.5.7
Ed-MacBook-Air:client ed$ pip freeze
altgraph==0.16.1
boto3==1.9.130
botocore==1.12.130
docutils==0.14
fbs==0.7.4
future==0.17.1
jmespath==0.9.4
macholib==1.11
pefile==2018.8.8
PyInstaller==3.4
PyQt5==5.12.1
PyQt5-sip==4.19.15
PyQtChart==5.12
Pyro4==4.75
PySide2==5.12.2
python-dateutil==2.8.0
s3transfer==0.2.0
serpent==1.28
shiboken2==5.12.2
sip==4.19.8
six==1.12.0
urllib3==1.24.1
>

I have 2 files:

main.py
```
from fbs_runtime.application_context import ApplicationContext
from PySide2.QtQml import QQmlApplicationEngine
from PySide2.QtWidgets import QApplication
from PySide2.QtCore import QObject, Signal, Slot
import sys
import os

class AppContext(ApplicationContext):
    def run(self):
        engine = QQmlApplicationEngine()
        chartGenerator = ChartGenerator()
        engine.rootContext().setContextProperty("chartGenerator", chartGenerator)
        engine.load("main.qml")
        root = engine.rootObjects()[0]
        engine.quit.connect(self.app.quit)
        return self.app.exec_()

class ChartGenerator(QObject):
    def __init__(self):
        QObject.__init__(self)

    @Slot(float)
    def do_something(self, my_number):
        print(my_number)

if __name__ == '__main__':
    app = AppContext()
    exit_code = app.run()
    sys.exit(exit_code)
```

and,
main.qml
```
import QtQuick 2.12
import QtQuick.Window 2.12
import QtQuick.Controls 2.12
import QtCharts 2.3

Window {
    id: window
    width: 1000
    height: 1000
    visible: true


    ChartView {
        id: chart
        anchors.fill: parent
        axes: [
            ValueAxis{
                id: xAxis
                min: 0.0
                max: 0.1
                visible: true
                tickCount: 17
            },
            ValueAxis{
                id: yAxis
                min: 0.0
                max: 0.1
                visible: true
                tickCount: 17
            }
        ]
    }
}
```

The output from fbs freeze

> Ed-MacBook-Air:client ed$ fbs freeze
11983 ERROR: Can not find path ./libshiboken2.abi3.5.12.dylib (needed by /Users/ed/.pyenv/versions/3.5.7/lib/python3.5/site-packages/PySide2/QtCore.abi3.so)
12011 ERROR: Can not find path ./libshiboken2.abi3.5.12.dylib (needed by /Users/ed/.pyenv/versions/3.5.7/lib/python3.5/site-packages/PySide2/QtNetwork.abi3.so)
12035 ERROR: Can not find path ./libshiboken2.abi3.5.12.dylib (needed by /Users/ed/.pyenv/versions/3.5.7/lib/python3.5/site-packages/PySide2/QtWidgets.abi3.so)
12052 ERROR: Can not find path ./libshiboken2.abi3.5.12.dylib (needed by /Users/ed/.pyenv/versions/3.5.7/lib/python3.5/site-packages/PySide2/QtGui.abi3.so)
12058 ERROR: Can not find path ./libshiboken2.abi3.5.12.dylib (needed by /Users/ed/.pyenv/versions/3.5.7/lib/python3.5/site-packages/PySide2/QtQml.abi3.so)
12070 ERROR: Can not find path ./libshiboken2.abi3.5.12.dylib (needed by /Users/ed/.pyenv/versions/3.5.7/lib/python3.5/site-packages/PySide2/QtQuick.abi3.so)
12986 ERROR: Can not find path ./libshiboken2.abi3.5.12.dylib (needed by /Users/ed/.pyenv/versions/3.5.7/lib/python3.5/site-packages/PySide2/libpyside2.abi3.5.12.dylib)
Done. You can now run
`target/PyInstallerFail.app/Contents/MacOS/PyInstallerFail`. If that
doesn't work, see https://build-system.fman.io/troubleshooting.

It cant find the lib. Then I tried to run it:

> Ed-MacBook-Air:client ed$ target/PyInstallerFail.app/Contents/MacOS/PyInstallerFail
QQmlApplicationEngine failed to load component
file:///Users/ed/python_sandbox/client/main.qml:1 module "QtQuick" is not installed
file:///Users/ed/python_sandbox/client/main.qml:2 module "QtQuick.Window" is not installed
file:///Users/ed/python_sandbox/client/main.qml:4 module "QtCharts" is not installed
file:///Users/ed/python_sandbox/client/main.qml:3 module "QtQuick.Controls" is not installed
file:///Users/ed/python_sandbox/client/main.qml:1 module "QtQuick" is not installed
file:///Users/ed/python_sandbox/client/main.qml:2 module "QtQuick.Window" is not installed
file:///Users/ed/python_sandbox/client/main.qml:4 module "QtCharts" is not installed
file:///Users/ed/python_sandbox/client/main.qml:3 module "QtQuick.Controls" is not installed
file:///Users/ed/python_sandbox/client/main.qml:1 module "QtQuick" is not installed
file:///Users/ed/python_sandbox/client/main.qml:2 module "QtQuick.Window" is not installed
file:///Users/ed/python_sandbox/client/main.qml:4 module "QtCharts" is not installed
file:///Users/ed/python_sandbox/client/main.qml:3 module "QtQuick.Controls" is not installed
file:///Users/ed/python_sandbox/client/main.qml:1 module "QtQuick" is not installed
file:///Users/ed/python_sandbox/client/main.qml:2 module "QtQuick.Window" is not installed
file:///Users/ed/python_sandbox/client/main.qml:4 module "QtCharts" is not installed
file:///Users/ed/python_sandbox/client/main.qml:3 module "QtQuick.Controls" is not installed
>Traceback (most recent call last):
  File "main.py", line 32, in <module>
  File "main.py", line 16, in run
IndexError: list index out of range
[49795] Failed to execute script main

I have been spinning my wheels for days on this. Any way around this? I know the issue lies with PyInstaller not playing nicely with PySide2, something about adding hooks that I dont understand. Any help is GREATLY appreciated. 

Thanks,
Ed

P.S. I zipped the fbs project.

[client.zip](https://github.com/mherrmann/fbs/files/3075264/client.zip)

**Comment by j9ac9k** [comment]
I can't speak to your issue, but I'm using fbs with PySide2 on it's own without any problem (but I'm not using QML applications).  Also why do you have both PyQt5 and PySide2 installed?

**Comment by Vyeadiai** [comment]
I find QML it much faster and enjoyable to develop the GUI using QML, I am only using PySide2 for the QML to Python communication. 
I have PyQt5 alongside PySide2 because I was testing with PyQt5 and it seems to work fine, the problem is with PySide2 'hooks'. 

It is related to this issue
[https://github.com/pyinstaller/pyinstaller/issues/3689](url)

and I believe this issue that was resolved with PyQt5 but not PySide2
[https://github.com/pyinstaller/pyinstaller/issues/3711](url)
and
[https://github.com/pyinstaller/pyinstaller/pull/3693](url)

If anyone knows how I can resolve this I would really appreciate your help. @patrickelectric @bjones1

**Comment by j9ac9k** [comment]
Side note, not advocating for or against QML (for some of my most frequent use of using PyQt I cannot use QML as it's incompatible with pyqtgraph.

If you believe this to be a pyside2 issue, I would reach out to their devs on gitter/IRC, you can see the channel information here: https://wiki.qt.io/Qt_for_Python . They've gotten back to me before (but usually after a day or so).

**Comment by Vyeadiai** [comment]
Thanks for the link @j9ac9k

**Comment by Vyeadiai** [comment]
Does anyone know how I can just add the required libraries manually after 'freezing'? In other words when I run the frozen app it complains about missing libs:

> Ed-MacBook-Air:client ed$ target/PyInstallerFail.app/Contents/MacOS/PyInstallerFail
QQmlApplicationEngine failed to load component
file:///Users/ed/python_sandbox/client/main.qml:1 module "QtQuick" is not installed
file:///Users/ed/python_sandbox/client/main.qml:2 module "QtQuick.Window" is not installed
...


Where would I put these libraries so that it could find them?

**Comment by Vyeadiai** [comment]
Related to this issue I created with PyInstaller
[https://github.com/pyinstaller/pyinstaller/issues/4177](https://github.com/pyinstaller/pyinstaller/issues/4177)

**Comment by mherrmann** [comment]
Hi @Vyeadiai,

you repeatedly say that this is a PyInstaller issue. In that case, the best way to proceed is to do what you did - file this as a PyInstaller issue so it gets fixed there (and thus, by extension, in fbs).

Regarding your question, you can add the required libraries "manually". Write a [custom build script](https://build-system.fman.io/manual/#custom-commands) that overrides fbs's `freeze` command and copies the libraries into `target/PyInstallerFail.app/...`.

I'll close this issue because, as you said, it's a PyInstaller issue. As a workaround you could also just use PyQt5.

**Comment by mherrmann** [comment]
This works now if you use fbs 0.8.1. Just install the development version of PyInstaller.
