### ISSUE TITLE
fbs freeze does not package distutils

### ISSUE THREAD

**Issue by j9ac9k** [mherrmann/fbs#103]
First off, this isn't a problem with the fbs codebase, but there may be a workaround that can be implemented in the library, I would be happy to test.

The issue is that pyinstaller is not grabbing distutils, so if you have a dependency that makes use of distutils, you may be in for a bad time.

Here is the pyinstaller issue: https://github.com/pyinstaller/pyinstaller/issues/4064

The underlying issue seems to be with virtualenv, as pinning the _system_ version of virtualenv to 16.2.0 or earlier seems to solve the issue.

**Comment by mherrmann** [comment]
I understand why you'd want me to fix this in fbs. But if it's a PyInstaller issue, then it should be fixed there. This way not only fbs gets the fix, but all use(r)s of PyInstaller. I'm sure the PyInstaller team would be happy to accept any PRs you send them that fixes the issue.

Closing this, because (as you said) it's not a problem with fbs's code base.

**Comment by j9ac9k** [comment]
Pardon me for commenting on the closed issue, while I don't think this is an issue in the fbs code base, I suspect the workaround could be implemented in the fbs codebase, I'm not sure I can implement the workaround as a fbs user (without modifying the fbs codebase).

Here is a link to a commit from a workaround in another repo that uses pyinstaller: https://github.com/willcl-ark/node-launcher/commit/479732dfae7c4301fd4c37400e96fb305a1cc775


Specifically, adding the following code at the beginning of the pyinstaller spec file seems to do the trick.

```
# work-around for https://github.com/pyinstaller/pyinstaller/issues/4064
import distutils
if distutils.distutils_path.endswith('__init__.py'):
    distutils.distutils_path = os.path.dirname(distutils.distutils_path)
```

**Comment by mherrmann** [comment]
Repeating myself: I will not implement a workaround for this in fbs. The reason is that it's a PyInstaller problem and should therefore be fixed there.
