### ISSUE TITLE
error when using signal connection

### ISSUE THREAD

**Issue by UserLiubov** [mherrmann/fbs#104]
Hello! I use fbs with PyQt5. I want to change ProgressBar value from another thread. I use slot/signal to do this. I define `notifyProgress = pyqtSignal(int)`. Then I set connection: `self.notifyProgress.connect(self.on_progress)`.
When I run this code I get an error when running `self.notifyProgress.connect(self.on_progress)`: `TypeError: AppContext cannot be converted to PyQt5.QtCore.QObject in this context`
But when I run this code without using fbs I don't get any errors.
Thanks for your helping!

**Comment by mherrmann** [comment]
fbs's `ApplicationContext` does not inherit from `QObject` so you can't define custom signals in your subclass of it, `AppContext`. But you can define another subclass of `QObject`, which you instantiate in `AppContext`, and define the signal there.

Either way, this is not really a "bug" of fbs. If the above isn't clear, please ask on StackOverflow.
