### ISSUE TITLE
fbs freeze doesnot work with Chirp SDK

### ISSUE THREAD

**Issue by gargvasu** [mherrmann/fbs#106]
First off, @mherrmann fbs is really great, thanks alot. I am using Chirp SDK by https://chirp.io/. Everything works fine in  fbs run but app won't open on fbs freeze. I think this issue is because 
while on fbs run it runs the python code but on fbs freeze it won't converts the code to native code. 

Chirp SDK provides support for Windows as well MacOS. Do you think it can work with fbs as well. 

Modules installed
altgraph==0.16.1
certifi==2019.3.9
cffi==1.12.3
chardet==3.0.4
**chirpsdk**==3.4.4
Click==7.0
configparser==3.7.4
**fbs**==0.7.9
future==0.17.1
idna==2.8
macholib==1.11
pefile==2019.4.18
pycparser==2.19
**PyInstaller**==3.4
pypiwin32==223
**PyQt5**==5.9.2
PyQt5-sip==4.19.15
PySoundFile==0.9.0.post1
python-dotenv==0.10.1
pywin32==224
pywin32-ctypes==0.2.0
requests==2.21.0
requests-futures==0.9.9
sip==4.19.8
sounddevice==0.3.13
urllib3==1.24.3

**Comment by mherrmann** [comment]
Hi,

thank you for the nice message. I'm happy to hear you are finding fbs useful. Have you tried the steps at [build-system.fman.io/troubleshooting](https://build-system.fman.io/troubleshooting)? You say it "won't open". Which error message do you get when you try starting the frozen app from the command line?

**Comment by gargvasu** [comment]
Hi, Sorry I forgot to mention the error message. It says "Failed to execute script main"/ 
I did try the troubleshooting steps. I even tried freeze without importing chirp code and its working fine. Even fb installer works fine with importing chirp code.

**Comment by mherrmann** [comment]
You mean all you're seeing is this dialog?

![image](https://user-images.githubusercontent.com/1076393/57209890-af882680-6fda-11e9-8d4b-e776d794346c.png)

**Comment by gargvasu** [comment]
Yes, I am getting this dialog box.

**Comment by mherrmann** [comment]
Then I don't think you followed the Troubleshooting steps correctly. Please read them again.

**Comment by gargvasu** [comment]
Okay. I will go through it line by line. Would the warn file also help in finding the exact issue?

**Comment by mherrmann** [comment]
I don't think the warn file will help. And you should have gone through it line by line before opening an issue and taking up my time.
