### ISSUE TITLE
FBS cannot differ PySide2 from PyQt5

### ISSUE THREAD

**Issue by Chum4k3r** [mherrmann/fbs#107]
My problem is about the both packages existing side by side on my system. I've followed every step on setting up virtual environments to avoid problems with FBS, and actually compiled and generated installer on win10, but while on my Ubuntu, appears that the FBS cannot see that only PySide2 is installed on my virtual environment and pulls both PyQt5 and PySide2, making the Qt libraries crash

 * Your operating system(s)
Ubuntu 18.04 LTS
 * Your Python version
Python 3.6.7
 * Your fbs version
fbs 0.7.9
 * Your PyInstaller version
PyInstaller 3.4 
* Your PyQt5 / PySide2 version
PySide2 5.12.3
PyQt5 5.9.2 
...
Traceback (most recent call last):
  File "main.py", line 4, in <module>
ImportError: /home/joaovitor/Repositorios/PyFreQAnalyzer/target/PyFreQAnalyzer/libQt5Core.so.5: version `Qt_5.12' not found (required by /home/joaovitor/Repositorios/PyFreQAnalyzer/target/PyFreQAnalyzer/libpyside2.abi3.so.5.12)
[22769] Failed to execute script main

**Comment by mherrmann** [comment]
Hi! Do I understand correctly that your app uses PySide2? In your virtual environment, can you do both

    import PyQt5

and

    import PySide2

?

If yes, why do you say that "only PySide2 is installed", when the above indicates it's both?

Does the problem also appear with PySide2 5.12.2?

**Comment by Chum4k3r** [comment]
When I'm on my project venv I cannot import both, but it doesn't matter which venv I'm on, I have both packages pip-installed, so when I try

`pip list`

both packages are listed, in any environment.

Also, it doesn't matter whether I'm on my dedicated project venv or the base env and use 

`fbs freeze --debug`

it is possible to read the prints on the terminal of the software searching for the "PyQt5" package. On windows this doesn't happened, but I also don't have PyQt5 installed, in any env.

The reason why I maintain both packages on my ubuntu is because I use Spyder for my work, and it is PyQt5 based.

Also, I don't have any
 
`import matplotlib`

statement in any part of my code, but matplotlib binaries are present on the compiled software directory, under the target dir.

**Comment by mherrmann** [comment]
Hm, if `pip list` includes both `PyQt5` and `PySide2` then I would say both are installed in your virtual environment. If you "can't import" them, then maybe they're not installed correctly. But still, they are installed.

My advice would be to fix your virtual environment until `pip list` really does only include the dependencies you want.

**Comment by Chum4k3r** [comment]
Apparently I've managed to do it, the ImportError no longer occurs. Instead, I'm getting "segmentation fault"...

**Comment by mherrmann** [comment]
Then I'll close this issue.
