### ISSUE TITLE
Windows installer missing author settings

### ISSUE THREAD

**Issue by serkandyck** [mherrmann/fbs#11]
İnstaller configration required Settings Author Name but
https://github.com/mherrmann/fbs/blob/86d915d1da14bfe07db4565f2332cbeb75a74744/fbs/installer/windows/__init__.py#L13

Author missing in fbs-tutorial base.json
https://github.com/mherrmann/fbs-tutorial/blob/d34ebfdbf3e36f4c3a580f90d6c55653d3dfc710/src/build/settings/base.json#L2

**Comment by mherrmann** [comment]
I merged your PR. Thank you @serkandyck!
