### ISSUE TITLE
Create Windows installer: filtering doesn't work

### ISSUE THREAD

**Issue by lomotrix** [mherrmann/fbs#112]
Hi @mherrmann,
 
great project, managed to build installers on all 3 major platforms. I had problems building the installer for Windows though. The `Installer.nsi` didn't get filtered and I had to replace all those `${..}` place holders.

I tracked it down to the comparision operation in `fbs/resources.py: class _paths: def __contains__(self, item):` The statement `p.samefile(item)` returns `False` for my setup because of changing `st_ino` values. So the file was copied without filtering.

Some print statements in `def __contains__` reveal following situation:

```
paths p: \\vboxsrv\opt\conda_environments\some_project\fbs_package\src\installer\windows\Installer.nsi

paths item: \\vboxsrv\opt\conda_environments\some_project\fbs_package\src\installer\windows\Installer.nsi

paths p.samefile(item): False

paths compare Path p == item: True

paths os.stat p: os.stat_result(st_mode=33206, st_ino=18446735964861516144, st_dev=64769, st_nlink=1, st_uid=0, st_gid=0, st_size=2892, st_atime=1558435201, st_mtime=1558362909, st_ctime=1558435189)

paths os.stat item: os.stat_result(st_mode=33206, st_ino=18446735964865990672, st_dev=64769, st_nlink=1, st_uid=0, st_gid=0, st_size=2892, st_atime=1558435201,st_mtime=1558362909, st_ctime=1558435189)
```

With following change the installer creation works perfectly. I think it is sane to just compare paths and not to check on disk if these are really the same files.

```python
def __contains__(self, item):
    item = Path(item).resolve()
    for p in self._paths:
        #if p.samefile(item) or p in item.parents:
        if p == item or p in item.parents:
            return True
    return False
```

Software versions (installed via pip in conda environment):

- fbs 0.8.1
- python 3.7
- PyQt5 5.12.2

**Comment by mherrmann** [comment]
Thank you for reporting this. I applied the fix you suggested and released new version [0.8.2](https://github.com/mherrmann/fbs/releases/tag/v0.8.2).
