### ISSUE TITLE
Security Alert: try to store file outside of dist-directory.

### ISSUE THREAD

**Issue by Chum4k3r** [mherrmann/fbs#113]
Hello there, I'm here again.
There was I happily trying to compile my project, as I've had done dozens of times before, and this alert started popping up at this line

```
59441 INFO: Building COLLECT COLLECT-00.toc
Security-Alert: try to store file outside of dist-directory. Aborting. '/usr/lib/x86_64-linux-gnu/qt5/qt.conf'
Traceback (most recent call last):
  File "/home/joaovitor/.local/bin/fbs", line 11, in <module>
    sys.exit(_main())
  File "/home/joaovitor/.local/lib/python3.6/site-packages/fbs/__main__.py", line 17, in _main
    fbs.cmdline.main()
  File "/home/joaovitor/.local/lib/python3.6/site-packages/fbs/cmdline.py", line 32, in main
    fn(*args)
  File "/home/joaovitor/.local/lib/python3.6/site-packages/fbs/builtin_commands/__init__.py", line 125, in freeze
    freeze_ubuntu(debug=debug)
  File "/home/joaovitor/.local/lib/python3.6/site-packages/fbs/freeze/ubuntu.py", line 4, in freeze_ubuntu
    freeze_linux(debug)
  File "/home/joaovitor/.local/lib/python3.6/site-packages/fbs/freeze/linux.py", line 8, in freeze_linux
    run_pyinstaller(debug=debug)
  File "/home/joaovitor/.local/lib/python3.6/site-packages/fbs/freeze/__init__.py", line 48, in run_pyinstaller
    run(args, check=True)
  File "/usr/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['pyinstaller', '--name', 'OnSound', '--noupx', '--log-level', 'DEBUG', '--noconfirm', '--distpath', '/home/joaovitor/repositorios/onsound/target', '--specpath', '/home/joaovitor/repositorios/onsound/target/PyInstaller', '--workpath', '/home/joaovitor/repositorios/onsound/target/PyInstaller', '--additional-hooks-dir', '/home/joaovitor/.local/lib/python3.6/site-packages/fbs/freeze/hooks', '--debug', 'all', '--runtime-hook', '/tmp/tmpaqdkbhgz/fbs_pyinstaller_hook.py', '/home/joaovitor/repositorios/onsound/src/main/python/main.py']' returned non-zero exit status 1.
```

I'm currently on:
Ubuntu 18.04 LTS
fbs 0.8.1
PyInstaller 3.4
PySide2 5.12.0
shiboken2 5.12.0

Tried to find out by myself but it's been weeks with no clues.
Hope I'm not bothering with small issues
Thank you for your time

**Comment by mherrmann** [comment]
Hi, I don't know why that could be happening. Can you create a minimal example that reproduces the issue?

**Comment by Chum4k3r** [comment]
Sorry for the delay, I believe I did not solved the issue, but made a workaround.

I've created the virtual environment inside the project folder. I don't know if this were to be made from the beginning, but now I can freeze as a breeze

**Comment by himanshus97** [comment]
hello guys,
could you please tell me how can i store my data (generating during execution of application) after building my application, because traditional python methods to save files at specified loaction is not working in my application .

**Comment by mherrmann** [comment]
@himanshus97 please ask this on [StackOverflow](https://www.stackoverflow.com).

**Comment by thekswenson** [comment]
I am getting the same error as @Chum4k3r.  Is this not a bug?

**Comment by thekswenson** [comment]
@Chum4k3r : could you please take me though your workaround?
I've made a virtual environment in my project folder and this hasn't fixed the problem...
  I assume it's because I gave `the --system-site-packages` flag to `python3 -m venv`.

It would be difficult for me to get anything working without that flag considering my application depends on an enormous number of packages including GTK.
