### ISSUE TITLE
ModuleNotFoundError after sucessful freeze

### ISSUE THREAD

**Issue by deven96** [mherrmann/fbs#117]
Running in development mode functions properly until i freeze and try to run the frozen version and it throws up a ModuleNotFoundError
 * Ubuntu 18.10
 * Python 3.6.5
 * fbs==0.8.2
 * PyInstaller==3.4
 * PyQt5==5.12.2
 * ```ModuleNotFoundError: No module named distutils```
 *This problem stems from my matplotlib import and I am running in a virtualenvironment if that helps
Thanks!

**Comment by j9ac9k** [comment]
@deven96 this is a pyinstaller issue, if you look at the GitHub they have an issue for this, including a work around. I can't remember if this was fixed in the development version of pyinstaller or not....

**Comment by liuh886** [comment]
I got a similar problem: Freeze Done but excute with ModuleNotFoundError. Also when Freeze --debug.

I notice that the target freezed doesn't contain any dependency except PyQt5. I have not changed any code or dependency, so i don't know where to start trouble shooting.

Python 3.6.2
fbs==0.8.2  / 0.7.0
PyInstaller==3.4
PyQt5==5.11.3

**Comment by liuh886** [comment]
> Running in development mode functions properly until i freeze and try to run the frozen version and it throws up a ModuleNotFoundError
> 
> * Ubuntu 18.10
> * Python 3.6.5
> * fbs==0.8.2
> * PyInstaller==3.4
> * PyQt5==5.12.2
> * `ModuleNotFoundError: No module named distutils`
>   *This problem stems from my matplotlib import and I am running in a virtualenvironment if that helps
>   Thanks!

https://stackoverflow.com/questions/53177533/python-fbs-module-imports-dont-work-after-freeze

maybe this could be helpful.

**Comment by mherrmann** [comment]
@liuh886 you wrote

> i don't know where to start trouble shooting.

You can start here: https://build-system.fman.io/troubleshooting. One of the things it suggests is to use PyQt5 5.9.2 (not 5.11 like you have). Maybe this will solve your issue.

Either way, I haven't seen a minimal example in this thread that reproduces the problem and proves it is a bug in fbs. So I'm closing this issue.
