### ISSUE TITLE
Frozen application only runs when debug flag is set

### ISSUE THREAD

**Issue by rajbala** [mherrmann/fbs#120]
Hi there!

I had an issue that I figured out.  I thought I would post a note here in case others have the same issue.  

Some functionality in a frozen application that I wrote would only work when the debug flag was set when running fbs freeze --debug or when using fbs run.  Running the installed application that was created without the debug flag would not start certain functionality but no error was generated.  

Turns out that having a bunch of print statements caused this issue.  Commented out the print statements for now, but the long-term solution is to use the Python logging module.  

Hope this helps someone in the future.  Fbs has been super helpful and fun to use!

**Comment by mherrmann** [comment]
Thank you for sharing Raj! In general, `print(...)` statements should not break fbs. I suspect (/hope) that the cause of the problem you encountered was not the actual print statement, but what was inside it. Either way, again thank you for taking the time to share your findings.
