### ISSUE TITLE
74302 ERROR: Can not find path ./libtbb.dylib (Numba)

### ISSUE THREAD

**Issue by komodovaran** [mherrmann/fbs#123]
When I freeze my app, I get
```
74302 ERROR: Can not find path ./libtbb.dylib (needed by .../fbsenv/lib/python3.7/site-packages/numba/npyufunc/tbbpool.cpython-37m-darwin.so)
```

Indeed, there doesn't seem to be any such file in `site_packages`, and the app compiles and runs anyway.

I then tried to install `tbb` with Homebrew, and copied the dylib over, and I still get the same error message.

**Comment by mherrmann** [comment]
This error is produced by PyInstaller, which fbs uses to compile ("freeze") your app. I suggest asking this question on [Google](https://www.google.com/search?q=libtbb.dylib+pyinstaller), [StackOverflow](https://stackoverflow.com/) or the [PyInstaller issue tracker](https://github.com/pyinstaller/pyinstaller/issues).
