### ISSUE TITLE
Any sublime users?

### ISSUE THREAD

**Issue by craigmac** [mherrmann/fbs#125]
Not an "Issue", just thought I'd point out that I create a fbs.build-settings so that you can run some of the fbs packaging commands (non-interactive ones) from inside Sublime Text 3 via the Command-Palette. I'll add it to packagecontrol.io later for easier install but thought I'd link to it here first (and to motivate myself to actually go through the process of creating a packagecontrol account, etc.)

https://github.com/saltycraig/fbs.sublime-build

**Comment by mherrmann** [comment]
Cool! Thanks!
