### ISSUE TITLE
[Question] Adding installation steps

### ISSUE THREAD

**Issue by kjanko** [mherrmann/fbs#126]
Hi guys,

I have a simple question: let's say I want to add some steps to the installer that's created by running 'fbs installer'. Is this possible in the current state of fbs?

**Comment by mherrmann** [comment]
Hi,

I presume that's for Windows?

**Comment by kjanko** [comment]
Yeah.

**Comment by mherrmann** [comment]
You can copy the [default `Installer.nsi`](https://github.com/mherrmann/fbs/blob/master/fbs/_defaults/src/installer/windows/Installer.nsi) into your `src/installer/windows/` and modify it to add steps :-)

**Comment by kjanko** [comment]
Oh I see - thought that these files are pre-generated based on configuration/code that we have in the project. Guess not :)

**Comment by mherrmann** [comment]
You should be able to edit them using my explanation above. If not, feel free to re-open :-)

**Comment by kjanko** [comment]
Hey @mherrmann ,

I did what you suggested and It seems like fbs keeps overwriting the modified installer. Is this intended behavior?

**Comment by kjanko** [comment]
I think the location is correct as the new file gets replaced by the default one. I'll check what's happening in details on Monday.

**Comment by 09hirenpatel** [comment]
Thanks @mherrmann It works fine for the windows.
But, I am not able to do the same for the mac and ubuntu. 
I am trying to put application in the right-click context menu for all three OS windows, mac and ubuntu. Let me know if you can help me with this.

**Comment by mherrmann** [comment]
@09hirenpatel when you write "let me know if you can help me with this", I feel treated like I'm your subordinate.

Anyways, I can't help with your question. Please ask on StackOverflow.

**Comment by 09hirenpatel** [comment]
I am really sorry for my wordings. I didn't mean that way @mherrmann. You are respectful person and I just need help from you. 
It will be really helpful if you can help me to set up the installer script for the mac and ubuntu.

Thanks in advance.

**Comment by mherrmann** [comment]
You're doing it again ;-) "It will be really helpful if you can guide me." I just told you I'm not available for help and I asked you to go to StackOverflow.

You write "I just need help from you". Think about my perspective: You're a random stranger to me on the internet. I'm very busy with my own projects. I understand you need help. But what incentive do I have to spend my precious time helping you? You offer no answer to this question. It's not that I don't like helping. It's that many people ask me for help every day and if I helped them all then I would have no time left in my day to work on projects that pay my bills, or spend time with my loved ones.

This is an open source project. You're getting it for free. But that doesn't mean that your needs also entitle you to getting free help.

I hope that makes sense. Like I said, I won't have time to help. Your best bet (I think) is to ask on StackOverflow.

I'll close this.
