### ISSUE TITLE
Commercial licensing for proprietary software

### ISSUE THREAD

**Issue by ScriptSmith** [mherrmann/fbs#13]
The Licensing heading of [README.md](https://github.com/mherrmann/fbs/blob/master/README.md#licensing) states that: 

> This project is licensed under the GPL. In simple terms, this means you can use it for free in open source projects that are also licensed under the GPL. If on the other hand you want to use the project for a proprietary app where you don't want to open source the code, then you need a commercial license. The price for one developer is currently EUR 99. One year of updates is included

My understanding of the GPL is that you are not in a position to offer a commercial license that allows one to use this code in proprietary software because you are not the sole owner of this project's copyright.

You can read common answers to questions about the GPL [here](https://www.gnu.org/licenses/gpl-faq.en.html), and RMS talks specifically about selling exceptions in GPL software [here](https://www.gnu.org/philosophy/selling-exceptions.html).

My understanding (hopefully others can validate this point of view) is that you are able to sell a proprietary version of any software that has been licensed under the GPL if you own the copyright. There is no transfer or change in the status of ownership that occurs after licensing something under the GPL, and this means that you are at liberty to use any additional licenses that you like.

However, you are not able to sell a proprietary version that includes the contributions that others have made because they have only licensed you to use their code under the GPL. You do not own their contributions, they do, and they have licensed their code to you under strict terms which prohibit use in proprietary software.

If my understanding is correct, then you can either:

1) Stop selling a proprietary version of this project
    1) You can sell this software, but not for use in proprietary software
2) Remove the contributions that others have made and continue selling this project
3) Ask the past contributors (I can see at least 2 in the version history) to assign ownership of their code to you, and continue selling this project. Then either: 
    1) Add a contributors agreement to ensure that future contributions are allowed to be sold.
    2) Transition to a different license such as the MIT License which would allow you to sell contributions made by others, as they have licensed you to do so

Additionally, on line 2 of `fbs_runtime/signal_.py` the following code is used:

```python
from PyQt5.QtNetwork import QAbstractSocket
```

Unless you have an agreement with Riverbank computing, you are not allowed to sell a version of their software that can be used in proprietary software. The FSF talks about linking to GPL software [here](https://www.gnu.org/licenses/gpl-faq.en.html#LinkingWithGPL) and it may be worth seeking legal advice to ensure compliance in this regard - I've seen mixed opinions of this interpretation.

**Comment by mherrmann** [comment]
Thank you for the advice, if somewhat unsolicited and prescriptive.

> you are not in a position to offer a commercial license that allows one to use this code in proprietary software because you are not the sole owner of this project's copyright.
> [...] 
> you are not able to sell a proprietary version that includes the contributions that others have made because they have only licensed you to use their code under the GPL.
> [...]
> they have licensed their code to you under strict terms which prohibit use in proprietary software.

I 've obtained @fredrikaverpil's permission by email. The other change was just a single character in a comment, but you're right. I'll ask for permission in a comment below and revert the change if necessary.

> Unless you have an agreement with Riverbank computing, you are not allowed to sell a version of their software that can be used in proprietary software.

I neither ship their software, nor do I claim to sell it(?). The users install the `PyQt5` dependency themselves. And I do have an agreement with Riverbank computing.

**Comment by mherrmann** [comment]
@ss18, do you give me permission to relicense your [contribution](https://github.com/mherrmann/fbs/pull/12) to fbs to others?

**Comment by ss18** [comment]
@mherrmann of course

**Comment by mherrmann** [comment]
Thanks!

**Comment by ScriptSmith** [comment]
Great. My apologies if the initial contact came off as rude, this particular scenario is one that I've considered in the past and I used this as an opportunity to try reason about the problem.

**Comment by mherrmann** [comment]
Sure! I appreciate it. Since you're already here (and seem to know about this), can you recommend a good Contributor License Agreement? [Google's](https://cla.developers.google.com/about/google-individual?csw=1), that of the [Apache Software Foundation](http://www.apache.org/licenses/icla.pdf) and for instance the [University of Washington](http://www.washington.edu/ucal/CLicense.html) are extremely similar. Do you know if I will violate somebody's copyright if I use the same phrases?

**Comment by ScriptSmith** [comment]
Unfortunately I have no experience with CLAs, so I can't give you any recommendations beyond that GitHub itself recommends [cla-assistant](https://github.com/cla-assistant/cla-assistant) in some cases. That might be too much for a project like this however

**Comment by mherrmann** [comment]
Okay, no problem. I've created a form with cla-assistant now. It's super-easy!

@ss18 sorry to bother you with this again (it's a pain I know). Could I ask you to [sign the official CLA](https://cla-assistant.io/mherrmann/fbs)? It's completely online, you simply sign in with GitHub. Really sorry for the hassle. But @ScriptSmith is right, it's important to do these things properly, in the interest of contributors as well as those of the project. Thanks.

**Comment by ss18** [comment]
@mherrmann no worries, done

**Comment by mherrmann** [comment]
@ss18 you're a star. Thanks!

**Comment by ss18** [comment]
:star:

**Comment by fredrikaverpil** [comment]
For the record, I've also signed the CLA.

**Comment by rth** [comment]
> The users install the PyQt5 dependency themselves. And I do have an agreement with Riverbank computing.

Also some users might be using PySide2 (as done in https://github.com/mherrmann/fbs/pull/1) or generally a wrapper such as [qtpy](https://github.com/spyder-ide/qtpy) or [Qt.py](https://github.com/mottosso/Qt.py) so using fbs commercially does not necessarily imply the need for a commercial PyQt5 license..
