### ISSUE TITLE
ImportError After fbs freeze ( using opencv in application)

### ISSUE THREAD

**Issue by himanshus97** [mherrmann/fbs#130]
Hi, i,m creating an application (PyQt5) with camera (opencv-python) for macOs . it runs for `fbs run` and even there is no error under `fbs freeze --debug` ,
after successfully `fbs freeze` (with no errors) i got this error while executing application :-

```
Traceback (most recent call last):
  File "main.py", line 25, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages/cv2/__init__.py", line 3, in <module>
ImportError: dlopen(/Applications/data/Desktop/full_finalApp/target/YouSly/cv2/cv2.cpython-35m-darwin.so, 2): Symbol not found: __ZN10QBoxLayout10invalidateEv
  Referenced from: /Applications/data/Desktop/full_finalApp/target/YouSly/cv2/cv2.cpython-35m-darwin.so
  Expected in: /Applications/data/Desktop/full_finalApp/target/YouSly/PyQt5/../QtGui
 in /Applications/data/Desktop/full_finalApp/target/YouSly/cv2/cv2.cpython-35m-darwin.so
[1079] Failed to execute script main
```
i'am using **macOs Mojave - version 10.14.5**
```
- fbs - version 0.8.3 ; 
- Pyinstaller - version 3.4 ;
- opencv-python - version 4.1.0.15
```

**Comment by mherrmann** [comment]
Sounds to me a little like [this problem](https://stackoverflow.com/a/48177589/1839209). Maybe downgrading opencv and PyInstaller will help. If not, please open an issue on the [PyInstaller issue tracker](https://github.com/pyinstaller/pyinstaller/issues), as it's not really related to fbs.
