### ISSUE TITLE
Resource files not copying over.

### ISSUE THREAD

**Issue by jb41997** [mherrmann/fbs#133]
I'm on python 3.7.4 so I know it isn't officially supported yet.  If you don't want to answer because of that I totally understand and will close the issue.  

That said, everything is going great so far.  ```fbs run``` works great.  I'm having one little problem that I can't seem to make work.  I'm trying to include a config.ini file in the target directory so the end-users can change settings etc. before running the app.  However,  ```fbs freeze``` works only when I manually copy the config.ini into the target/app directory.  I was under the impression that I could include resource files and have them copied over automatically as long as I referenced them in the application code like so ```appctxt.get_resource('config.ini')```.  However, when I freeze the app, I get the error, "unable to find config.ini".  
Is there a better way to copy the file straight to the frozen app directory or do I need to manually perform this task?  I also tried the Info.plist file in the ```src/freeze/mac``` directory.  It doesn't appear to copy to the target/app either.

All this is PySide2 5.12.3 and MacOS 10.14.6

thanks for any insight!

**Comment by mherrmann** [comment]
Hi, is your `config.ini` in `src/main/resources/base`?

**Comment by jb41997** [comment]
Yes

**Comment by mherrmann** [comment]
And it ends up in your app's frozen directory as well? `find target -name config.ini`

**Comment by jb41997** [comment]
Ah, it shows up here:  ```target/app.app/Contents/Resources/config.ini``` but i'm running 
```
cd target/app
./app
```

**Comment by mherrmann** [comment]
What does `print(appctxt.get_resource('config.ini'))` give, when you run the frozen form of your app?

**Comment by jb41997** [comment]
Alright, so when I launch from ```target/app.app/Contents/MacOS``` it sees the config.ini just fine.  Which makes sense because it does indeed copy the config.ini to ```target/app.app/Contents/Resources/config.ini```.  I've been trying to run the app thats sitting in the directory ```target/app```.     

Ok, so is that the best place for a config.ini file though?  If the intention is for the end user to edit the file before launching the app?  I feel like maybe I should have it sitting outside somewhere?  Apologies for my ignorance, this is my first time using fbs and pyside2.  I really appreciate you're help!

One more little issue, the Info.plist isn't getting read.  I'm ending up with 2 versions.  Its reading one that is sitting here: ```target/app.app/Contents/Info.plist```` instead of the one I created which is getting copied here ```target/x42lite.app/Contents/Resources/Info.plist```

Again, thanks for the assistance!

**Comment by jb41997** [comment]
Everything is working as designed.  Thanks for the clarification.  Closing issue.
