### ISSUE TITLE
how to use 'ffmpeg'

### ISSUE THREAD

**Issue by wcyDreamer** [mherrmann/fbs#134]
in my project, i use 'ffmpeg' script. fbs run is ok and fbs freeze is ok. but the app don't work. the reason is that i use subprocess `comm = 'ffmpeg -i a.mp3 -ac 1 -ar 16000 -y b.wav' subprocess.call(comm, shell=True)`

**Comment by mherrmann** [comment]
Please ask this on StackOverflow.
