### ISSUE TITLE
failed to execute script fbs_pyinstaller _ hook after fbs freeze

### ISSUE THREAD

**Issue by alpha999999999999** [mherrmann/fbs#135]
Hello, 
First off thank you for fbs @mherrmann, I have problem when freezing and run the app
I have just tried fbs few day ago, when I try to freezing .py (pyqt5) to .exe, when I run command `fbs run` everything work but when I clicked to .exe app it throws error. What happend there ? How I can fix this?

![image](https://user-images.githubusercontent.com/40297209/62584500-13263680-b8df-11e9-97d8-6cfcadc703cd.png)

* Windows 10
* Anaconda  
* Python 3.6
* Pyqt5 

Thank for reading!

**Comment by mherrmann** [comment]
Closing this because you didn't follow the steps in https://build-system.fman.io/troubleshooting.
