### ISSUE TITLE
failed to execute script main

### ISSUE THREAD

**Issue by alpha999999999999** [mherrmann/fbs#138]
First of all, thank Mr.mherrmann for fbs library
I have used fbs to make an installer pyqt5 but file .exe not working (fbs run is worked)
no import error found when i run fbs clean and fbs freeze --debug, I don't know how to fix this ...
I have used ApplicationContext and QMainWindow 

![Screenshot from 2019-08-17 23-33-28](https://user-images.githubusercontent.com/40297209/63219969-f8d63d80-c1a7-11e9-97a2-93a349375b07.png)

here is all pakage I used:
environment: venv , window10, Pycharm, python 3.6
* fbs==0.8.3
* PyInstaller==3.4
* PyQt5==5.9.2
* altgraph==0.16.1
* APScheduler==3.6.1
* future==0.17.1
* macholib==1.11
* numpy==1.17.0
* pefile==2019.4.18
* pytz==2019.2
* pywin32==224
* pywin32-ctypes==0.2.0
* sip==4.19.8
* six==1.12.0
* tzlocal==2.0.0

Thank for reading!

**Comment by mherrmann** [comment]
From the [instructions for creating issues](https://github.com/mherrmann/fbs/blob/master/.github/issue_template.md):

> let us know the following:
> ...
> A (minimal!) script that reproduces the problem you are experiencing.

Closing this issue because you didn't follow the instructions.
