### ISSUE TITLE
Where to include an associated executable and libraries

### ISSUE THREAD

**Issue by breisfeld** [mherrmann/fbs#140]
Hi,

I am building a GUI for a custom scientific computing engine using PyQT5. The engine comprises an executable and some libraries. 

Would either of the 'Extra files' or 'Resource files' areas mentioned in the fbs manual be an appropriate place to store these files and have them reliably installed? Or, would this be better accomplished by customizing the (NSIS or other) installer script? 

Thanks.

**Comment by mherrmann** [comment]
Hi, what do you mean by "installed"? Where do you want the files to end up? In the installation directory of your app? Or elsewhere? If in the installation directory, then you can just put any files you want to end up in the installation directory in `src/main/resources/base` for instance.

**Comment by breisfeld** [comment]
Hello,

Thank you for your reply.

By 'installed' I mean that when and end user double clicks on the installer, both the PyQT code and the engine and libraries are copied to the user's machine. It sounds like using `src/main/resources/base` may be a suitable method. However, I presume that if I wanted to have the engine copied to somewhere else, like the appdir (e.g., `C:\Documents and Settings\<User>\Application Data\Local Settings\<AppAuthor>\<AppName>` on windows), I would have to customize the installer script.

**Comment by mherrmann** [comment]
Yes, if you want some files to end up in a different location, then you'll need to customize the installer.
