### ISSUE TITLE
PyQT5 Upgrade from 5.11 to 5.13 - Freeze Target Qt5Core.dll Not Found until PATH updated

### ISSUE THREAD

**Issue by EdLipson5117** [mherrmann/fbs#141]
Not a significant issue but want to make you aware.
Freeze was working fine at 5.11.0, which was installed with QT Designer. Upgrading to 5.13.0 and Freeze runs to completion, but the program can't find the Qt5Core.dll even when started in the target pgm directory. Adding the target pgm directory to the path resolves the fail and the program runs.

 * Your operating system(s) Win 10 VDS
 * Your Python version (Must be 3.5 or 3.6 because you followed the above instructions.) 3.6.8
 * Your fbs version 0.8.3
 * Your PyInstaller version 3.4
 * Your PyQt5 / PySide2 version 5.13.0 for both, just importing PyQT5

**Comment by mherrmann** [comment]
Thank you for letting me know. I'm closing this because I officially only support PyQt5 5.9.2 (see [troubleshooting](https://build-system.fman.io/troubleshooting)). If you must use 5.13.0, then I suggest you open an issue on github.com/pyinstaller/pyinstaller.

**Comment by eduardtudor21** [comment]
This looks like a bug in pyqt5 5.13 find_qt function in Windows.
https://www.riverbankcomputing.com/pipermail/pyqt/2019-August/042069.html

Work around is to delete the function.
https://www.riverbankcomputing.com/pipermail/pyqt/2019-August/042082.html

**Comment by yishenggudou** [comment]
@EdLipson5117 @mherrmann 
Thank you for your reply
I change to use PySide2 

Add the following code to my make file 

it can build a mac app successful

```
	cp -vf venv/lib/python3.6/site-packages/shiboken2/libshiboken2.abi3.5.13.dylib venv/lib/python3.6/site-packages/PyInstaller/hooks/
	cp -vf venv/lib/python3.6/site-packages/shiboken2/libshiboken2.abi3.5.13.dylib  venv/lib/python3.6/site-packages/PySide2/
	fbs freeze
	mkdir -p target/acu.app/Contents/MacOS/ui
	cp -vrf src/main/python/ui/*  target/acu.app/Contents/MacOS/ui/
```

**Comment by yishenggudou** [comment]
the ui directory include all my `qml` files
