### ISSUE TITLE
fbs freeze is not copying resources to target/myApp

### ISSUE THREAD

**Issue by wtflove** [mherrmann/fbs#143]
I am having this issue that fbs freeze is not automatically copying my .xlsx file under resources/base to, according to the guide, target/myApp folder.
I copied the .xlsx file to the folder by myself, and the app works well.

What I did:
fbs run, print(appctxt.get_resource('myXlsxFile.xlsx')) gives me:
FileNotFoundError: [Errno 2] No such file or directory: 'path\to\project\src\main\python\myXlsxFile.xlsx'

I am using:
PyQt5==5.9.3
python==3.6.8
pyinstaller==3.5
windows==10

How can I let the program do it automatically?
Anyone can help trouble shoot my issue?

Thank you all!

**Comment by mherrmann** [comment]
Can you create a minimal example that reproduces the problem?

**Comment by wtflove** [comment]
I put the resources under a wrong dir... This lib works great! Thank you contributors!
