### ISSUE TITLE
Question about fbs Installer

### ISSUE THREAD

**Issue by Rauman** [mherrmann/fbs#144]
Hello, 
I have a scrip with Python, Pyqt5 ( of course ) and Matplotlib. I make the installer for the application, now the question is; this application will  work in other PC only with the installer? or needs the target PC Matplotlib, Pyqt5 and Python already installed?

Thaks a lot ¡

**Comment by mherrmann** [comment]
The target PC does not need Matplotlib, PyQt5, Python, etc. In theory. You need to test whether that actually works. If not, you may need to apply some fixes. But once everything's set up correctly, yes, then the installer and .exe produced by `fbs installer` and `fbs freeze`, respectively, will run on your users' systems without any extra dependencies.
