### ISSUE TITLE
How to add uac-admin option while doing fbs freeze?

### ISSUE THREAD

**Issue by zencore-cn** [mherrmann/fbs#149]
Command "fbs freeze" auto generate a pyinstaller command, but seems missing a way to enable --uac-admin option.

**Comment by mherrmann** [comment]
I'm afraid this is currently not supported. Here's how to work around this:

Create a file `build.py` in your main project directory, according to [these instructions](https://build-system.fman.io/manual/#custom-commands). Create your own version of [the built-in `freeze` command](https://github.com/mherrmann/fbs/blob/bd93efba6f9c515416035c42bfe84d04cb1fc454/fbs/builtin_commands/__init__.py#L98-L140). In it, you will invoke [`run_pyinstaller(...)`](https://github.com/mherrmann/fbs/blob/bd93efba6f9c515416035c42bfe84d04cb1fc454/fbs/freeze/__init__.py#L14), passing the extra argument you want.
