### ISSUE TITLE
fbs freeze doesn't output loggings to a file

### ISSUE THREAD

**Issue by kkagill** [mherrmann/fbs#153]
Thanks for this wonderful package.
I just found that fbs has some problem with packaging log file.
For example, 
I output loggings to a file like below 
```
import logging
logging.basicConfig(filename="./log_file.log",
                    filemode='a',
                    format='%(asctime)s',
                    datefmt='%H:%M:%S',
                    level=logging.ERROR)
```
This works with `fbs run`, but when I `fbs freeze` or/then `fbs installer` I encounter this error:
`Failed to execute script main`

In order to troubleshoot, I `fbs clean` then `fbs freeze --debug`, but couldn't find any valid error messages relating to `logging.basicConfig`

Can you take a look at this please as outputing a log file is quite important in many programs?

 * Windows 10
 * Python 3.6.8
 * fbs 0.8.4
 * PyInstaller 3.5
 * PyQt5 5.9.2

**Comment by mherrmann** [comment]
What happens when you replace `./log_file.log` by the absolute path to a (writeable) file? Eg. `"C:\\Users\\yourname\\log_file.log"`?

**Comment by kkagill** [comment]
Thanks for the hint I solved it via

```
logging.basicConfig(filename=str(Path.home()) + "\\" + "log_file.log",
                    filemode='a',
                    format='%(asctime)s',
                    datefmt='%H:%M:%S',
                    level=logging.ERROR)
```

**Comment by gkandler** [comment]
Okay so I guess what you wrote isn't entirely correct:

> fbs has some problem with packaging log file.

I'm closing this issue.
