### ISSUE TITLE
Cryptic MacOSX Error on fbs installer

### ISSUE THREAD

**Issue by alexrockhill** [mherrmann/fbs#154]
* Your operating system(s)
MacOS Catalina
 * Your Python version (Must be 3.5 or 3.6 because you followed the above instructions.)
3.6.7
 * Your fbs version
0.8.4
 * Your PyInstaller version
3.5
 * Your PyQt5 / PySide2 version
5.11.3
 * A copy of any error messages you are getting. Use ```...``` to format them.

```
(sfvenv3) alexrockhill@Alexs-MacBook-Pro SlowFastQt % sudo fbs installer
waited 1 seconds for .DS_STORE to be created.
hdiutil: internet-enable: verb not recognized
Usage: hdiutil <verb> <options>
<verb> is one of the following:
help
attach
detach
eject
verify
create
compact
convert
burn
info
checksum
chpass
erasekeys
unflatten
flatten
imageinfo
isencrypted
makehybrid
mount
mountvol
unmount
plugins
resize
segment
pmap
udifderez
udifrez
Traceback (most recent call last):
  File "/Users/alexrockhill/software/anaconda3/envs/sfvenv3/bin/fbs", line 8, in <module>
    sys.exit(_main())
  File "/Users/alexrockhill/software/anaconda3/envs/sfvenv3/lib/python3.6/site-packages/fbs/__main__.py", line 17, in _main
    fbs.cmdline.main()
  File "/Users/alexrockhill/software/anaconda3/envs/sfvenv3/lib/python3.6/site-packages/fbs/cmdline.py", line 32, in main
    fn(*args)
  File "/Users/alexrockhill/software/anaconda3/envs/sfvenv3/lib/python3.6/site-packages/fbs/builtin_commands/__init__.py", line 183, in installer
    create_installer_mac()
  File "/Users/alexrockhill/software/anaconda3/envs/sfvenv3/lib/python3.6/site-packages/fbs/installer/mac/__init__.py", line 21, in create_installer_mac
    ], stdout=DEVNULL)
  File "/Users/alexrockhill/software/anaconda3/envs/sfvenv3/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/Users/alexrockhill/software/anaconda3/envs/sfvenv3/lib/python3.6/site-packages/fbs/installer/mac/create-dmg/create-dmg', '--volname', 'SlowFast', '--app-drop-link', '170', '10', '--icon', 'SlowFast.app', '0', '10', '/Users/alexrockhill/education/UO/SwannLab/SlowFast/task versions/SlowFastQt/target/SlowFast.dmg', '/Users/alexrockhill/education/UO/SwannLab/SlowFast/task versions/SlowFastQt/target/SlowFast.app']' returned non-zero exit status 1.
```

 * A (minimal!) script that reproduces the problem you are experiencing.
Not sure how to make a minimal script that produces the issue, this is just when happens when I run "fbs installer" with the above specs.

**Comment by alexandramartinez** [comment]
I have the same issue

MacOS Catalina
Python 3.7
fbs 0.8.4
PyInstaller 3.5
PyQt5 5.14.0

**Comment by sneakypete81** [comment]
This ("internet-enable") is a feature removed in MacOS Catalina. See  https://github.com/electron-userland/electron-builder/issues/4405 for more context.

**Comment by iwctwbai** [comment]
I have the same issue.
how to fix it?
@sneakypete81 
@alexrockhill 
@alexandramartinez

**Comment by iwctwbai** [comment]
it works
> 
import platform
from fbs import path, SETTINGS
from os import replace, remove
from os.path import join, dirname, exists
from subprocess import check_call, DEVNULL


def create_installer_mac():
    app_name = SETTINGS['app_name']
    dest = path('target/${installer}')
    dest_existed = exists(dest)
    if dest_existed:
        dest_bu = dest + '.bu'
        replace(dest, dest_bu)
    try:
        pdata = [
            join(dirname(__file__), 'create-dmg', 'create-dmg'),
            '--volname', app_name,
            '--app-drop-link', '170', '10',
            '--icon', app_name + '.app', '0', '10',
            dest,
            path('${freeze_dir}')
        ]
        if platform.system() == 'Darwin' and int(platform.platform()[7:][:2]) >= 19: # if macOS Catalina
            pdata.insert(1,'--no-internet-enable')
        check_call(pdata, stdout=DEVNULL)
    except BaseException:
        if dest_existed:
            replace(dest_bu, dest)
        raise
    else:
        if dest_existed:
            remove(dest_bu)

**Comment by iwctwbai** [comment]
It works. 
`import platform
from fbs import path, SETTINGS
from os import replace, remove
from os.path import join, dirname, exists
from subprocess import check_call, DEVNULL


def create_installer_mac():
    app_name = SETTINGS['app_name']
    dest = path('target/${installer}')
    dest_existed = exists(dest)
    if dest_existed:
        dest_bu = dest + '.bu'
        replace(dest, dest_bu)
    try:
        pdata = [
            join(dirname(__file__), 'create-dmg', 'create-dmg'),
            '--volname', app_name,
            '--app-drop-link', '170', '10',
            '--icon', app_name + '.app', '0', '10',
            dest,
            path('${freeze_dir}')
        ]
        if platform.system() == 'Darwin' and int(platform.platform()[7:][:2]) >= 19:
            pdata.insert(1,'--no-internet-enable')
        check_call(pdata, stdout=DEVNULL)
    except BaseException:
        if dest_existed:
            replace(dest_bu, dest)
        raise
    else:
        if dest_existed:
            remove(dest_bu)`

**Comment by iwctwbai** [comment]
`import platform
from fbs import path, SETTINGS
from os import replace, remove
from os.path import join, dirname, exists
from subprocess import check_call, DEVNULL

def create_installer_mac():
app_name = SETTINGS['app_name']
dest = path('target/${installer}')
dest_existed = exists(dest)
if dest_existed:
dest_bu = dest + '.bu'
replace(dest, dest_bu)
try:
pdata = [
join(dirname(file), 'create-dmg', 'create-dmg'),
'--volname', app_name,
'--app-drop-link', '170', '10',
'--icon', app_name + '.app', '0', '10',
dest,
path('${freeze_dir}')
]
if platform.system() == 'Darwin' and int(platform.platform()[7:][:2]) >= 19:
pdata.insert(1,'--no-internet-enable')
check_call(pdata, stdout=DEVNULL)
except BaseException:
if dest_existed:
replace(dest_bu, dest)
raise
else:
if dest_existed:
remove(dest_bu)`

**Comment by iwctwbai** [comment]
@mherrmann

**Comment by mherrmann** [comment]
Sorry, I can't read this. If you'd like to submit a Pull Request @iwctwbai I'd be happy to take a look at it. Thanks!

**Comment by gudwns1215** [comment]
I think he added 
```
if platform.system() == 'Darwin' and int(platform.platform()[7:][:2]) >= 19:
    pdata.insert(1,'--no-internet-enable')
```
in fbs/fbs/installer/mac/__init__.py
and pdata is original paramter to "check_call" function

**Comment by komodovaran** [comment]
Properly formatted, the file should be:

````
import platform
from fbs import path, SETTINGS
from os import replace, remove
from os.path import join, dirname, exists
from subprocess import check_call, DEVNULL


def create_installer_mac():
    app_name = SETTINGS['app_name']
    dest = path('target/${installer}')
    dest_existed = exists(dest)
    if dest_existed:
        dest_bu = dest + '.bu'
        replace(dest, dest_bu)
    try:
        pdata = [
            join(dirname(__file__), 'create-dmg', 'create-dmg'),
            '--volname', app_name,
            '--app-drop-link', '170', '10',
            '--icon', app_name + '.app', '0', '10',
            dest,
            path('${freeze_dir}')
        ]
        if platform.system() == 'Darwin' and int(
            platform.platform()[7:][:2]) >= 19:
            pdata.insert(1, '--no-internet-enable')

            check_call(pdata, stdout = DEVNULL)
    except BaseException:
        if dest_existed:
            replace(dest_bu, dest)
        raise
    else:
        if dest_existed:
            remove(dest_bu)
````

**Comment by mherrmann** [comment]
Thank you @komodovaran.

The code should use `is_mac()` from module `fbs_runtime.platform` instead of `platform.system() == 'Darwin'` and `platform.mac_ver` instead of `platform.platform`. I'd also remove the `BaseException`.

If someone creates a Pull Request with these changes, I'd be happy to merge them into fbs.
