### ISSUE TITLE
Button works in target/x.app/Contents/MacOS/x but not by double clicking app

### ISSUE THREAD

**Issue by alexrockhill** [mherrmann/fbs#155]
Your operating system(s)
MacOS Catalina
Your Python version (Must be 3.5 or 3.6 because you followed the above instructions.)
3.6.7
Your fbs version
0.8.4
Your PyInstaller version
3.5
Your PyQt5 / PySide2 version
5.11.3
A copy of any error messages you are getting. Use ... to format them.
Nothing happens on button press

A (minimal!) script that reproduces the problem you are experiencing.
Not super minimal but fairly minimal, this is the contents of a main.py file that can be run with the default "fbs startproject"

import sys
import json
import os.path as op
import serial
import time
import numpy as np
from fbs_runtime.application_context.PyQt5 import ApplicationContext
from PyQt5.QtWidgets import (QApplication, QMainWindow, QLabel, QPushButton,
                             QWidget, QLineEdit, QStackedWidget)
from PyQt5.QtGui import QFont
from PyQt5.QtCore import Qt, pyqtSlot, QTimer, QEventLoop
from datetime import datetime

HIGH_SCORE = 1222
N_TRIALS = 600
N_PRACTICE_TRIALS = 20
SEED = 11
PRACTICE_SEED = 12
MIN_FIXATION = 0.1
MAX_FIXATION = 3
MIN_ITI = 2
MAX_ITI = 3
FEEDBACK_TIME = 2
BLOCKS = 8

PORT = 'COM4'
BAUDRATE = 115200
BYTESIZE = 8

class AppContext(ApplicationContext):
    def run(self):
        exp = SlowFast(1200, 800)
        exp.show()
        return self.app.exec_()

class SlowFast(QMainWindow):

    def __init__(self, width, height):
        super().__init__()
        self.setWindowTitle('SlowFast')
        self.width = width
        self.height = height * 0.9
        self.small_font = QFont('Helvetica', 20 * height / 800)
        self.large_font = QFont('Helvetica', 40 * height / 800)
        self.stim_font = QFont('Helvetica', 200 * height / 800)
        self.setGeometry(0, 0, self.width, self.height)

        # Set window background color
        self.setAutoFillBackground(True)
        p = self.palette()
        p.setColor(self.backgroundRole(), Qt.black)
        self.setPalette(p)

        # initialize meta data
        self.practice = None
        self.output = None
        self.subject = None
        self.run = None
        self.date_of_birth = None
        self.sex = None
        self.testing = None

        # initialize task data
        self.trial = 0
        self.block = 0
        self.total_points = 0
        self.slow_or_fast = 'slow'
        self.this_points = 0
        self.fixation = None
        self.stim = None
        self.response = None
        self.response_time = None
        self.left_or_right = None
        self.behavior_fname = None

        # initialialize derived meta data
        self.correct_keys = None
        self.fixations = None
        self.ITIs = None
        self.seed = None
        self.n_trials = None
        self.blocks = None

        self.allow_response = False
        self.data_entries = {}
        self.date = datetime.now().strftime('%Y-%m-%d')

        self.stack = QStackedWidget(self)
        self.setCentralWidget(self.stack)
        self.stack.addWidget(self.start_screen())  # 0
        self.stack.addWidget(self.instruction_screen())  # 1
        self.stack.addWidget(self.fixation_screen())  # 2
        self.stack.addWidget(self.task_screen())  # 3
        self.stack.addWidget(self.feedback_screen())  # 4
        self.stack.addWidget(self.end_menu())  # 5
        self.stack.addWidget(self.finished_screen())  # 6
        self.stack.addWidget(QWidget())  # 7

    # HELPER FUNCTIONS
    def label(self, widget, loc, text, font):
        label = QLabel(text, widget)
        self.setPosition(label, *loc)
        label.setFont(font)
        label.setAlignment(Qt.AlignCenter)
        label.setStyleSheet('color: white')
        return label

    def entry(self, widget, loc, text, font, default=None):
        entry = QLineEdit(widget)
        self.setPosition(entry, *loc)
        if default is not None:
            entry.setText(default)
        entry.setFont(font)
        entry.setAlignment(Qt.AlignCenter)
        self.data_entries[text] = entry
        return entry

    def button(self, widget, loc, text, font, command):
        button = QPushButton(text, widget)
        self.setPosition(button, *loc)
        button.setFont(font)
        button.clicked.connect(command)
        return button

    def pd_square(self, widget):
        pd_square = self.label(widget, [0.9, 1.0, 0.94, 1.0], '',
                               self.small_font)
        pd_square.setStyleSheet('background-color: white')

    def setPosition(self, widget, y0, y1, x0, x1):
        widget.move(int(x0 * self.width),
                    int(y0 * self.height))
        widget.resize(int((x1 - x0) * self.width),
                      int((y1 - y0) * self.height))

    def wait(self, secs):
        loop = QEventLoop()
        QTimer.singleShot(secs * 1000, loop.quit)
        loop.exec_()

    # SCREENS
    def start_screen(self):
        defaults = {'Practice (Y/N)': 'Y', 'Subject': 'test',
                    'Run': '1', 'Date of Birth': '20190101',
                    'Sex': 'f', 'Testing': 'Y'}
        start_screen = QWidget()
        self.label(start_screen, [0.07, 0.1, 0.4, 0.6], 'Practice (Y/N)',
                   self.small_font)
        self.entry(start_screen, [0.1, 0.15, 0.4, 0.6], 'Practice (Y/N)',
                   self.small_font, defaults['Practice (Y/N)'])
        self.label(start_screen, [0.17, 0.2, 0.4, 0.6], 'Subject',
                   self.small_font)
        self.entry(start_screen, [0.2, 0.25, 0.4, 0.6], 'Subject',
                   self.small_font,
                   defaults['Subject'])
        self.label(start_screen, [0.27, 0.3, 0.4, 0.6], 'Run', self.small_font)
        self.entry(start_screen, [0.3, 0.35, 0.4, 0.6], 'Run', self.small_font,
                   defaults['Run'])
        self.label(start_screen, [0.37, 0.4, 0.4, 0.6], 'Date of Birth',
                   self.small_font)
        self.entry(start_screen, [0.4, 0.45, 0.4, 0.6], 'Date of Birth',
                   self.small_font,
                   defaults['Date of Birth'])
        self.label(start_screen, [0.47, 0.5, 0.4, 0.6], 'Sex', self.small_font)
        self.entry(start_screen, [0.5, 0.55, 0.4, 0.6], 'Sex', self.small_font,
                   defaults['Sex'])
        self.label(start_screen, [0.57, 0.6, 0.4, 0.6], 'Testing',
                   self.small_font)
        self.entry(start_screen, [0.6, 0.65, 0.4, 0.6], 'Testing',
                   self.small_font, defaults['Testing'])
        self.button(start_screen, [0.67, 0.75, 0.4, 0.6], 'Start',
                    self.small_font, self.start_task)
        return start_screen

    def fixation_screen(self):
        fixation_screen = QWidget()
        self.label(fixation_screen, [0.1, 0.9, 0.1, 0.9],
                   '+', self.stim_font)
        self.pd_square(fixation_screen)
        return fixation_screen

    def task_screen(self):
        task_screen = QWidget()
        task_screen.stimulus = self.label(task_screen,
                                          [0.1, 0.9, 0.1, 0.9],
                                          '', self.stim_font)
        self.pd_square(task_screen)
        return task_screen

    def instruction_screen(self):
        instruction_screen = QWidget()
        instruction_screen.fast_message = \
            ('Fast block\n\nThe faster your respond\n' +
             'the higher your score\n' +
             '(with a wrong answer penalty)')
        instruction_screen.slow_message = \
            ('Slow block\n\n\nThe closer your score is to\n' +
             '0.5 seconds, the higher your score\n' +
             '(with a wrong answer penalty)')
        instruction_screen.label = \
            self.label(instruction_screen, [0.1, 0.9, 0.1, 0.9], '',
                       self.large_font)
        return instruction_screen

    def feedback_screen(self):
        feedback_screen = QWidget()
        feedback_screen.total = \
            self.label(feedback_screen, [0.25, 0.45, 0.1, 0.9], '',
                       self.large_font)
        feedback_screen.this = \
            self.label(feedback_screen, [0.45, 0.65, 0.1, 0.9], '',
                       self.large_font)
        feedback_screen.rt = \
            self.label(feedback_screen, [0.65, 0.85, 0.1, 0.9], '',
                       self.large_font)
        self.label(feedback_screen, [0.05, 0.15, 0.05, 0.25],
                   'High Score: %i points' % HIGH_SCORE,
                   self.small_font)
        return feedback_screen

    def end_menu(self):
        end_menu = QWidget()
        self.label(end_menu, [0.25, 0.35, 0.4, 0.6], 'End of Block',
                   self.small_font)
        self.button(end_menu, [0.45, 0.55, 0.4, 0.6], 'Continue',
                    self.small_font, self.start_block)
        return end_menu

    def finished_screen(self):
        finished_screen = QWidget()
        self.label(finished_screen, [0.4, 0.6, 0.2, 0.8],
                   'The task is complete\n' +
                   'thank you for participating',
                   self.large_font)
        return finished_screen

    @pyqtSlot()
    def start_task(self):
        self.meta_data()
        if self.testing == 'N':
            self.output = serial.Serial(port=PORT, baudrate=BAUDRATE,
                                        bytesize=BYTESIZE, timeout=2,
                                        stopbits=serial.STOPBITS_ONE)
            self.output.open()
        np.random.seed(self.seed)
        correct_keys = None
        while correct_keys is None or (
            len(correct_keys[correct_keys == 'left']) -
                len(correct_keys[correct_keys == 'right']) < 2):
            correct_keys = np.random.randint(0, 2, self.n_trials)
            correct_keys = correct_keys.astype(str)
            correct_keys[correct_keys == '0'] = 'left'
            correct_keys[correct_keys == '1'] = 'right'
        self.correct_keys = correct_keys

        self.fixations = (np.random.random(self.n_trials) *
                          (MAX_FIXATION - MIN_FIXATION) + MIN_FIXATION)

        self.ITIs = (np.random.random(self.n_trials) *
                     (MAX_ITI - MIN_ITI) + MIN_ITI)

        self.start_block()

    def start_block(self):
        self.stack.setCurrentIndex(1)
        instruction_screen = self.stack.currentWidget()
        if self.slow_or_fast == 'fast':
            instruction_screen.label.setText(instruction_screen.fast_message)
        elif self.slow_or_fast == 'slow':
            instruction_screen.label.setText(instruction_screen.slow_message)
        else:
            raise ValueError('Unexpected slow_or_fast %s' % self.slow_or_fast)
        self.wait(5)
        self.stack.setCurrentIndex(7)
        self.wait(3)
        self.next_stimulus()

    def end_of_block(self):
        if self.slow_or_fast == 'slow':
            self.slow_or_fast = 'fast'
        elif self.slow_or_fast == 'fast':
            self.slow_or_fast = 'slow'
        else:
            raise ValueError('Unrecognized slow_or_fast value')
        self.block += 1
        self.total_points = 0
        self.stack.setCurrentIndex(5)

    def next_stimulus(self):
        self.response = self.response_time = None
        self.left_or_right = self.correct_keys[self.trial]
        self.show_fixation()
        self.wait(self.fixations[self.trial])
        self.allow_response = True
        self.show_stim()

    # SCREEN HELPERS
    def keyPressEvent(self, event):
        super(SlowFast, self).keyPressEvent(event)
        if self.allow_response:
            self.response_time = time.time() - self.stim
            if event.key() == Qt.Key_Left:
                self.response = 'left'
            elif event.key() == Qt.Key_Right:
                self.response = 'right'
            else:
                self.response = event.key()
            self.allow_response = False
            if self.testing == 'N':
                self.output.write(3)
            self.end_stim()

    def show_fixation(self):
        self.stack.setCurrentIndex(2)
        self.fixation = time.time()
        if self.testing == 'N':
            self.output.write(1)

    def show_stim(self):
        self.stack.setCurrentIndex(3)
        task_screen = self.stack.currentWidget()
        if self.correct_keys[self.trial] == 'left':
            task_screen.stimulus.setText('<')
        elif self.correct_keys[self.trial] == 'right':
            task_screen.stimulus.setText('>')
        else:
            raise ValueError('Something went wrong with correct_keys')
        if self.testing == 'N':
            self.output.write(2)
        self.stim = time.time()

    def end_stim(self):
        self.score()
        self.stack.setCurrentIndex(7)
        now = time.time()
        self.add_result()
        self.wait(self.ITIs[self.trial] - (time.time() - now))
        if self.trial >= self.n_trials - 1:
            if self.practice:
                self.trial = 0
                self.block = 0
                self.total_points = 0
                self.slow_or_fast = 'slow'
                self.this_points = 0
                self.stack.setCurrentIndex(0)
                self.data_entries['Practice (Y/N)'].setText('N')
                self.data_entries['Subject'].setText(self.subject)
                self.data_entries['Run'].setText(self.run)
                self.data_entries['Date of Birth'].setText(self.date_of_birth)
                self.data_entries['Sex'].setText(self.sex)
                self.data_entries['Testing'].setText(self.testing)
            else:
                self.stack.setCurrentIndex(7)
                if self.testing == 'N':
                    self.output.close()
        elif ((self.trial + 1) % int(self.n_trials / self.blocks) == 0):
            self.trial += 1
            self.end_of_block()
        else:  # main loop
            self.trial += 1
            self.next_stimulus()

    def score(self):
        correct = self.response == self.correct_keys[self.trial]
        if self.slow_or_fast == 'slow':
            self.this_points = 1 - 5 * abs(0.5 - self.response_time)
        elif self.slow_or_fast == 'fast':
            self.this_points = (0.5 - self.response_time) * 10
        self.this_points -= not correct
        self.this_points = int(np.round(self.this_points * 100))
        self.total_points += self.this_points
        self.stack.setCurrentIndex(4)
        feedback_screen = self.stack.currentWidget()
        feedback_screen.total.setText('Total Points: %i' % self.total_points)
        feedback_screen.this.setText('Points This Trial: ' +
                                     '%i' % self.this_points)
        feedback_screen.rt.setText('Response Time: %.2f' % self.response_time)
        self.wait(FEEDBACK_TIME)

    def meta_data(self):
        self.subject = self.data_entries['Subject'].text()
        self.run = self.data_entries['Run'].text()
        self.sex = self.data_entries['Sex'].text()
        self.date_of_birth = self.data_entries['Date of Birth'].text()
        self.practice = self.data_entries['Practice (Y/N)'].text()
        self.testing = self.data_entries['Testing'].text()
        if self.testing not in ['Y', 'N']:
            raise ValueError('Unrecognized Testing value %s' % self.testing)
        if self.practice == 'Y':
            self.practice = True
            self.n_trials = N_PRACTICE_TRIALS
            self.seed = PRACTICE_SEED
            self.blocks = 2
        elif self.practice == 'N':
            self.practice = False
            self.n_trials = N_TRIALS
            self.seed = SEED
            self.blocks = BLOCKS
        else:
            raise ValueError('Unrecognized Practice (Y/N) value ' +
                             '%s' % self.practice)
        self.behavior_fname = (('practice_' if self.practice else '') +
                               'sub-%s_' % self.subject +
                               'run-%s_task-SlowFast_' % self.run +
                               'date-%s.tsv' % self.date)
        if op.isfile(self.behavior_fname) and self.subject != 'test':
            raise ValueError('Subject name %s and ' % self.subject +
                             'run %s already used today' % self.run)
        labels = ['Trial', 'Response Time', 'Left or Right', 'Fixation Time',
                  'Go Time', 'Points', 'Total', 'Key Pressed', 'Slow or Fast',
                  'Block']
        with open(self.behavior_fname, 'w') as f:
            f.write('\t'.join(labels) + '\n')
        df2 = {'Subject': self.subject, 'Sex': self.sex,
               'Date of Birth': self.date_of_birth}
        if not op.isfile('participants.tsv'):
            with open('participants.tsv', 'w') as f:
                f.write('\t'.join(df2.keys()) + '\n')
        with open('participants.tsv', 'a') as f:
            f.write('\t'.join(df2.values()) + '\n')

    def add_result(self):
        result = [self.trial, self.response_time, self.left_or_right,
                  self.fixation, self.stim, self.this_points,
                  self.total_points, self.response, self.slow_or_fast,
                  self.block]
        with open(self.behavior_fname, 'a') as f:
            f.write('\t'.join([str(v) for v in result]) + '\n')

if __name__ == '__main__':
    appctxt = AppContext()
    exit_code = appctxt.run()
    sys.exit(exit_code)

**Comment by alexrockhill** [comment]
Also when I run this same example, although I tried to follow the directions for persisting data here: https://www.learnpyqt.com/courses/model-views/modelview-architecture/#a-persistent-data-store 

Nothing saves when I run the Contents/MacOS version. See the end of the file where I'm just trying to write to a file using the builtin open function.

**Comment by gkandler** [comment]
I'm sorry, this neither looks like a bug in fbs nor do I have time to read through this code. This issue tracker is for bugs / improvements in fbs. What you wrote is more of a "I need help with my script", at least until you prove to me that what is happening is a bug in fbs. I'm closing this issue. If you're interested in help with this, I advise you ask on StackOverflow.

**Comment by mherrmann** [comment]
I'm sorry, this neither looks like a bug in fbs nor do I have time to read through this code. This issue tracker is for bugs / improvements in fbs. What you wrote is more of a "I need help with my script", at least until you prove to me that what is happening is a bug in fbs. I'm closing this issue. If you're interested in help with this, I advise you ask on StackOverflow.

**Comment by alexrockhill** [comment]
This is not an “I need help with my code problem” it’s clearly a bug with fbs. The target executable works fine which means the PyQt5 app works fine. The issue is with the process by which fbs makes an x.app. No one has to read through all the code, just put main.py in a new startstart project folder and replicate the error. It’s a simple QPushButton that works with the executable but not in the process by which MacOS runs an app.

**Comment by alexrockhill** [comment]
The issue was actually with saving the data. Maybe the issue should be instead that it would be helpful if the app through errors. Sorry, that did involve more of the code and you were right to close this issue. Thanks

**Comment by mherrmann** [comment]
No problem. Thank you for letting me know. I'm happy to hear it works for you now.
