### ISSUE TITLE
vlc refuses to freeze

### ISSUE THREAD

**Issue by BoukeVahl** [mherrmann/fbs#159]
Hi Guys

>Have you already purchased a license for fbs, or are you planning to do so in the near future? 
No probs in purchasing a license, but for the moment I'm toying around as Python is quite new to me. (I'm a self-taught coder, coming from Director, with lots of bad habits. Python / QT / fbs is a life-saver for me.)

Now for the trouble:
with just an 'import vlc' in main,
I can't get python-vlc to freeze. 
On Win, normal freeze gives the 'Failed to execute script main', --debug gives me no executable at all.
On Mac, I get a lot of warnings of QT related missing stuff, no clue what that has to do with the VLC module.

Os: Both Windows 10 and OSX (something)
Python 3.7 (Yes, I know it's unsupported, but it was recommended by my mentor to use it anyways, and so far everything has worked just fine.)
PyInstaller 3.5
fbs 0.8.4
PyQt5 5.13.1

> Is it a problem with one of your dependencies? 
Most likely. I found several references on vlc / pyInstaller that I need to copy 'some' VLC stuff to 'some' location, but I have no clue how to adapt this to fbs and it's directory structure.

So, can anyone shed some light on this?

Thanks!
Bouke

**Comment by BoukeVahl** [comment]
Few steps closer:
On Windows:
I've copied:
libvlc.dll
libvlccore.dll
and the plugins folder to /src/main/resources/base

On Mac, I've copied just the plugins folder (out of the vlc package)

That seems to do the trick, although I'm a bit confused.
To my understanding, the vlc module uses the existing installation.
This seems the case on Mac. (If I uninstall VLC, the Python app won't run anymore.)
But on Windows, it keeps working fine even with VLC totally removed.
(Just on the two .dll's and the plugins.)

Another strange thing, the freezed stuff is HUGE
The Windows install folder is 278 MB, the Mac package is 201 MB
This is way more than I anticipated based on the plugin folders.

Last but not least, I have no clue if the frozen stuff will work on other machines.

Bouke

**Comment by mherrmann** [comment]
Sorry Bouke, but this is not the place for such questions. This issue tracker is for changes to be made to fbs, such as bug fixes or feature requests. It's not a place for "help me program my fbs-based app". I'm not even sure you'll get an answer here. I suggest you ask your question on StackOverflow.

**Comment by BoukeVahl** [comment]
Hi Michael,
No probs, I ‘sorta kinda’ expected something like this.
But in my defence, I’m kind of ignorant :-)
(I really have no clue what fbs actually ‘is’…)

Another thing, licensing:
Not sure if you have looked me up, but I’m selling software, and I have no idea if I’m breaking rules / misbehave.
I’m not a lawyer, I have no clue what I’m allowed / not allowed to re-sell. (I did look up GPL, but still I’m unsure, since basically I’m writing scripts that do tricks, but I have no clue if my work is ‘open’ or not…)

Last but not least, I’m totally willing to pay for support / licensing!
So, if you want some paid hours, or know someone who has some spare time and want to earn a few bucks, I’m game.


Bouke

www.VideoToolShed.com
van Oldenbarneveltstraat 33
6512 AS  Nijmegen
+31 6 21817248
To send files, go here:
https://videotoolshed.wetransfer.com/

**Comment by mherrmann** [comment]
Hi Bouke,

okay, thank you for understanding. fbs takes the Python code of applications based on PyQt or PySide and spits out standalone executables and installers.

Regarding the GPL: It basically means that, if you distribute your app to one of your users, then you must also give them your app's source code. I suspect that is not what you want.

I'd be happy to discuss this, and further questions such as consulting work, by email. If you are interested in this, feel free to contact me at [my first name] @ [my last name, double r, double n] dot io.
