### ISSUE TITLE
freezing the app is successful, but standalone .exe won't start

### ISSUE THREAD

**Issue by kkagill** [mherrmann/fbs#161]
Hello Michael,

Thanks for your work btw and I am looking forward to hearing from you since I'm having a bit of problem executing a standalone file.

I'm trying to use a module from `pip install slackclient` and imported in your `main.py`
```
from fbs_runtime.application_context.PyQt5 import ApplicationContext
from PyQt5.QtWidgets import QMainWindow
import slack
import sys

if __name__ == '__main__':
    appctxt = ApplicationContext()       # 1. Instantiate ApplicationContext
    window = QMainWindow()
    window.resize(250, 150)
    window.show()
    exit_code = appctxt.app.exec_()      # 2. Invoke appctxt.app.exec_()
    sys.exit(exit_code)
```

After `fbs freeze` which was successful, I clicked on the executable file from `~/target/`, but app was not opened. No errors or stack traces in the build dialog. 

If I removed `import slack`, then it can execute the file. Would it be the problem with the `slack`? Any guidance would be greatly appreciated.

 * Windows 10 Pro
 * 3.6.8 64-bit
 * pip install fbs PyQt5==5.9.2

**Comment by kkagill** [comment]
https://stackoverflow.com/questions/59350893/pyqt5-fbs-cant-execute-slack

**Comment by mherrmann** [comment]
Hi,

thank you for the nice words and I appreciate that you created a minimal example. But I do not have time to help you debug your dependencies. From the [issue template](https://github.com/mherrmann/fbs/blob/118572c037a03ab062f1dbc2d87827be2b5cc2e9/.github/issue_template.md):

> Is it a problem with one of your dependencies? [...] try googling "PyInstaller [your dependency problem]". If that doesn't help, please go to PyInstaller's issue tracker and request a fix there. fbs uses PyInstaller for dependency management and so any dependency-related problems should be fixed there.

I also saw that you asked the question on StackOverflow. That is the right place. So I'm closing this issue.
