### ISSUE TITLE
Pyinstaller does not look in src/main/python when freezing

### ISSUE THREAD

**Issue by ripdog** [mherrmann/fbs#162]
* Your operating system(s): Win10x64
 * Your Python version 3.6.8
 * Your fbs version 0.8.4
 * Your PyInstaller version 3.5
 * Your PyQt5 / PySide2 version 5.13.1

Hello! Thank you so much for fbs. 

TL;DR: When I run `fbs freeze`, PyInstaller does not look in `src/main/python` for modules. This means that every one of my own-module imports fail and are not added to the PYZ. They are then listed in the warn-appname.txt file as missing top-level imports. The generated spec file lists the `target/PyInstaller` directory alone in `pathex`.

I have converted an existing app to fbs. I generated a project with `fbs startproject` then moved my python to `src/main/python`, resources to the resources dir, etc. I populated base.json. I integrated `ApplicationContext` and got resource loading working correctly with `fbs run`. Then I tried to build it with `fbs freeze`. I can fix it by patching fbs to add `--path src/main/python` to the command line.

The executable is generated without any errors. When run, it fails quickly with the standard error. Rebuilding with `--debug`, I was able to observe that all of my modules failed to be found thanks to `warn-vapoursonic.txt`. I checked the spec file, and found that the `pathex` section only listed `/target/PyInstaller`.

I use poetry to manage my venv, as you can see in the command line below. 

I was able to fix the issue by adding the following to `fbs\freeze\windows.py` at line 18:

```python
args.extend(['--paths', path(r'src/main/python')])
```

Here's the pyinstaller command line which is generated:

```
pyinstaller --name vapoursonic --noupx --log-level DEBUG --noconfirm --icon C:\Users\ripdog\PycharmProjects\vapoursonic\src\main\icons\Icon.ico --distpath C:\Users\ripdog\PycharmProjects\vapoursonic\target --specpath C:\Users\ripdog\PycharmProjects\vapoursonic\target\PyInstaller --workpath C:\Users\ripdog\PycharmProjects\vapoursonic\target\PyInstaller --additional-hooks-dir C:\Users\ripdog\AppData\Local\pypoetry\Cache\virtualenvs\vapoursonic-ZCn5mK1A-py3.6\lib\site-packages\fbs\freeze\hooks --debug all --runtime-hook C:\Users\ripdog\PycharmProjects\vapoursonic\target\PyInstaller\fbs_pyinstaller_hook.py C:\Users\ripdog\PycharmProjects\vapoursonic\src\main\python\main.py
```

Here's a pastebin of the output of a failing freeze. Note that `src/main` is added to the path list, but not `src/main/python`.

https://pastebin.pl/view/2bdd8f41

And here's a fixed freeze after my patch:

https://pastebin.pl/view/852e6cd3

I'm going to assume you won't be willing to add my patch in as it is unnecessary for most people - that's quite fair enough. However, I would ask you to please add the generic ability to declare extra pyinstaller args in the build json files, as this would allow me to fix my issue without having to monkey-patch fbs or maintain a fork of the freeze function.

**Comment by mherrmann** [comment]
> I would ask you to please add the generic ability to declare extra pyinstaller args in the build json files

It's something I've been pondering for a while and a somewhat frequent stumbling block for other people as well. I will look into it when I have time.

In your particular case, maybe the problem can also be solved by using fbs's recommended PyQt version, 5.9.2.

**Comment by ripdog** [comment]
Thanks for your reply, @mherrmann . Sorry for the delay in replying.

I've worked on this for a while. I was initially sceptical, but reverting to PyQt5 5.9.2 did indeed remove the need for the patch on my dev machine. However, I'm also writing a github actions script to build a package. When built on gh actions, with the exact same python, pyqt, fbs versions, the issue reoccurred.

The next thing I tried was changing my imports to relative syntax, i.e. `config` to `.config`. This actually fixed PyInstaller and allowed it to find my imports both locally and on gh actions. However, the app does not run like this, due to this error:

```python
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
ModuleNotFoundError: No module named '__main__.config'; '__main__' is not a package
```

Error is the same whether running from source or frozen.

So next I tried moving all my code into a new module and using absolute imports again. Now that import is `modulename.config`. This actually both works and builds fine on my local machine and gh actions. It seems this is the solution.

It'd be great if this issue and solution could be documented the fbs website to prevent anymore helpess saps like myself from falling into this trap. I'm happy to write this myself, but I can't seem to find the repo for the website...?

Also, I do think the ability to declare pyinstaller args would be useful for lots of things, and as a general escape hatch when things go wrong. Thanks again for fbs, it's truly great.

**Comment by ripdog** [comment]
FWIW, I was able to bump the PyQt version back to 5.13.2 after putting my code in a package, and the code freezes fine both locally and on github.

**Comment by mherrmann** [comment]
So the problem was that you had

    src/main/python/
        main.py
        config.py

instead of

    src/main/python/
        package/
            main.py
            config.py

so you imported `config` instead of `package.config`?

**Comment by ripdog** [comment]
Yes, that's correct.

**Comment by ripdog** [comment]
@mherrmann Sorry for the ping, but I don't think github gives emails for closed issues (?)

I am getting my app to work on linux today, and discovered a flaw with my previous solution which you should mention if you add it to your troubleshooting page. The issue is that because linux executables have no extension, I ended up with a situation where my package directory and executable file had the same filenames, causing pyinstaller to break. (Pyinstaller would try to put my compiled python files in `package/`, but `package` is already a file.)

I submitted a [pull request](https://github.com/pyinstaller/pyinstaller/pull/4591) to provide a less confusing error message to pyinstaller, but I think this is worth documenting in your troubleshooting page too. I fixed the issue by appending `_pkg` to my package name.

**Comment by mherrmann** [comment]
I wonder why this is a problem for you at all? For instance, my file manager fman uses this name for the package as well as the executable and it's not a problem. The reason is that the package sources simply do not appear in the app directory:

![image](https://user-images.githubusercontent.com/1076393/71541202-a5de7500-2955-11ea-8923-0b23f42e72a4.png)

Note how there's an `fman` executable but no `fman/` directory.

**Comment by ripdog** [comment]
Yes. I understand that normally own-module imports go in the PYZ, but that wasn't working for me for who knows what reason, so after moving them into a named module, pyinstaller started putting the compiled files in a folder. 

If I could figure out the root cause for why pyinstaller can't find my own-module imports, I could get rid of the package and go back to plain import statements, and my code would end up in the PYZ. Still, in the absence of that, I'm happy with this.

Just to be clear, you don't import own-modules like `from fman.x import y`, do you?

**Comment by mherrmann** [comment]
`from fman.x import y` ist exactly how I import them.

**Comment by ripdog** [comment]
Well then I'm buggered. This is way out of my pay grade. 

Persumably the pyinstaller folks would know, but I can't file an issue there as I'm using an old pyinstaller version...
