### ISSUE TITLE
How to run my own python script with fbs at installation and at uninstallation time

### ISSUE THREAD

**Issue by Venktesh98** [mherrmann/fbs#163]
Actually my question is?

How to run my own script at the time of installation and also at the time of uninstallation ,as i am making the use of fbs with PyQt5 for creating an executable that when installed on system must be automatically registered in the Registry of windows and i wanna run my own PYTHON code that must be executed with installation script and when uninstaller.exe of fbs runs the specified folder created in python file must fade away from Windows Registry after uninstalling.

**Comment by mherrmann** [comment]
From the text you should have read when you clicked on "New issue":

> Are you here to get help with your app? Then please go to StackOverflow.com and ask there.

Closing this.
