### ISSUE TITLE
fbs freeze --debug --> How to catch executable output?

### ISSUE THREAD

**Issue by ChrisPHL** [mherrmann/fbs#164]
Hi there,

I wish you a happy new year 2020!

I'm trying to fix a "The application works but the fbs freeze'd version does not"-problem.
When I start the executable from cmd.exe (Windows of course) another cmd.exe comes up, tries to run my application (which produces some debug output btw.) and closes immediately. I cannot * manage to catch the output. What I tried so far:

- Just running `application.exe > debug.log 2>&1` produces an empty file.

- A batch file like this:
```
@echo off
call application.exe > debug.log 2>&1
pause
```
...runs the app within its own cmd window and pauses the window I called this file from (An empty log file is created also.).

Do you have any ideas how to get the output?

Thanks in advance!

kind regards
Christian

**Comment by mherrmann** [comment]
Hi Christian, did you add the `--debug` flag to freeze? `fbs freeze --debug`

**Comment by Lenormju** [comment]
To clarify, adding `--debug` when freezing enables **both** freezing debug **and** running debug.

**Comment by mherrmann** [comment]
Yes. My goal was for him to get console output. But he's not responding anymore anyways; so I'm closing this issue

**Comment by ChrisPHL** [comment]
Sorry for the late response.
Of course I used the `--debug` flag. This causes the addional cmd window to appear when I start the application.
Please give me/other users some more time to respond, I was very busy this weekend, sorry.
Nevertheless I managed to get the output using PyCharm's builtin Terminal which works like a charm with the debug freeze'd application. :-)

Kind regards
Christian
