### ISSUE TITLE
where to place .ui files i would like to load

### ISSUE THREAD

**Issue by yashu2001** [mherrmann/fbs#165]
Hi please help me on where to place my .ui files designed using qt designer in the fbs direcotry structure?

**Comment by mherrmann** [comment]
You can place them in `src/main/resources/base`, eg. `src/main/resources/base/my.ui` then use [`get_resource('my.ui')`](https://build-system.fman.io/manual/#get_resource) as in the [tutorial](https://github.com/mherrmann/fbs-tutorial) and `uic.loadUi(...)` to load it. For further questions, please ask on StackOverflow, as this issue tracker is for bugs and improvements to fbs, not for getting help with your app.
