### ISSUE TITLE
macOS Catalina Dark Mode Error

### ISSUE THREAD

**Issue by luigifreitas** [mherrmann/fbs#166]
The macOS Catalina dark mode isn't working as expected with `fbs freeze`. The `fbs run` window seems to work fine. The same behavior is observed with the example project. I tried to add the `NSRequiresAquaSystemAppearance` key to the `info.plist`. This seems to help but nothing was displayed on the window. I'm running the Qt 5.14.1.

![Screen Shot 2020-01-11 at 3 52 07 AM](https://user-images.githubusercontent.com/6627901/72200252-fb228800-3425-11ea-8b2b-6f9286c09419.png)

![Screen Shot 2020-01-11 at 3 57 27 AM](https://user-images.githubusercontent.com/6627901/72200292-80a63800-3426-11ea-844f-4989be29601c.png)

**Comment by j9ac9k** [comment]
@luigifreitas I haven't tried PySide2 5.14.1 yet (I'm still running on PySide2 5.12.5) but I had this very issue occur when I was running off of a conda based python distribution. 

Do you get the same behavior with `fbs startproject` and then `fbs freeze`?

**Comment by luigifreitas** [comment]
@j9ac9k Yes, this occurs with the frozen `fbs startproject` too.

**Comment by j9ac9k** [comment]
You're not by chance using a conda distribution of python?

**Comment by j9ac9k** [comment]
Wait, how are you on PySide2 5.14.1? That hasn't been released yet... Qt 5.14.1 isn't scheduled for release until the 21st of January.

**Comment by luigifreitas** [comment]
> Wait, how are you on PySide2 5.14.1? That hasn't been released yet... Qt 5.14.1 isn't scheduled for release until the 21st of January.

My bad, I'm using Qt version 5.14.0.

> You're not by chance using a conda distribution of python?

Nope, this is the `brew` version.

**Comment by luigifreitas** [comment]
After further research, I think this issue isn't caused by FBS. Closing.
