### ISSUE TITLE
shutil.which doesn't work

### ISSUE THREAD

**Issue by fredrikaverpil** [mherrmann/fbs#17]
I'm creating a Tutorial.app on macOS and I'm trying to figure out why I can't get `shutil.which('someapp')` to work. It keeps returning `None` whichever program I'm trying to look up if I run the frozen app. If I run the fbs app using `python -m fbs run`, the `shutil.which` returns the program path as expected.

I've also tried to write a custom "which" for my application, which checks for filenames on PATH which have `os.access(fpath, os.X_OK)`... but this also won't return anything other than `None` under the frozen mac .app.

PyInstaller actually has its own [compatibility library](https://github.com/persepolisdm/mac-package-build/blob/master/pyinstaller/PyInstaller/compat.py) which seems to include `shutil.which` and an implementation of searching through PATH for executables (using `os.X_OK`), so to me it kind of seems like it _should_ work... 🤔 

Any ideas?

**Comment by fredrikaverpil** [comment]
Hm, I think that the issue lies within that the system path has been limited to `/usr/bin:/bin:/usr/sbin:/sbin` for some reason.

**Comment by mherrmann** [comment]
Yes, I believe PyInstaller changes the PATH of the frozen app. Your workaround sounds like a good solution. I'm closing this issue because I believe the problem has been solved.
