### ISSUE TITLE
Hidden import 'Crypto' not found

### ISSUE THREAD

**Issue by hanson2010** [mherrmann/fbs#186]
I met import error while running freezed application. And I've pip installed the dependency and added the dependency 'Crypto' to ```hidden_imports``` already.

Operating system: Windows 10 x64
Python version 3.5
fbs version 0.8.6
PyInstaller version 3.4
PyQt5 version 5.13.0

While running freeze, it complains:
```
2310 ERROR: Hidden import 'Crypto' not found
Done. You can now run `target\xxx\xxx.exe`. If that
doesn't work, see https://build-system.fman.io/troubleshooting.
```

And while running the application, it saids:
```
ImportError: No module named 'Crypto'
```

**Comment by mherrmann** [comment]
fbs uses PyInstaller for packaging. PyInstaller handles dependencies such as Crypto. This needs to be fixed (/maybe already is fixed in recent versions of) PyInstaller. Please ask on PyInstaller's issue tracker.
