### ISSUE TITLE
Adding sys.argv flags to QApplication in ApplicationContext

### ISSUE THREAD

**Issue by arnauddhaene** [mherrmann/fbs#189]
I am loading Plotly mesh3d html files into QWebEngine Chromium. When using QApplication (before finding fbs), I passed ```--ignore-gpu-blacklist``` in the command line when launching my app. Otherwise, WebGL is not supported and my 3D graphs do not appear.

Now that I am using ApplicationContext, the initialization of my QApplication is done automatically. Is there any way to add my flag to the initialization of QApplication via the fbs structure?

Mac 10.15.3
PyInstaller 3.4
PyQt 5.14.0
Python 3.7

**Comment by mherrmann** [comment]
You could overwrite `ApplicationContext.app` as described in the [manual](https://build-system.fman.io/manual/#ApplicationContext.app).
