### ISSUE TITLE
ctypes.wintypes module not found

### ISSUE THREAD

**Issue by fredrikaverpil** [mherrmann/fbs#19]
After building my App.exe on Windows using Python 3.6.5, I get this when I run it:

```
Traceback (most recent call last):
...
    import ctypes, ctypes.wintypes
ModuleNotFoundError: No module named 'ctypes.wintypes'
[20024] Failed to execute script main
```

Have you seen anything like this?
I'm just throwing this out there... it could be PyInstaller's fault.

**Comment by mherrmann** [comment]
I have seen this very error. PyInstaller isn't picking up that your app is using the mentioned module. Does it work when you add

```
import ctypes.wintypes
```

somewhere in your app's (main) Python code?

P.S.: I had some [pretty bad experiences](https://fman.io/blog/battling-with-macos/) with PyInstaller (and thus fbs) with Python 3.6.5 on Mac. If you can, I would recommend Python 3.5 instead.

**Comment by fredrikaverpil** [comment]
> Does it work when you add

Aah... yes, that worked. Actually, come to think of it. I've actually had to do this for my postgres binding too (pg8000).

Thank you!

> If you can, I would recommend Python 3.5 instead.

So far it's working fine with Python 3.6. I really wish to use this, with all the async stuff. Fingers crossed then. 🤞

**Comment by mherrmann** [comment]
> Aah... yes, that worked.

Cool :)

> So far it's working fine with Python 3.6. I really wish to use this, with all the async stuff.

Sure :) Just if you do run into problems may be good to know that it could be caused by differences between 3.5 and 3.6 as well.

**Comment by fredrikaverpil** [comment]
> Just if you do run into problems may be good to know ...

Yes, much appreciated for this headsup. :)
