### ISSUE TITLE
OSError: [WinError 126] The specified module could not be found

### ISSUE THREAD

**Issue by datagatoni** [mherrmann/fbs#190]
Hello,

I am a beginner in python and recently discovered fbs, so this question is probably dumb, I apologize in advance.

I used it following the instructions using python 3.6.7 and importing all the modules in the virtual environment as directed. the program run but fbs freeze didn't work. turning the 'Failed to execute script main' error. I run the fbs freeze --debug method and now I am finding this error:

```
Traceback (most recent call last):
  File "lib\site-packages\PyInstaller\loader\pyiboot01_bootstrap.py", line 172, in __init__
  **File "ctypes\__init__.py", line 348, in __init__
OSError: [WinError 126] The specified module could not be found**
During handling of the above exception, another exception occurred:
'''''''''
''''''''''''''
'''''''''''''''''
  File "lib\site-packages\PyInstaller\loader\pyiboot01_bootstrap.py", line 174, in __init__
__main__.PyInstallerImportError: Failed to load dynlib/dll 'C:\\Users\\ALEXIS\\Desktop\\DEVELOP\\target\\Test5\\sklearn\\.libs\\vcomp140.dll'. **Most probably this dynlib/dll was not found when the application was frozen.
[6916] Failed to execute script main**
```

I have tried  some solutions that suggested  adding --path to the folder that contains Qt5Widgets.dll,"Qt5Core.dll"] and "Qt5Gui.dll" without success. I also tried to add these dll files in the json file as Hidden imports but it didn't work as well.

I hope you can point me in the right direction. 

Thanks,

Datagatoni

**Comment by mherrmann** [comment]
Hi,

which versions of PyInstaller and PyQt5 are you using?

Cheers,
Michael

**Comment by datagatoni** [comment]
used pip install fbs PyQt5==5.9.2, as directed.  it seems Pyinstaller is 3.4

**Comment by datagatoni** [comment]
also it might be of significance that when run the fbs startproject no resources  sub-folder was created in the main folder. there were only the "python" and "base" sub-folders.  I put files in the base subfolder and everything worked up to the fbs run step

**Comment by mherrmann** [comment]
I think this is simply a dependency problem. Please ask on PyInstaller's issue tracker about `sklearn` (or google the error message with "PyInstaller" and "sklearn").

**Comment by datagatoni** [comment]
For Anyone interested. I solved the problem by first installing the numpy-1.18.2+mkl-cp36-cp36m-win_amd64.whl version from [link](https://www.lfd.uci.edu/~gohlke/pythonlibs/) and then when I run fbs freeze--debug I was shown that the mkl_avx2.dll were the problems by copying all the mkl_xxx.dll from the environment folder (venv\Lib\site-packages\numpy)  to the target folder where the frozen app is. Voila everything worked fine, the app run with no error.
