### ISSUE TITLE
Create a desktop shortcut on the window

### ISSUE THREAD

**Issue by pengchant** [mherrmann/fbs#191]
Hello, what should I do to configure the package to be able to create desktop shortcuts when installing on Windows?

**Comment by mherrmann** [comment]
Copy [this file](https://github.com/mherrmann/fbs/blob/master/fbs/_defaults/src/installer/windows/Installer.nsi) into `src/installer/windows/Installer.nsi` and modify it so it places a shortcut on the desktop. It should be easy to find out how to do this by googling "NSIS place shortcut on desktop".

**Comment by pengchant** [comment]
Thank you! This does exactly what I need!!

**Comment by mherrmann** [comment]
:-)

**Comment by nicolaevladescu** [comment]
Here's a [link](https://gist.github.com/nicolaevladescu/54dda416cb26051fb4202cd1b5eb9c83) with an example, for a complete solution.
