### ISSUE TITLE
Suggest to have a dll directory to load missing dll automatically when freezing

### ISSUE THREAD

**Issue by ptskyin** [mherrmann/fbs#193]
Hi,
I'm using fbs with **bleak**, a BLE python package. It depends on BleakUWPBridge.dll (on Windows), but the dll is missing from the target/ directory when calling freeze. 

Suggest to have a dll directory, so that when calling freeze, any dll in this directory will be added to target/ automatically.

**Comment by mherrmann** [comment]
Could you put the DLL in `src/main/resources`?

**Comment by ptskyin** [comment]
> Could you put the DLL in `src/main/resources`?

The dll is still not included in the target/ directory, after doing this.

**Comment by mherrmann** [comment]
Sorry. `src/main/resources/base`

**Comment by ptskyin** [comment]
> Sorry. `src/main/resources/base`

Yes, this solves the issue. Great thanks!
