### ISSUE TITLE
Issue only on freezing using CurrencyConverter module

### ISSUE THREAD

**Issue by arnaudsauvaget** [mherrmann/fbs#194]
Hello, 

Using Python 3.6 and PySide2, project needs [CurrencyConverter](https://pypi.org/project/CurrencyConverter/)
`from currency_converter import CurrencyConverter`

fbs run is OK. 
fbs freeze -debug does not shown any ImportError but shows "Failed to execute script main"

Freezing without CurrencyConveryer involved in the code runs perfectly.

After investigation, I've noticed that the created target/my_app folder misses a folder located in lib/site-packages
Adding manually this folder in the target/my_app folder helps the .exe to run.
As explained in the documentation, I tried to add it in the src/main/resources/base/ folder but it does not work (ie: folder is still missing in target/my_app after freeze.

Best regards,
Arnaud
![screen_conv2](https://user-images.githubusercontent.com/24358922/81323448-b20dd800-9095-11ea-81f6-0931ae8b4838.png)

**Comment by mherrmann** [comment]
Please follow these steps: https://build-system.fman.io/manual/#dependencies. If that doesn't help, please file an issue with the PyInstaller library, which fbs uses under the hood.
