### ISSUE TITLE
fbs run and fbs freeze(fbs freeze --debug) all went well, when I try to run the exectuable file it says "failed to execute script xxx"

### ISSUE THREAD

**Issue by loveplay1983** [mherrmann/fbs#195]
* Environment
1. fbs 0.8.4
2. pyinstaller 3.4
3. python 3.6.7
4. pyqt 5.9.2

* Issue
My `fbs run and fbs freeze as well as fbs freeze --debug` looks all good, no error output, but when I try to execute the executable file, it says "fatal error detected, failed to execute script xxx"

Please help me out, many thanks!!!
CODE LINK: https://github.com/loveplay1983/pilot_project/tree/working_on_md5_uuid/5_screen_locker/screen_locker_beta/src/main/python

**Comment by mherrmann** [comment]
Unless you can prove that this is a bug in fbs, I'd ask that you please ask this on StackOverflow instead.
