### ISSUE TITLE
Spaces instead of tabs

### ISSUE THREAD

**Issue by fredrikaverpil** [mherrmann/fbs#2]
I noticed that you're using tabs to indent your code. I personally prefer spaces and use this everywhere. Even [PEP8 recommends spaces](https://www.python.org/dev/peps/pep-0008/#tabs-or-spaces) over tabs.

I believe Python 3 is more picky about mixing spaces and tabs and won't accept such mixing without raising errors (not entirely sure here). Since this is an open source project, perhaps I can persuade you to follow the PEP8 recommendations and use (4) spaces instead of a tab? 😉

**Comment by mherrmann** [comment]
_Sigh_ okay :wink:

I'll change to spaces after your current PRs or else merging might get tricky.

**Comment by mherrmann** [comment]
Converted to spaces in commit ceb2571.

**Comment by fredrikaverpil** [comment]
Thanks for this! :)
