### ISSUE TITLE
Bundling the python interpreter

### ISSUE THREAD

**Issue by fredrikaverpil** [mherrmann/fbs#20]
This may sound weird, but do you think it's possible to bundle the python binary itself (e.g. python.exe on Windows)?

I know how to bundle multiple binaries which stem from python scripts... But the python binary itself?

Any ideas?

**Comment by mherrmann** [comment]
It's easy to "write" your own Python interpreter: https://docs.python.org/3/library/code.html

**Comment by fredrikaverpil** [comment]
Ok, that's a start, at least!
