### ISSUE TITLE
Load program every time the computer starts

### ISSUE THREAD

**Issue by jakob1111** [mherrmann/fbs#200]
I would like to create a (Windows) program that, once it has been installed, starts automatically every time the computer is booted. Is it possible to realize this with fbs?

**Comment by mherrmann** [comment]
It's a bit external to fbs. You can start every program when your computer starts by putting it in Windows' autostart folder.

**Comment by jakob1111** [comment]
Thanks for your prompt reply! Yes, admittedly it's a bit external to fbs. I was just curious if there is a simple way to automatically add  a shortcut to Windows' autostart folder when a program that was created via fbs is installed.

**Comment by mherrmann** [comment]
You can customize https://github.com/mherrmann/fbs/blob/master/fbs/_defaults/src/installer/windows/Installer.nsi. Copy it into your project directory to `src/installer/windows/Installer.nsi` and modify it to add your program to the autostart folder on installation.

**Comment by jakob1111** [comment]
It works! I added the line

`   CreateShortCut "$SMSTARTUP\${app_name}.lnk" "$INSTDIR\${app_name}.exe"`

below the line

` CreateShortCut "$SMPROGRAMS\${app_name}.lnk" "$InstDir\${app_name}.exe"`

and the program now starts automatically when the PC is booted. Thanks a lot!
