### ISSUE TITLE
[Bug] .desktop files generated by FBS do not conform to Desktop Entry specification

### ISSUE THREAD

**Issue by josh-richardson** [mherrmann/fbs#202]
Hi there,

Whilst generating an AppImage from my fbs output, I noticed that `AppName.desktop` files generated by fbs and embedded in .deb installers do not conform to the Desktop Entry specification, meaning that the AppImage creation process fails as the [desktop-file-validate](https://manpages.ubuntu.com/manpages/bionic/man1/desktop-file-validate.1.html) step fails.

The issue here is that in [AppName.desktop](https://github.com/mherrmann/fbs/blob/master/fbs/_defaults/src/installer/linux/usr/share/applications/AppName.desktop#L8), line 8 specifies that the version entry should be set to the version of the application being released. However, according to spec, this should be the version of the desktop entry specification used in the desktop file, which I believe should either be from `1.0` to `1.4` depending on the spec you want to conform to.

This should be a one line fix, but if you'd like me to submit a PR for it I'll be happy to do so.

**Comment by mherrmann** [comment]
Thank you for the info. Yes please do submit a PR. Thanks!

**Comment by mherrmann** [comment]
Thanks! I've released the fix as version 0.8.7 to PyPI now.
