### ISSUE TITLE
Qt Designer in Windows XP 32 bits

### ISSUE THREAD

**Issue by tellts** [mherrmann/fbs#207]
Hello. In the article: "Generating License Keys in 2020" there is a text:
Key length
Historically, license keys had to be entered manually. For instance, when you bought Windows XP, you received a CD-ROM and a printed product key that you had to type in upon installation: 

Please provide the latest version number for this operating system. I have PyQt5-5.5.1-gpl-Py3.4-Qt5.5.1-x32.exe. Please tell me if there is a later version of Qt Designer that will work for me? Python 3.4.3.

**Comment by mherrmann** [comment]
What does the Generating License Keys article have to do with Qt Designer?

**Comment by tellts** [comment]
I thought there was a Windows XP version of Qt Designer. Don't you have one for free use?

**Comment by mherrmann** [comment]
I Don't, sorry.
