### ISSUE TITLE
ways to extract python errors during script initialization from compiled .exe?

### ISSUE THREAD

**Issue by ChrisOKay** [mherrmann/fbs#215]
Upon testing my successfully compiled version on a different machine, I had the weird effect that it worked on my machine, but just showed a "fatal error: failed to execture script main" dialog on the other machine (both more or less similar windows desktops).

I boiled down the issue to a rather trivial one, which was trying to load settings which had been written on my machine, but not on the other machine.

After tumbling down a rabbit hole of "maybe missing or hidden imports", I was only able to track down this issue by commenting out the code down to a minimal working example until figuring out what was causing the failure. The debugging process would have been much more smoothly if the original python error would have been displayed right away, either in the "fatal error" dialog or in the command line afterwards (both of which did not display any indication of an error trace).

Long story, short question: Are there ways to extract such an error during the script initialization of the exe?

**Comment by ChrisOKay** [comment]
I figured out that this non-verbose output is a feature of pyinstaller, not of fbs. Pyinstaller suggests (see [doc](https://pyinstaller.readthedocs.io/en/stable/when-things-go-wrong.html#figuring-out-why-your-gui-application-won-t-start)) to temporarely remove the --windowed option. This lead me to another issue #14, which lead to show_console_window, which lead to the desired verbose output of the error. My Google FU was not on point.

**Comment by mherrmann** [comment]
You can do `fbs freeze --debug` to get the same. Sorry for the late reply; I'm on holidays.

**Comment by ChrisOKay** [comment]
unfortunately, in this particular case everything worked well on my delevopment machine (freeze --debug showed no issues, the converted exe showed no issues).
Only my colleague had issues on his machine with the compiled exe (due to missing self.settings in the application, which were loaded during initialization). Since I did not want to install a full python environment on his machine, I wanted to find a way to display the error directly in the compiled exe. And the way to go was to disable the --windowed option.
Happy holidays!

**Comment by mherrmann** [comment]
I see, okay! For remote debugging, you may also find the [Sentry integration](https://build-system.fman.io/manual/#error-tracking) useful.
