### ISSUE TITLE
Feature Request: Add Support for PyInstaller's `--exclude-module` argument in settings

### ISSUE THREAD

**Issue by mdlockyer** [mherrmann/fbs#217]
As stated in the title, support for excluding modules would be a really helpful addition for fbs. I'm currently working on a project for which a module *must* be excluded for it function properly once frozen with PyInstaller, so I am unable to use fbs without modifications at the moment. I think this could be done exactly how `hidden_imports` is implemented. By adding another key to the `src/build/settings` json files, the user could specify the excluded module(s). This would be a very useful feature that exposes a crucial control point for a lot of PyInstaller builds that would otherwise be excluded (no pun intended) from using fbs. I already have a modified version of fbs with the feature implemented, and the changes are minimal.

I am happy to implement this myself and create a PR if this is something that you feel would be worth adding! 

Thanks for the wonderful tool btw. I've had a great experience overall with fbs.

**Comment by mherrmann** [comment]
Thank you for the kind words. I'm happy to hear that you are finding fbs useful.

What you want can already be achieved with a badly-documented feature: https://github.com/mherrmann/fbs/releases/tag/v0.8.9

Are you using fbs at Gearbox?

**Comment by mdlockyer** [comment]
Thanks! this is super helpful! Totally solved my use case.

I'm just using fbs for some personal projects. I love using it to throw together really fast GUIs for some of my automation scripts.
