### ISSUE TITLE
Hide Console

### ISSUE THREAD

**Issue by seasonalwind** [mherrmann/fbs#218]
Hi, is there any way for users to get rid of console output when freezing our programs, like "-- noconsole" or "-w" options in pyinstaller?

**Comment by mherrmann** [comment]
If you don't supply the `--debug` flag to `fbs freeze` then there shouldn't be a console.

**Comment by seasonalwind** [comment]
> If you don't supply the `--debug` flag to `fbs freeze` then there shouldn't be a console.

thank you so much ...
