### ISSUE TITLE
Modular application

### ISSUE THREAD

**Issue by nodedge** [mherrmann/fbs#220]
Hello Michael, 

Thank you for sharing FBS.

I have a question regarding plugins for modular applications.

Do you know if there is a way to add compiled plugins to a FBS-compiled application?

I tried with [Yapsy](https://pypi.org/project/Yapsy/). I managed to find python plugins located in the folder "plugins" of my installation folder.
However, Yaspsy only finds Python plugins (.py files), and not compiled plugins (.pyc, .whl, .pyd or any compiled extension).

 Do you know if there is a way to use [QPluginLoader](https://doc.qt.io/qt-5/qpluginloader.html) with FBS/PySide2?

Thank you for your insight.
Best regards.

**Comment by mherrmann** [comment]
Hi,

I'm sorry, I don't know. I've never worked with plugins.

**Comment by nodedge** [comment]
Hi, 

Thank you for your reply.

Cheers.
