### ISSUE TITLE
fbs tutorial gave me a rough experience the first time I evaluated fbs

### ISSUE THREAD

**Issue by ralfebert** [mherrmann/fbs#225]
I had a somewhat rough experience the first time I tried fbs while evaluating the solutions to build an macOS app bundle for a Qt python app . I don't need any help/support - I just wanted to let you know that you might be losing potential customers here:

- The hint 'Only Python 3.5 or 3.6 will work' in https://github.com/mherrmann/fbs-tutorial could be way more prominent. I know, it's in bold but I overread it in my quest to quickly find a way to build an app bundle for my first qt app (coming from https://doc.qt.io/qtforpython/deployment.html with the task to check out 4+ different solutions for that task I wasn't super careful here) and straight ran into the `TypeError: an integer is required` issue for Python 3.8:

```
TypeError: an integer is required (got type bytes)
Traceback (most recent call last):
  File "/Users/ralf/Desktop/py2app-tests/venv/bin/fbs", line 33, in <module>
```

  I would not have missed this if it would be the first step under Setup. "1. Install Python version 3.6." And imo it should give some perspective on why fbs is sticking with an old python version and give some outlook on the timetable for migration to newer versions. Maybe, if you want to be helpful, a recommendation on how to install an old python version in parallel with the latest version for potential customers like me who are new to the python ecosystem. I am okay with using an old version thats tried out and tested, but I will also worry 'will I be stuck on some old version forever without a migration path forward' / 'is fbs still maintained'? Dissolving these worries here might help with converting a developer or two into paying customers...

- The official qt documentation has a tutorial about fbs (https://doc.qt.io/qtforpython/deployment-fbs.html) - which doesn't mention this requirement at all. Also, it implies that it works with 'PySide6' (because their example main.py uses pyside6 - I guess somebody did just a search/replace without actually testing it) - but fbs just says 'Couldn't find PyQt5 or PySide2.' when I try this. I don't know what your relationship with the Qt Company is - but wouldn't it be in your common interest to make this tutorial as 'idiot-proof' as possible?

**Comment by ralfebert** [comment]
Tried it with Python 3.6, [How to manage multiple Python versions and virtual environments](https://www.freecodecamp.org/news/manage-multiple-python-versions-and-virtual-environments-venv-pyenv-pyvenv-a29fb00c296f/) was helpful in that regard.

Now stuck on an error 'ERROR: Can not find path ./libshiboken2.abi3.5.15.dylib' / 'Python library not found: Python, libpython3.6.dylib, .Python, libpython3.6m.dylib'.

These look similiar, giving up a this point:
- https://stackoverflow.com/questions/58658902/how-to-solve-fbs-error-can-not-find-path-libshiboken2-abi3-5-13-dylib
- https://github.com/mherrmann/fbs/issues/101

**Comment by ralfebert** [comment]
Steps to set up a new project using fbs:

* Install Python Version 3.6 via pyenv:

```
PYTHON_CONFIGURE_OPTS="--enable-framework" pyenv install 3.6.12
```

* Create a new project:

```
mkdir demo-project && cd demo-project
pyenv local 3.6.12
python3 -m venv venv
source venv/bin/activate
pip install pip --upgrade
pip install pyside2 fbs
fbs startproject
fbs run
fbs freeze
```

**Comment by mherrmann** [comment]
Sorry you had a bad experience. Thank you for sharing your solution here. I'll be happy to accept a PR that prints a warning on fbs command if the user is not using Python 3.5 or 3.6.

**Comment by AllenDang** [comment]
@mherrmann How about the doesn't support PySide6 issue? I followed the official document and fbs only support pyqt and pyside2.

**Comment by mherrmann** [comment]
I am open to suggestions.

**Comment by AllenDang** [comment]
@mherrmann Any plan to support PySide6?

**Comment by mherrmann** [comment]
Not from my side. I'm too busy with other projects that pay more than my bills.

**Comment by mherrmann** [comment]
I just released a new version of [fbs Pro](https://build-system.fman.io/pro) that adds support for PySide6 and PyQt6. Regarding the original topic of this thread, this too has been improved in the open source version of fbs to give a meaningful error message.
