### ISSUE TITLE
PySide6 Compatibility

### ISSUE THREAD

**Issue by nick-zanobini** [mherrmann/fbs#226]
Has there been any thought/progress on updating to support the future of Qt for Python with [PySide6](https://doc.qt.io/qtforpython/quickstart.html)?

**Comment by mherrmann** [comment]
Not at the moment; Pull Requests are always accepted :-)

**Comment by cuicaihao** [comment]
Any ideal about the introduction on the Qt website [Qt for Python & fbs](https://doc.qt.io/qtforpython/deployment-fbs.html?highlight=fbs), it is kind of misleading!

Their demo code is like the following:
```python
from fbs_runtime.application_context import ApplicationContext
from PySide6.QtWidgets import QMainWindow
import sys
if __name__ == '__main__':
    appctxt = ApplicationContext()       # 1. Instantiate ApplicationContext
    window = QMainWindow()
    window.resize(250, 150)
    window.show()
    exit_code = appctxt.app.exec_()      # 2. Invoke appctxt.app.exec_()
    sys.exit(exit_code)
```
As you can see, it called PySide6. But I tried the code on macOS 11.2.1 with conda environment (pyQt python3.7) , it does not work. 

Do you think Qt Team has already solved the issue?

```
(pyQt) ➜  QtFBS fbs run
Traceback (most recent call last):
  File "/Users/cc/Documents/Developer/QT/QtFBS/src/main/python/main.py", line 1, in <module>
    from fbs_runtime.application_context import ApplicationContext
ImportError: cannot import name 'ApplicationContext' from 'fbs_runtime.application_context' (/Users/cc/opt/miniconda3/envs/pyQt/lib/python3.7/site-packages/fbs_runtime/application_context/__init__.py)
(pyQt) ➜  QtFBS 
```

The original `fbs` tutorial works fine on Mac, but it shows a lot when calling `fbs freeze` or `fbs installer`, I think this is the os issue with the `pyinstaller`.

```bash
...
2652 ERROR: Can not find path /usr/lib/libSystem.B.dylib (needed by /Users/cc/opt/miniconda3/envs/pyQt/lib/libtinfo.6.dylib)
2656 ERROR: Can not find path /usr/lib/libSystem.B.dylib (needed by /Users/cc/opt/miniconda3/envs/pyQt/bin/python3.7)
2922 ERROR: Can not find path /usr/lib/libSystem.B.dylib (needed by /Users/cc/opt/miniconda3/envs/pyQt/bin/python3.7)
...
```

**Comment by mherrmann** [comment]
I just released a new version of [fbs Pro](https://build-system.fman.io/pro) that adds support for PySide6 and PyQt6.
