### ISSUE TITLE
Open source licensing

### ISSUE THREAD

**Issue by mighty-pirate** [mherrmann/fbs#23]
According to the site, projects can freely use fbs providing the project in question is licensed using GNU general public license. Just so I don't disobey the terms of the license; does this mean only the project using fbs, or any other projects that it would integrate with?

I was planning on using Unlicense which is a permissive license very similar to WTFGPL.

**Comment by mherrmann** [comment]
If you use Unlicense for your project then it's not licensed under the GPL. So if I understood your question correctly then no, you can't use Unlicense for your project.

**Comment by mighty-pirate** [comment]
Ok, I understand that, but I was wondering if all projects in the system need to use GPL, or whether its just the project that makes use of the fbs code. In this case the front end project.

**Comment by mherrmann** [comment]
I see. Only the code base that uses fbs needs to be GPL. So it depends on how separate the front end is from the other parts of your system. If no other parts use the frontend's code or include it as a library, then it should suffice to make only the frontend code GPL.

**Comment by mighty-pirate** [comment]
Thats great, thanks a lot.
