### ISSUE TITLE
 form design not respect  the  size 

### ISSUE THREAD

**Issue by faustf** [mherrmann/fbs#235]
![de](https://user-images.githubusercontent.com/37455401/122672447-d2cabb80-d1cb-11eb-9d1e-310685f5f94d.jpg)

hi at all
the form design not respect  the  size if  gui when run it  look the attach file 
bye

**Comment by mherrmann** [comment]
This is a question about Qt Designer, not fbs, so I'm closing this issue. I'd recommend you ask the question on StackOverflow.
