### ISSUE TITLE
How to work with subdirectories?

### ISSUE THREAD

**Issue by sho-87** [mherrmann/fbs#237]
This is more of a basic usage question, rather than a bug...

I have an app structured like so:

```
src/main/python:

├── views
│   └── main.ui
├── controllers
│   └── settings.py
├── __init__.py
└── main.py
```
In `main.py` (and other python files), how do I reference files that are in subdirectories? For example, I'm trying to load the ui file that is inside the `views` directory:

```
class MainWindow(QMainWindow):
    def __init__(self, ctx):
        super(MainWindow, self).__init__()
        self.ctx = ctx

        uic.loadUi('views/main.ui', self)
        self.show()
```
This works in my IDE, but `fbs run` will give me `FileNotFoundError: [Errno 2] No such file or directory: 'views/main.ui'`, because I guess its looking in a different root directory

What are the best practices for working with subdirectories like this?

I know I can just put everything inside the `resources` folder, but some things like the controllers (which are python classes) don't feel like they should be packaged/distributed with the application itself

---

 * Your operating system(s): Windows 10
 * Your Python version: 3.6
 * Your fbs version: 0.9.5
 * Your PyInstaller version: 3.4
 * Your PyQt5 version: 5.15.4

**Comment by mherrmann** [comment]
The `.ui` file should go into `resources/`. You can get its path via ApplicationContext.get_resource(...). Python code gets automatically included if you `import` it from your main script or if you add it to `hidden_imports`.
