### ISSUE TITLE
Installer launches application with admin permissions

### ISSUE THREAD

**Issue by fredrikaverpil** [mherrmann/fbs#24]
I suspect that the last step of the installer (which offers the ability to launch the frozen application) is using the same environment as the installer itself. In my case, this means that administrative permissions are enabled.

When my application runs, it creates files on disk. When the application recognizes very old and unused such files, it attempts to delete them. This, however, fails, as some of these files were created from an application instance which got launched from the installer and now requires admin permissions for deletion. This is on Windows.

I recently found out that you can force an application to run as "non-administrative" using `runas` on Windows:

    runas /trustlevel:0x20000 "SpotifyFullSetup.exe /silent"

In the `Installer.nsi` file, I'm going to attempt to do this for Windows. But I don't have a solution for macOS or Linux, but I'm not sure whether the issue is being hit on those operating systems at all.

This is what the launch command of the `Installer.nsi` looks like:

```
Function LaunchLink
  ExecShell "" "$SMPROGRAMS\%{app_name}.lnk"
FunctionEnd
```

EDIT: I realized this doesn't belong in the fbs project, but instead in the fbs-tutorial one.

**Comment by mherrmann** [comment]
Hey Fredrik! Nice to hear from you again (and that - hopefully - you're still finding fbs useful).

You're right that the [line that causes this](https://github.com/mherrmann/fbs-tutorial/blob/7a7f39f4e6125f8222fdb0322e033075a396a6c4/src/main/Installer.nsi#L99) is actually in fbs-tutorial. Still, I think it's fair to continue the discussion here.

After a little research, I'm not sure yet how to fix this. [Here](http://forums.winamp.com/showthread.php?t=294617) is someone who had the same problem. He did come up with a solution, but apparently (judging from the thread) it's somewhat hacky. Maybe we can just do `ExecShell "" "runas..."`?

**Comment by fredrikaverpil** [comment]
> Hey Fredrik! Nice to hear from you again (and that - hopefully - you're still finding fbs useful).

License purchased! :wink: :heart:

>  Maybe we can just do `ExecShell "" "runas..."`?

This would've been a quick fix, but after having spent an hour to try to figure out the escaping and quotation without success, I finally opted for this workaround instead...

Download [ShellExecAsUser.dll](http://nsis.sourceforge.net/ShellExecAsUser_plug-in) and place it next to the `Installer.nsi` file. Then modify the LaunchLink section as follows:

```
Function LaunchLink
  ; ExecShell "" "$SMPROGRAMS\%{app_name}.lnk"
  !addplugindir "..\..\src\main"
  ShellExecAsUser::ShellExecAsUser "open" "$SMPROGRAMS\%{app_name}.lnk"
FunctionEnd
```

The DLL can also be placed in `C:\Program Files (x86)\NSIS\Plugins\[architecture]` but then you wouldn't be able to bundle it with the git repo.

**Comment by mherrmann** [comment]
> License purchased! :wink: :heart:

Already by email, but again: Thank you! :slightly_smiling_face: 

I incorporated your fix in [fbs-tutorial#ce058](https://github.com/mherrmann/fbs-tutorial/commit/ce508f9655278d1ff6267f8bb394bc7a6a116b7e) :-)
