### ISSUE TITLE
Writing to text does not default to UTF-8

### ISSUE THREAD

**Issue by BoukeVahl** [mherrmann/fbs#240]
From my limited knowledge, saving text defaults to UTF 8
However, on my (Catalina) system, this does not work when freezed.
Running the freezed app from the command line does work as expected for some reason.
(I was trying to write Japanese to file.)

Forcing the text encoding to UTF 8 solves it, so it's not really a problem.

**Comment by mherrmann** [comment]
Hi Bouke, I'm sorry but this feels more like a Python question than one that is specific to fbs to me? In all cases, forcing the encoding to UTF-8 sounds like a good solution to me.

**Comment by BoukeVahl** [comment]
Hi Michael,
Not sure, writing Japanese does work inside Pycharm without forcing UTF-8, but does not after freezing, so I thought it might have to do with FBS.
But is was merely a warning for others, it's really not an issue.
(Thinking of it, just a print() of Japanese text causes crashes.)

Thx,
Bouke

**Comment by mherrmann** [comment]
I see. Okay! Then I'll mark this issue as closed. It will still be here for others to find.
