### ISSUE TITLE
QML files are not included in the build

### ISSUE THREAD

**Issue by ashwin31** [mherrmann/fbs#241]
Hi, do you have any suggestions or documentation to work with pyside2 and qml.

 * my operating system(s) ubuntu 20.04
 * my Python version is 3.8.10 I read above instructions and this is not about python version.
 * my fbs version 1.0.3
 * my PyInstaller version 4.4
 * my PySide2 version 5.15.2

Output after running the build
```
./target/PieTrack/PieTrack 
QQmlApplicationEngine failed to load component
file:///home/ashwin/git-prjs/pietrack/desktop_client/target/PieTrack/qml/main.qml: No such file or directory
```

A (minimal!) script that reproduces the problem
```
# Get Context
    engine.rootContext().setContextProperty("backend", main)

    # Load QML File
    engine.load(os.path.join(os.path.dirname(__file__), "qml/main.qml"))
```

This is not fbs or pyinstaller bug. I don't know how to embed QML files and link them any other way. Bur, documentatio to achieve this will help me and others who want to develop apps with pyside2 and QML.

**Comment by mherrmann** [comment]
Hi, I would include them as resource files. This is described in https://build-system.fman.io/manual/#resource-files.

**Comment by ashwin31** [comment]
@mherrmann you saved me. I was looking for this for 4 days and asked many people. This is easy and worked like a magic. Thank you very much.

**Comment by mherrmann** [comment]
Happy it helped :blush:
