### ISSUE TITLE
I can't afford buying fbs. Can I compile it myself from here?

### ISSUE THREAD

**Issue by dragonDScript** [mherrmann/fbs#244]
I can't afford buying fbs. Can I compile it myself from here? It's an open source app, and... *Quid pro quo.*

**Comment by mherrmann** [comment]
You can use the free version of fbs (the one given here) with Python 3.5 and 3.6.

**Comment by dragonDScript** [comment]
> You can use the free version of fbs (the one given here) with Python 3.5 and 3.6.

Okay! And what are the differences between free and paid?

**Comment by mherrmann** [comment]
You're saying you can't pay and now you want a sales conversation ;) It's all in the [manual](https://build-system.fman.io/manual/).

**Comment by dragonDScript** [comment]
> You're saying you can't pay and now you want a sales conversation ;) It's all in the [manual](https://build-system.fman.io/manual/).

Thanks, just curious.
