### ISSUE TITLE
How to get the license key value from inside a widget?

### ISSUE THREAD

**Issue by brian316** [mherrmann/fbs#248]
I read the licensing article but it only shows using `licensing.unpack_license_key` function on the ApplicationContext class.
I'm basically trying to get the license key inside a widget and verify using the unpack method. How can I do this?
Im trying to get a call to that function inside my MainWindow() class.

> I would basically like to use this unpack feature anywhere in the source code if possible

example:
```python
class MyAppContext(ApplicationContext):
    @cached_property
    def window(self):
        return MainWindow()

    def run(self):
        self.window.show()
        return self.app.exec()

if __name__ == '__main__':
    appctxt = MyAppContext()
    appctxt.run()
```
 * Windows 10
 * Python3.9
 * fbs version: PRO  Version`1.0.5`
 * pyinstaller==4.5.1
 * PySide6==6.1.3

**Comment by mherrmann** [comment]
I released fbs Pro 1.0.6 to make it easier for you. You can install it by changing "1.0.5" to "1.0.6" in the `pip` link in the email you received when you purchased Pro. The updated instructions are at https://build-system.fman.io/manual/#license-keys. In short, you are no longer required to use `ApplicationContext.licensing` but can instead simply use an fbs function anywhere in your code.

**Comment by brian316** [comment]
Thank you! This works now :)

```python
def get_license_key(key_path: str):
    """Returns key contents if valid None otherwise"""
    try:
        with open(key_path) as f:
            key_contents = f.read()
        return unpack_license_key(key_contents, PUBLIC_SETTINGS['licensing_pubkey'])
    except BaseException:
        return None
```

I will also test if i can use the `ApplicationContext.get_resource(*rel_path)`
This was well worth the money I'm still figuring out bits and pieces but it's much less complicated than other installer/bundlers
Thank you.

**Comment by mherrmann** [comment]
Happy to hear you like it :)
