### ISSUE TITLE
thanks

### ISSUE THREAD

**Issue by rudolfolah** [mherrmann/fbs#25]
**Just wanted to say thanks** for putting together [the PyQt5 tutorial](https://build-system.fman.io/pyqt5-tutorial), I've been working on a video course that makes use of it (along with Tornado and RxPy) and it's nice to someone else working on promoting and educating developers about the Qt5 coding with Python.

The installer part is very interesting as PyQt5 itself also has an installer/deployer called [pyqtdeploy](https://www.riverbankcomputing.com/software/pyqtdeploy/intro), it would be neat in the future to see a comparison between fbs and pyqtdeploy.

**Comment by mherrmann** [comment]
My pleasure - thank you for the kind message :-) When I tried pyqtdeploy two years ago, it was very difficult to use and kept crashing. That's why I gave up on it.

**Comment by rudolfolah** [comment]
I didn't know that about pyqtdeploy, I'll have to give fbs a try!
