### ISSUE TITLE
Pyside2 support?

### ISSUE THREAD

**Issue by kefniark** [mherrmann/fbs#26]
Hello there,

I'm quite interested by this project but I would like to know if there is any plan to support "Qt for python" in the future or if this tool will remain PyQt specific. 

Thanks

**Comment by mherrmann** [comment]
Hi Kevin,

it [supports](https://github.com/mherrmann/fbs/blob/67d124137bbc8a96fccf78b534e305ec8c100c30/fbs_runtime/application_context.py#L8-L15) Qt for Python already. I've updated the README to reflect this. The [home page](https://build-system.fman.io/) already mentions this.

Cheers,
Michael
