### ISSUE TITLE
Get ApplicationContext after creating

### ISSUE THREAD

**Issue by gentlegiantJGC** [mherrmann/fbs#261]
PySide2 has QApplication.instance() to get the previously created instance of the app or create it. I can't see anything like this that exsits for fbs's ApplicationContext.

I would like to use ApplicationContext.get_resource to get resources without having to manually store the object as is suggested in: https://stackoverflow.com/questions/60040208/access-fbs-resource-files-in-non-gui-code

Would you consider adding a mecanism for fbs to store the object so it can be accessed again like PySide2 does for the app?

**Comment by mherrmann** [comment]
fbs has such a function: https://github.com/mherrmann/fbs/blob/aa5214e83e4fefb23187fca05a5764fa3211acc4/fbs_runtime/application_context/__init__.py#L139

**Comment by gentlegiantJGC** [comment]
Thank you. I can't see any mention of that in the docs.

From my understanding it is called like this which is a little clunky.
```py
get_application_context(PySide2.ApplicationContext)
```

Would you consider adding a classmethod on the ApplicationContext class that simplifies that behaviour?

Something like this
```py
@classmethod
def instance(cls):
    return get_application_context(cls)
```

That way you could just do
```py
PySide2.ApplicationContext.instance()
```

This may be ambiguous if you called the instance method from different ApplicationContext classes because the returned instance would not be an instance of that class but the same issue exists with get_application_context.

**Comment by mherrmann** [comment]
Yes, not all public functions are listed in the docs. The docs do [say](https://build-system.fman.io/manual/#others):

> The most important parts of fbs's API are described above. But there are more functions which you can use. They are documented in (extensive) comments in fbs's source code. You can consider everything whose name doesn't start with an underscore _ a part of the public API.

Your code is nicer than `get_application_context(...)`. However, now that `get_application_context(...)` already exists, I'd rather not add a new method that does essentially the same. From `import this` in Python:

> There should be one-- and preferably only one --obvious way to do it.

**Comment by mherrmann** [comment]
(So my motivation for refusing your request is that 1) there's already a way to do it and I don't want there to be two ways. Also 2), I don't think it would be very nice if a class method touches global state outside the class. I have fewer such qualms about a module-level function. But again - your code is nice and probably I'd write it differently if I were writing fbs from scratch.)

**Comment by gentlegiantJGC** [comment]
I assumed that upon constructing the ApplicationContext for the first time the global state would get modified but that doesn't look to be the case. It looks like the global state needs to be manually set. The only thing I can see that uses it is get_application_context

As an alternative suggestion could get_application_context be modified so that it could be called with no inputs?
Something like this
```py
from typing import Optional

def get_application_context(
    DevelopmentAppCtxtCls: Optional[_ApplicationContext]=None,
    FrozenAppCtxtCls: Optional[_ApplicationContext]=None
):
    if _state.APPLICATION_CONTEXT is None:
        if FrozenAppCtxtCls is None:
            FrozenAppCtxtCls = DevelopmentAppCtxtCls
        CtxtCls = FrozenAppCtxtCls if is_frozen() else DevelopmentAppCtxtCls
        if CtxtCls is None:
            raise TypeError("DevelopmentAppCtxtCls must be defined in the first call to get_application_context")
        _state.APPLICATION_CONTEXT = CtxtCls()
            
    return _state.APPLICATION_CONTEXT
```

That way on the first call you would need to do 
```py
get_application_context(PySide2.ApplicationContext)
```

but subsequent calls the inputs are ignored meaning you can just do
```py
get_application_context()
```

**Comment by mherrmann** [comment]
Sorry, you wrote:

> I assumed that upon constructing the ApplicationContext for the first time the global state would get modified but that doesn't look to be the case

But the code says:

     _state.APPLICATION_CONTEXT = ...

So I would say it's modifying the global state?

**Comment by gentlegiantJGC** [comment]
Sorry if that was a little ambiguous. I was referring to when third party code directly calls the `ApplicationContext.__init__` method `ApplicationContext()` instead of get_application_context.

In that case it constructs the context but `_state.APPLICATION_CONTEXT` is not changed. It is only changed as far as I can see when calling get_application_context.

I was just saying that I understand your reasoning for not wanting to call get_application_context from the class.

**Comment by mherrmann** [comment]
I see. Regarding your suggestion:

> could get_application_context be modified so that it could be called with no inputs?

In this case, your code would have to know when to call it with inputs and when to call it without. Then maybe some import order changes and the calls that were previously fine without arguments suddenly break. In my opinion, it's preferable to define a function in your own code `get_my_application_context` that calls `get_application_context` with your `DevelopmentAppCtxtCls`. Then you can always call `get_my_application_context`. Also, it only takes 2 lines for you to define `get_my_application_context`. So adding the functionality you propose to fbs does not pay off, in my opinion.

**Comment by gentlegiantJGC** [comment]
Okay. Thanks for considering the suggestion.
