### ISSUE TITLE
Cross compiling from x86 to ARM

### ISSUE THREAD

**Issue by leopck** [mherrmann/fbs#267]
I'm currently using fbs to create GUI on x86 host but seeing as many people are also using Mac which is ARM based and possibly more in the future, is it possible to cross compile from x86 to ARM? Some ARM hardwares such as embedded systems does not come with the required libraries to cross compile. Is this something that is being looked at yet?

**Comment by mherrmann** [comment]
Please see https://build-system.fman.io/manual/#releasing-multiple, where it says:

> The caveat is that fbs commands only ever target the current platform. That is, you for instance cannot create a Mac installer when running fbs on Windows. The solution to this is to use virtual machines to invoke fbs on different platforms.

In other words, fbs does not support cross-compilation.

**Comment by leopck** [comment]
@mherrmann thanks for the clarification. Makes sense for different operating system as in the example you gave from Mac to Windows, I just thought that this wouldn't be an issue for Linux based system since both my current device and my embedded device are both Linux just compiler is different.
