### ISSUE TITLE
Does it support the dependencies (Tensorflow,...)

### ISSUE THREAD

**Issue by RealTourani** [mherrmann/fbs#275]
Hi,
I just want to know if we purchase pro version , Does it support the dependencies (Tensorflow,...) or not?
if the answer is yes , Is Hobbyist plan is ok?
Thanks.

**Comment by mherrmann** [comment]
Hi, fbs uses PyInstaller to manage dependencies. So your question boils down to whether PyInstaller supports them. Hobbyist is OK only if you are the only developer on the team, so you need the Startup or Enterprise edition. The good thing about those is that they come with a money back guarantee. So if for some reason it doesn't work out with the dependencies, then to can get your money back.
