### ISSUE TITLE
Installer for fbs ?

### ISSUE THREAD

**Issue by jedie** [mherrmann/fbs#28]
I'm new here and looked at https://github.com/mherrmann/fbs-tutorial

Spontaneously I thought: Why isn't there also a finished installer that sets up the fbs virtualenv for "easier" start the tutorial ?

**Comment by mherrmann** [comment]
I'm not sure whether you mean with or without installing Python. Either way, it's beyond fbs's scope. It doesn't want to be its own Python distribution. It's a library, nothing more. Finally, the commands to set up the virtualenv are so easy and well-supported by Python that there is in my eyes very little argument to justify the energy required for automating them.

So, thanks for the idea. I appreciate any feedback. But I don't think it makes sense for fbs at this point.

**Comment by jedie** [comment]
I didn't mean to install Python ;)

The installer can check if python is available and inform the user to install Python if not.
And it just creates the virtualenv...

It's more a "DEMO" App that will create a virtualenv to start with fbs...

**Comment by mherrmann** [comment]
I stick by my above points :-) If you or someone else wants to implement this, feel free. I consider it outside of fbs's scope.
