### ISSUE TITLE
Pro -- Updates beyond 1 year?

### ISSUE THREAD

**Issue by apastel** [mherrmann/fbs#280]
Been using the free version for a while and thinking about getting Pro. I'm curious about how updates work and didn't find the answer in the FAQ.

Since it's just me working on my project, the single "Hobbyist" license appeals to me.
It's clear to me that I would only get to download it one time (keeping a local copy so that I can re-install when wiping my venv or getting a new computer for example). So I would never get to use future Pro features/fixes which is a bummer but understandable for the price.

However even if I bought the Startup or Enterprise version, I would only get "1 year of updates." Does that mean after 1 year, I would no longer be able to download `fbs` at all? Or I would only be able to download whatever the last version that was released after the 1 year ended? What if I really wanted some new feature/bugfix in a new release after that? Would I have to pay for Startup or Enterprise again?

Thanks for the great project.

**Comment by mherrmann** [comment]
Hi! You'd still be able to download fbs after one year, just not newer versions. If you want new versions again, you will have to pay again to get access. I.e. yes, you'd have to buy Pro again.

**Comment by apastel** [comment]
Ok, thank you.
