### ISSUE TITLE
FBS with Pyqt6

### ISSUE THREAD

**Issue by proftc** [mherrmann/fbs#290]
I'm trying to use FBS on my Mac M2 which requires PyQt5. I have installed Python 3.9.6 and set up a virtual environment. However I see that PyQt5 is not supported and I have tried many of the suggested solutions but - I get all sorts of errors when I try to install it- so I am now trying fbs pro which supports  PyQt6 but now the test program gives an error?
(nmr396) terry@M2 testFBS % fbs run
Traceback (most recent call last):
  File "/Users/terry/Documents/Python/testFBS/src/main/python/main.py", line 11, in <module>
    exit_code = appctxt.app.exec_()      # 2. Invoke appctxt.app.exec_()
AttributeError: 'QApplication' object has no attribute 'exec_'
I'm obvious missed something?
Thanks for any suggestions

**Comment by mherrmann** [comment]
In PyQt6, I think it's called `exec`, not `exec_`.

**Comment by proftc** [comment]
Brilliant Thanks

**Comment by proftc** [comment]
That worked fine but I now get these errors? when I try to freeze. Do I need to run everything under Rosetta?
nmr396) terry@M2 testFBS % fbs freeze 
Could not find any of the following files:

 * Python3
 * libpython3.9m.dylib
 * Python
 * .Python
 * libpython3.9.dylib
 
Thanks again

**Comment by mherrmann** [comment]
Let's continue this discussion in #291 please.
