### ISSUE TITLE
QTabwidget Tab text area is white when selected, nothing can be seen 

### ISSUE THREAD

**Issue by XavierPixel** [mherrmann/fbs#297]
This is my first time to use QT designer to design GUI for my application.
I don't know why Tab text area is white when selected, nothing can be seen, see the picture below.

<img width="477" alt="图片" src="https://user-images.githubusercontent.com/129482867/232363839-f7532be8-e9c3-4014-a34c-284a691162e7.png">

I run  QT designer on Mac pro <M1 chip>. Is this the matter?

**Comment by Kastakin** [comment]
How is this related to `fbs`?

**Comment by mherrmann** [comment]
It isn't.

**Comment by XavierPixel** [comment]
I download QT designer from https://build-system.fman.io/qt-designer-download. And i see github links,
i think may be i can get some help here. Actually i don't kow what's fbs,
