### ISSUE TITLE
Installed Executable Not Running

### ISSUE THREAD

**Issue by jayddg75** [mherrmann/fbs#303]
Hey, running into a weird problem.  The freeze output works just fine.  I sign the executable and it runs just fine via double click.  I create the installer with your default NSIS script just adding a license page and install the program via the installer to my computer; the installer is signed as well.  It all installs no problems.

I go to run the executable in program files (x86) and it wont run on double click.  I either have to give it admin permissions or run it via powershell or cmd line.  Can you help me with this, not sure if I have something set wrong or it is a Windows thing.  When I run on double click, nothing happens; doesn't show up in task manager.

Operating System:  Windows 11 Home 
Python: 3.12
fbs: pro 1.2.1
PyInstaller: 6.8.0
PySide: 6.7.0

Regards,

Jason

**Comment by mherrmann** [comment]
Hi! Which [edition of Pro](https://build-system.fman.io/pro) do you have? Hobbyist, Startup or Enterprise?

**Comment by jayddg75** [comment]
Thanks @mherrmann .  I found the issue and it has nothing to do with fbs.  I was putting writable files into C:\Program Files (x86) instead of C:\Program Data (for all users to write to).

I am using the hobbyist version.  Love fbs, by the way, it saved me a lot of time and headache.  I come from more of a data background vs the application side of things.  This made things much easier for me and filled in a lot of the pieces I needed.

**Comment by jayddg75** [comment]
Closing this.  All good
