### ISSUE TITLE
Installer for Linux

### ISSUE THREAD

**Issue by timhoeppner** [mherrmann/fbs#35]
The website claims packaging for Linux is supported but I get "Unsupported OS" when trying to package on Ubuntu.

**Comment by mherrmann** [comment]
Yes, I'm just working on implementing packaging on Linux. Here, the [README](https://github.com/mherrmann/fbs#current-status) does say

> Installers can be created for Windows and Mac. The next steps are to let you create an installer for Ubuntu (Linux)

Sorry for the confusion. I'm hoping to offer packaging on (Ubuntu) Linux in the next week or two.

**Comment by timhoeppner** [comment]
Gotcha, thanks for the reply. I was thinking maybe it got removed for one reason or another since in your fman demonstration video you had it building and packaging on all three platforms.

All the best, thanks again.

**Comment by mherrmann** [comment]
Creating Linux installers is now possible (`.deb` on Ubuntu, `.rpm` on Fedora, `.pkg.tar.xz` on Arch).
