### ISSUE TITLE
Version number in frozen Mac app?

### ISSUE THREAD

**Issue by bastula** [mherrmann/fbs#36]
Great project you have going here! 🎉

Just wondering if versioning is working correctly? I saw #34 and was expecting a version number to show up in the frozen Mac app. However, it just passes the string in the Info.plist (which are just the placeholders).

Once I added a `version` key to `base.json` it worked correctly. Should that be in the default project template? I'm sure other users may run into this issue and I didn't see it documented in the manual.

**Comment by mherrmann** [comment]
You're right, thanks. I fixed this in version 0.2.0 now :-)
