### ISSUE TITLE
Missing dll-s after freezing

### ISSUE THREAD

**Issue by ave-satan** [mherrmann/fbs#38]
Hi,

I've been using fbs to build .exe of my app for windows, and it's all been great so far!
I'm wrinting it using PyQt5, numpy, Pillow and a thing called pypylon (the rest are pure python libs).
While other packages are no issue it all, [pypylon](https://github.com/basler/pypylon) is giving me some serious headache. 
- It has no pypi package, so one must download a wheel and install manually. 
- It requres official SDK to be installed in the system

And the bunch of dll's it comes with never go into the `target/app` when I'm doing `python -m fbs freeze`
I managed to get it working by manually copying the all dll-s from `site-packages/pypylon` into my `target/app`, but would like to get some no-brainer automation here :)

After doing some investigation on my own it looks like `fbs` has no capability of including such dll-s into the build manually. They also suggest messing with pyinstaller and I thought trying something like `pyinstaller --paths` or `pyinstaller --add-data` to see if it helps, but honesltly going down that level is not a thing I would like doing, yet I still have to discover a proper way to do so.

There was also an issue with hidden import with that library, but it works fine after adding this line into `main.py` (just adding this in case you want play with it yourself)
```python
from pypylon import _pylon, _genicam
```

**Comment by mherrmann** [comment]
Hi,

I'm happy to hear you're finding fbs useful!

I'll tell you what I would do: I'd write a [custom build script](https://build-system.fman.io/manual/#custom-commands) that overwrites the `freeze` command and copies the .dlls. Something like the following (untested):

    from fbs import path
    from fbs.cmdline import command
    from glob import glob
    from os.path import dirname, join
    from shutil import copy
    
    import fbs.builtin_commands
    import fbs.cmdline
    
    @command
    def freeze(debug=False):
        fbs.builtin_commands.freeze(debug)
        import pypylon
        for dll in glob(join(dirname(pypylon.__file__), '*.dll')):
            copy(dll, path('${freeze_dir}'))
    
    if __name__ == '__main__':
        project_dir = dirname(__file__)
        fbs.cmdline.main(project_dir)

You'd then invoke `python build.py run/freeze/...` instead of `python -m fbs ...`.

Hope this helps.

Cheers,
Michael

**Comment by ave-satan** [comment]
Thanks!

Looks promising, I'll definitely try it and will dig more into custom commands.

On a side note, do you think adding support for something like this in json configs would be a way to go?

**Comment by mherrmann** [comment]
Happy to help :-)

Not for `.dlls` as in this case, but I've been pondering on whether to add a `hidden_imports` settings in `base.json` so you don't have to do `from pypylon import _pylon, _genicam` in your Python code. What do you think of this idea?

**Comment by ave-satan** [comment]
Sounds good.

**Comment by ave-satan** [comment]
Sounds good.

**Comment by ave-satan** [comment]
Sound good.

**Comment by mherrmann** [comment]
There is now a `hidden_imports` settings. Its explained under [Dependencies](https://build-system.fman.io/manual/#dependencies) in the Manual.
