### ISSUE TITLE
Showcase: working fbs built Windows installer

### ISSUE THREAD

**Issue by craigmac** [mherrmann/fbs#42]
If you are planning to have a showcase of apps/examples built with fbs, I'd like to add an open-source application I'm working on called openroll. It was built with Python, PyQt5 and fbs of course! Hope if can help anyone looking for setup/code examples when working with fbs. There is an official installer for Windows currently built using NSIS. Repository is found at saltycraig/openroll.

**Comment by mherrmann** [comment]
Hey Craig!

That's a very cool idea actually. I may wait until we have a few more examples before putting up a page. But do you have any screenshots?

Thanks for sharing :-)
m

**Comment by saltycraig** [comment]
![screenshot-1 0](https://user-images.githubusercontent.com/7416158/48208574-1d5fd800-e341-11e8-9c16-03ebebad3cea.PNG)

I'll add it to the project page as well, thanks!

**Comment by deven96** [comment]
I would also like to add my application to the example as it was bootstrapped with the fman build system

**Comment by mherrmann** [comment]
And what is "your application"?

**Comment by deven96** [comment]
A simple PyQt application for sniffing wifi and bluetooth devices.
![output](https://user-images.githubusercontent.com/23453888/58956985-98825300-8797-11e9-8414-650cd9562ae2.gif)
