### ISSUE TITLE
I noticed a restructure of src/...

### ISSUE THREAD

**Issue by fredrikaverpil** [mherrmann/fbs#43]
Hi @mherrmann,

I noticed that after an update of fbs to the current v0.3.9, my NSIS changes were lost and the installer got built using the defaults. This seems to happen because the `Installer.nsi` is now expected to be found in`src/installer/windows` (by judging from the contents of `windows.json` in this repo). I used to store this in `src/main/NSIS/Installer.nsi`. So I moved my Installer.nsi to `src/installer/windows/Installer.nsi` instead. But now I got an error instead, where `fbs.builtin_commands.installer()` does not find the Installer.nsi file at all:

    subprocess.CalledProcessError: Command '['makensis', 'Installer.nsi']' returned non-zero exit status 1.

I previously did not use a `windows.json` at all, but now I tried placing one in the `src/build/settings/windows.json` in order to tell fbs where to find Installer.nsi. The contents is the same as the one in this repo:

```json
{
    "installer": "${app_name}Setup.exe",
    "resources_to_filter": [
        "src/installer/windows/Installer.nsi"
    ]
}
```

 Still getting the same error as before though, where the Installer.nsi is not found and I cannot make the installer.

I got curious and wanted to check if anything had also changed in `src/build/settings/base.json`. I can see that it differs quite a lot from my own base.json and this got me wondering... what happened to the json keys `app_name`, `main_module` and `author`?
Are these keys no longer used and if so, where do I specify the entry point of `main_module` for example?
If I remove the `main_module` key/value from base.json, `fbs -m fbs run` will no longer work.

Lots of confusing changes here. Did I miss some kind of memo? 😉

**Comment by mherrmann** [comment]
Hey Fredrik,

yes, I did change the directory structure. I still do this to improve fbs for the future. I try to document pretty meticulously what I did (and how you can migrate from earlier versions) on the [Releases page](https://github.com/mherrmann/fbs/releases).

Are you sure that `installer` does not find your `Installer.nsi`? I just tested by doing the following steps:

1. `python -m fbs startproject`
2. Copy the [default `Installer.nsi`](https://github.com/mherrmann/fbs/blob/9103e85f39811cb35e351b9eee249979e95277a1/fbs/_defaults/src/installer/windows/Installer.nsi) to `src/windows/installer/Installer.nsi`
3. Made a few minor changes to this new copy of `Installer.nsi`
4. `python -m fbs clean`, `... freeze`, `... installer`

This did produce the "modified" installer.

`app_name`, `main_module` and `author` are all still there. See [here](https://github.com/mherrmann/fbs/blob/9103e85f39811cb35e351b9eee249979e95277a1/fbs/builtin_commands/project_template/src/build/settings/base.json).

Maybe a brief summary of the biggest change: I didn't like the fact that `startproject` creates a lot of files that most users won't want to modify. These files are therefore now in a new `_defaults` module inside fbs.

**Comment by fredrikaverpil** [comment]
I followed your steps exactly and the changes in Installer.nsi are not picked up. You are saying this produce a installer on your end with the changes, but not here on my end. Hmm...

**Comment by fredrikaverpil** [comment]
The changes I did to Installer.nsi was to just change the greeting string "This wizard will guide you through...".

I notice that the `target/installer/Installer.nsi` contains the change, but the actual installer shows the original, default string.

Are you not seeing this on your end?

**Comment by mherrmann** [comment]
I'm attaching my sources. Maybe they will help?

[src.zip](https://github.com/mherrmann/fbs/files/2575730/src.zip)

**Comment by fredrikaverpil** [comment]
So, after switching the folders around and using `src/installer/windows/Installer.nsi`, it seems I am making progress (not in the tutorial app but in my actual app).

I am now noticing that the `target/installer/Installer.nsi` contains my changes but the variable substitution hasn't happened. I can see `${app_name}` etc. I am running a custom build script which calls `fbs.builtin_commands.freeze(debug)` for freeze and then `fbs.builtin_commands.installer()` for installer.

I'm looking in the `builtin_commands` module but I can't see anything on variable substitution... any ideas?

**Comment by fredrikaverpil** [comment]
Hm, ok weird. When I use your default Installer.nsi, the build script produces an installer without issues. But when I use mine, with my changes, it crashes:

```
File: "..\%{app_name}\*" -> no files found.
Usage: File [/nonfatal] [/a] ([/r] [/x filespec [...]] filespec [...] |
   /oname=outfile one_file_only)
Error in script "Installer.nsi" on line 95 -- aborting creation process
```

**Comment by fredrikaverpil** [comment]
Seems like `%{app_name}` should be `${app_name}` now.

**Comment by fredrikaverpil** [comment]
Ok, these are my findings, which solved my issues with building the installer using fbs v0.3.9:

- Installer.nsi should reside in `src/installer/windows` (not in `src/windows/installer`)
- Change all occurances of `%{` into `${` in Installer.nsi
