### ISSUE TITLE
Support for AppImage

### ISSUE THREAD

**Issue by dridk** [mherrmann/fbs#44]
Could you add AppImage support ? And/or snap package ? 
It would be awesome 
https://appimage.org
https://github.com/probonopd/linuxdeployqt

**Comment by mherrmann** [comment]
Why? Are `.deb`, `.pkg.tar.xz`, `.rpm` not enough? What about automatic updates?

**Comment by dridk** [comment]
I think from the user end perspective, It's really appreciate to download and run the AppImage directly regardless linux distribution. 

For instance, krita:
https://krita.org/fr/telechargement/krita-desktop/

**Comment by mherrmann** [comment]
Sorry but I still don't understand: For a user who's on Ubuntu, why is an AppImage so much better than a `.deb`? In my eyes the only advantage of AppImages are that they are (supposed to) run everywhere. But they're larger binaries. They don't integrate into the native package manager. So there are no automatic updates. I just fail to see what's so great about them - under the assumption that a native package exists.

**Comment by patrickelectric** [comment]
@mherrmann 	the points is that you don't need to deploy .dev, .pkg or .rpm. You can just share an appimage or a snap package. This makes easier for new users to run programs.

**Comment by mherrmann** [comment]
@patrickelectric to install `App.deb`, the user

1. Downloads it
2. Executes `sudo dpkg -i App.deb`.

To install `App.AppImage`, the user

1. Downloads it
2. Executes `chmod +x App`.

How is that easier? How does it justify the drawbacks I mentioned above?

**Comment by patrickelectric** [comment]
but the appimage step will work for any Linux, It's just easier to deploy one thing than a package for each OS. Just pointing.

**Comment by mherrmann** [comment]
You're right it may be easier for me as the app developer. But (as I said above) don't think it's easier for the user.

**Comment by mherrmann** [comment]
I'm closing this issue for now because I don't feel like there are sufficient reasons for creating an AppImage at this point, where `.deb`, `.rpm` and `.pkg.tar.xz` are already available.

**Comment by dridk** [comment]
One last reason : You need root privilege to install deb or rpm.

**Comment by mherrmann** [comment]
> You need root privilege to install deb or rpm.

Not really. You can also just extract the contents of a `.deb` say and copy it somewhere else. See eg. fman-users/fman/issues/572.

**Comment by mherrmann** [comment]
Actually, I should do this differently. I'm not opposed to supporting AppImages forever. I think they have valid use cases, especially on little-used Linux distributions. My point in the other issue was that I feel they don't have enough benefits over a native package such as an `.rpm` to justify their implementation. I'll re-open a new issue for AppImages in a little while to document this, and that AppImages will likely be implemented in the future.
