### ISSUE TITLE
Really confused on the licensing

### ISSUE THREAD

**Issue by ShamanTcler** [mherrmann/fbs#46]
I understand you are releasing your code under GPL. Which version of the GPL?

Before I try your app, it appears to be analogous to QtCreator .... do I have this correct?  If so this is a developer tool, and not something I as a developer would ever release to a customer.

Now I read the prior discussion on licensing. Do I understand that your app injects your code into my code such that you can now claim license dominion? (QtCreator as far as I know does no such code injection).

If this is the case is your app still viable to produce an application that does not include your code?

**Comment by mherrmann** [comment]
When you use fbs, you add imports to your code of the form

    from fbs_runtime import ApplicationContext

This makes you subject to the GPL. The license is [in the standard location](https://github.com/mherrmann/fbs/blob/master/LICENSE). You can see there that it's the GPLv3.

**Comment by mherrmann** [comment]
> If this is the case is your app still viable to produce an application that does not include your code?

Yes, absolutely. Just buy a license ;-)
