### ISSUE TITLE
Please support AppImage as a target format

### ISSUE THREAD

**Issue by probonopd** [mherrmann/fbs#47]
The [AppImage](http://appimage.org/) format is quite popular for Python/Qt applications, because it neatly packages everything inside one single file, including Python, Qt, etc. and does not touch things in the base system.

Supporting AppImage would have, among others, these advantages for end users:
- Applications packaged as an AppImage can run on many distributions (including Ubuntu, Fedora, openSUSE, CentOS, elementaryOS, Linux Mint, and others)
- One app = one file = super simple for users: just download one AppImage file, [make it executable](http://discourse.appimage.org/t/how-to-make-an-appimage-executable/80), and run
- No unpacking or installation necessary
- No root needed
- No system libraries changed
- Works out of the box, no installation of runtimes needed
- Optional desktop integration with `appimaged`
- Optional binary delta updates, e.g., for continuous builds (only download the binary diff) using AppImageUpdate
- Can optionally GPG2-sign your AppImages (inside the file)
- Works on Live ISOs
- Can use the same AppImages when dual-booting multiple distributions
- Can be listed in the [AppImageHub](https://appimage.github.io/apps) central directory of available AppImages
- Can double as a self-extracting compressed archive with the `--appimage-extract` parameter

[Here is an overview](https://appimage.github.io/apps) of projects that are already distributing upstream-provided, official AppImages.

Here is an example of a rather complex Python/Qt application distributed as an AppImage:
https://ultimaker.com/en/products/ultimaker-cura-software

If you have questions, AppImage developers are on #AppImage on irc.freenode.net.

**Comment by mherrmann** [comment]
Thank you for the suggestion. Please see #44 for a discussion of why AppImages are currently not a priority. Although the points you mention are quite nice, I feel they don't fundamentally go beyond what was discussed there. So I'm closing this issue for now as a duplicate.

Thanks,
Michael
