### ISSUE TITLE
Execute fbs installer on Debian

### ISSUE THREAD

**Issue by tcolombo** [mherrmann/fbs#53]
fbs lets us create .deb packages for Ubuntu... but Ubuntu is Debian based and using a Debian system returns an error : 
Unsupported Linux distribution

The doc is not clear but we must add in src/build/settings/base.json the line : 
{
    ...
    "installer": "Ubuntu"
}

A way to made fbs working on Debian : 
In fbs_runtime/platform.py : 
def is_ubuntu():
    try:
        linux_distrib = linux_distribution()
        return linux_distrib == 'Ubuntu' or linux_distrib == 'Debian'
    except FileNotFoundError:
        return False

Perhaps renaming is_ubuntu() in is_debian_like() would make more sense.

In any case, thanks for your job !

**Comment by mherrmann** [comment]
Thank you for the report. I'm afraid I don't currently have time to support arbitrary Debian-based distributions. But I'll keep it in mind for the future.

**Comment by Josep-Jesus-Bigorra-Algaba** [comment]
Having the same error, even wondering about switching to Ubuntu or Arch.. Could this be due to my MX Linux running latest Python 3.5.x?

**Comment by mherrmann** [comment]
On Linux, fbs only supports Ubuntu, Arch and Fedora / CentOS.

Closing this as "wontfix" because Debian is not officially supported by fbs for now.
