### ISSUE TITLE
Recommended approach when adding paths to PyInstaller?

### ISSUE THREAD

**Issue by fredrikaverpil** [mherrmann/fbs#54]
Hi again Michael!

I've been bugging you so many times on this topic already, so I'll just keep it short. I really need to add custom paths to PyInstaller now via the [`--paths` option](https://pyinstaller.readthedocs.io/en/stable/usage.html#what-to-bundle-where-to-search) (which you made a little bit harder recently with v0.4.4) :wink: ... I guess my only option is to maintain my own version of each `freeze_[platform]` function and on each fbs update I will have to do a diff check for changes.

I initially thought it could be possible to monkey patch the arguments of the functions to accept an `args` argument again and then remove [the initial `args = []` declaration](https://github.com/mherrmann/fbs/blob/master/fbs/freeze/windows.py#L12) ... but I was unable to figure out a way to do this and [asked at SO](https://stackoverflow.com/questions/53477701/can-i-monkey-patch-function-arguments-variables-prior-to-calling-the-function), but without much success so far.

Personally, I think it would make sense to allow for a .spec file in the settings. Let me know if this is something you think sounds okay and I can create a PR if you like.

Since I have been bringing this up many times, please close this request if you feel you cannot support this for whatever reason and I will have to deal with it. This is my final attempt to make you change your mind on allowing for this type of customization, I promise. :wink:

Please let me know what your suggestion is, and I will then shut up about this.

**Comment by mherrmann** [comment]
Hey Fredrik,

maybe you could try the following before `run_pyinstaller` gets invoked?

 * `os.environ['PYTHONPATH'] = ...` (may work)
 * `sys.path.append(...)` (probably won't work)

**Comment by fredrikaverpil** [comment]
Turns out that your suggestion works great (!) when adding paths 😄  ...but I failed to mention I also need to add non-Python files using the [PyInstaller `--add-data` option](https://pyinstaller.readthedocs.io/en/stable/usage.html#what-to-bundle-where-to-search). 😭 

So, to recap:

* `sys.path.append(...)` approach is required for `fbs run`
* `os.environ['PYTHONPATH'] = ...` approach is required for `fbs freeze`

But I have no such solution for `--add-data`.

**Comment by mherrmann** [comment]
I see :( Pity.

For `--add-data`, can you just [copy](https://docs.python.org/3/library/shutil.html#shutil.copy) the file(s) into the `target/YourApp` directory?

**Comment by mherrmann** [comment]
(By the way, I released [fbs 0.4.6](https://github.com/mherrmann/fbs/releases/tag/v0.4.6) today and am pretty stoked about it.)

**Comment by fredrikaverpil** [comment]
Would it be terrible to offer a setting "pyinstaller_args", where I could specify something like:

```json
# windows.json

"show_console_window": true,
"pyinstaller_args": {
    "--add-data": "C:/path/to/module1/file;./module1/file",
    "--add-data": "C:/path/to/module2/file;./module2/file"
    }

```

**Comment by fredrikaverpil** [comment]
> For `--add-data`, can you just copy the file(s) into the `target/YourApp` directory?

Hmm.. I was under the impression that `--add-data` would bundle the data files in some clever way which would hide the files away from the browsable folder in `target/MyApp`... but it seems all it does is actually copying the files. So maybe I am out of luck in terms of hiding files away from the user but would on the other hand be able to solve this problem by simply copying the files, like per your suggestion. I'll investigate and report back.

> (By the way, I released fbs 0.4.6 today and am pretty stoked about it.)

Wow, nice work!

**Comment by fredrikaverpil** [comment]
Okay, this seems like an edge case (when not building with `--onefile`) so I'll just resort to copying the data files like you suggested. I think this solves my main problem for now!

Thanks again Michael for your input.

**Comment by mherrmann** [comment]
Always happy to help Fredrik. It's a pity I often have to say no to your requests. It's never because I don't want to help. It's because your requirements are very specific and I'm afraid of making fbs less useful for other people if I trim fbs to fit it to your project too much. What's more, it may seem innocuous to add a special flag or setting that's really really useful, but only for a tiny number of people. But a) I have to support, test etc. every "feature" I add to fbs and b) even unused parameters/settings make fbs more difficult for first time users. A big part of fbs's value lies in its simplicity and I strive to keep it so. And people can always drop down to Python and write custom build scripts for special requirements. So in short, it's not because I don't want to help, but because I have a strong and admittedly strict vision for fbs. Hope that makes sense.

**Comment by fredrikaverpil** [comment]
No worries, Michael. I know exactly what that is like. 😉

**Comment by mherrmann** [comment]
Thanks Fredrik :relieved:.
