### ISSUE TITLE
Automatic packaging of submodules

### ISSUE THREAD

**Issue by lumpigerAffe** [mherrmann/fbs#58]
I tried out fbs and I have the following problem. 
`fbs run` works well, but after `fbs freeze` executing the executable file gives following error:
`ModuleNotFoundError: No module named 'controller'`

This error is described in [https://build-system.fman.io/manual/](https://build-system.fman.io/manual/) under Dependencies. So I tried to add:
`"hidden_imports": ["controller"]`

into the base.json. Afterwards i get the error:
`2170 ERROR: Hidden import 'controller' not found`

controller is part of my application.
The folder structure is this:

> src/main/python:
> - main.py
> - controller:
>     - \__init__.py
>     - controller.py

The main.py has this import:
`from controller import EditorController`

The \__init__.py looks like this:
`from .controller import EditorController`

Is there a way to fix this problem?

**Comment by mherrmann** [comment]
What if you rename `controller.py` to something else, eg. `_controller.py`? Or try with an absolute import, instead of a relative one?

**Comment by lumpigerAffe** [comment]
I could solve this issue.
I had a \__init__.py file in the folder src/main and the folder src/main/python. I don't know why they were there, but deleting them solved the issue.

**Comment by mherrmann** [comment]
Happy to hear it!
