### ISSUE TITLE
Expose build settings to the fbs_runtime?

### ISSUE THREAD

**Issue by jstnlef** [mherrmann/fbs#59]
I'm not sure if this is currently possible but I would like the "version" field in the `build/settings/base.json` to be the canonical version field I can reference across the app. Specifically, I would like to include the version value as part of the title window. Any ideas?

**Comment by jstnlef** [comment]
That seems like a decent enough workaround. I'll give it a go. Is it too much of a burden to include all of the settings in the app context? I feel like there aren't that many properties and it would be nice to have those readily available.

**Comment by mherrmann** [comment]
There's no problem doing it for `fbs run`. But for the frozen version of your app, we most definitely don't want all settings, because they may include passwords.

**Comment by mherrmann** [comment]
(And I'm inclined to also not include all settings by default for `fbs run`. Because then people will see "ah, I have this setting when running from source". And then, when they freeze and deploy their app, all of a sudden the setting won't be there. Imho better to make them make it explicit in the first place. Plus making some settings such as `version` available by default.)

**Comment by mherrmann** [comment]
I'm getting closer to an implementation of this. There'll be a new field in `ApplicationContext`, called `.build_settings`. For instance, you'll be able to access it as follows:

    class AppContext(ApplicationContext):
        def run(self):
            print('Starting version ' + self.build_settings['version'])
            ...

What's available in `build_settings` will be defined by a new setting called `"public_settings"`. The default will look (roughly) as follows:

    "public_settings": ["app_name", "author", "version"]

Questions;
 1. Do you find this intuitive?
 2. Can you think of better names than `build_settings` and `public_settings`? Would be cool if they both used the same name, but I can't think of what would satisfy this requirement.

**Comment by mherrmann** [comment]
(Maybe call them both `public_settings`?)

**Comment by mherrmann** [comment]
Implemented in [fbs 0.5.8](https://github.com/mherrmann/fbs/releases/tag/v0.5.8) :-) If you have questions or find bugs, please file an issue.

**Comment by jstnlef** [comment]
Whoops. I meant to respond to this yesterday but got caught up with work. Thanks a lot for this. I'm going to try it out today 👍

**Comment by jstnlef** [comment]
Works like a charm :)

**Comment by mherrmann** [comment]
Great! Thanks for letting me know :)

**Comment by mherrmann** [comment]
What do you think of the name `public_settings`?

**Comment by mherrmann** [comment]
(for both the setting and the field of `ApplicationContext`)
