### ISSUE TITLE
Offline Installer

### ISSUE THREAD

**Issue by t0ly** [mherrmann/fbs#6]
When there is no internet or the installer is blocked by a firewall, the installation aborts without offering an offline install option.

1: Error text is unhelpful: "Unable to connect to the internet. If you use a firewall, please white list fmanUpdate.exe" (Do I have to whitelist each new installer? What if I'm not the admin of the firewall, as often happens on corporate networks?)

2: Help button leads to an Error 404

3: There's no link in the installer or on the website to download an offline installer.

![image](https://user-images.githubusercontent.com/10426998/34599603-e9c8b0f2-f1fb-11e7-8138-e65b5781057b.png)

![image](https://user-images.githubusercontent.com/10426998/34599618-febba366-f1fb-11e7-8ac7-b7aacc1a934c.png)

**Comment by mherrmann** [comment]
Yes, this is for [fman](https://fman.io)'s installer. For fbs, I want to add the ability to create an offline installer. This is the next mile stone.

**Comment by mherrmann** [comment]
I released fbs 0.0.7 today. It adds the ability to create offline installers on Windows and Mac. For screenshots / instructions, please see the [updated tutorial](https://github.com/mherrmann/fbs-tutorial#creating-an-installer).
