### ISSUE TITLE
missing msvcr110.dll during freeze

### ISSUE THREAD

**Issue by mathbeal** [mherrmann/fbs#63]
Using python 3.6 on Windows 10 64bits and following tutorial.
The fbs freeze raised 

> LookupError : Could not find msvcr110.dll on PATH

The missing dll is not in system32 as expected.
![image](https://user-images.githubusercontent.com/23397421/49895784-acd13d00-fe51-11e8-9fb9-eb22ed143f16.png)
Is it a good idea to download it from site like [http://www.dlldownloader.com/msvcr110-dll/](url) or is there a better way ?

**Comment by mherrmann** [comment]
@bicarlsen [solved this](https://github.com/mherrmann/fbs/issues/51#issuecomment-440701742) by installing the [Visual C++ Redistributable for Visual Studio 2012 Update 4](https://www.microsoft.com/en-us/download/details.aspx?id=30679). Maybe this will help you as well?

**Comment by mathbeal** [comment]
Yes! the install solved the issue. 

Thanks.
