### ISSUE TITLE
glitchiness on blur event

### ISSUE THREAD

**Issue by rashkov** [mherrmann/fbs#64]
Great project! I'm noticing some glitchy graphics that happen when I blur (remove focus) from an element. Screenshot attached. I can usually get it to clear up again by re-focusing the element, or re-focus and then blur again. I assume that maybe triggers a re-render. See screenshot.

My setup is a little unconventional though -- running i3 on arch linux, and it looks like I have a few versions of pyqt installed: 
local/pyqt4-common 4.12.1-1
    Common PyQt files shared between python-pyqt4 and python2-pyqt4
local/pyqt5-common 5.11.3-1
    Common PyQt files shared between python-pyqt5 and python2-pyqt5
local/python-pyqt5 5.11.3-1
    A set of Python 3.x bindings for the Qt5 toolkit
local/python-sip-pyqt5 4.19.13-1
    Python 3.x SIP bindings for C and C++ libraries (PyQt5 version)
local/python2-pyqt4 4.12.1-1
    A set of Python 2.x bindings for the Qt toolkit

Let me know if I can provide any more information, testing, development, or feel free to close this ticket if it looks too obscure!

here's an imgur link of the screenshot, having trouble attaching it: https://imgur.com/a/6fT8Txx

edit: Seems to only happen with mouse clicks. Keyboard tabbing into and out of elements doesn't seem to trigger this.

**Comment by mherrmann** [comment]
Thank you for the kind words :-) I've never seen the behavior you describe before. It may be particular to your non-mainstream setup. But either way, it would be a bug in Qt, not fbs, because fbs does not do any rendering of its own. So I will close this issue. Do feel free to open new ones though!
