### ISSUE TITLE
How to debug "a problem is at the origin of program to stop working correctly"

### ISSUE THREAD

**Issue by tardyp** [mherrmann/fbs#65]
Hi, I am using FBS to create multi platform app.
It works well on most windows machines, including my developement machine, but does crash on other machine when user opens a dialog in the app.

A windows dialog box says:
```a problem is at the origin of program to stop working correctly```

and there is no other message or stack trace.
I am not sure how I can debug that.

![image](https://user-images.githubusercontent.com/109859/49995297-0473c380-ff8c-11e8-8124-96fc10ac49c4.png)

**Comment by mherrmann** [comment]
Hm, reading your message again, I only see now that the problem only appears when the user opens a _dialog_. That is, if I understand correctly, your app does launch successfully, and the crash appears when the dialog is opened. If that is the case, then it is highly likely that it is a bug either in Qt, or in your own code. fbs is not involved in the the launching of any dialogs.

**Comment by tardyp** [comment]
hi @mherrmann thanks for support.
The problem was related to git not in the PATH for some of my users.

--debug indeed allowed me to debug that. 

For completeness, --debug will make a binary wich opens a console window behind your app with the log of the app. So this is not something you can ship to users.

I configured a sentry in order to collect crashes from the users.

**Comment by mherrmann** [comment]
Okay! Happy to hear it works now.
