### ISSUE TITLE
hot-reloading?

### ISSUE THREAD

**Issue by davidm-public** [mherrmann/fbs#7]
Hi interesting project, almost considered following your advice and choosing QT over electron.

However, once you get used to the productivity of HMR (hot module reloading) in the javascript world, and MVVM frameworks like Vuejs, it's hard to switch, even if it means saving your users a few seconds on load time.

Thoughts?

**Comment by mherrmann** [comment]
Hi,

I don't advise to use Qt. It greatly depends on the project. For many projects, Electron will be a better fit. I'm trying to help with the ones where it isn't.

Python can HMR too. Qt uses an MVC pattern. At the end of the day, I don't see either of these as decisive for the choice of technology. Startup time / general performance of my app however is important to me. At the end of the day, we are programming to solve the problems of our users. That's more important than us getting to use the tools that we like most.

Of course, you're free to use whatever you like :-) fbs is merely another option.

**Comment by mherrmann** [comment]
(Besides, HMR is much less important if restarting your app takes 1s not 5.)

**Comment by davidm-public** [comment]
hmm, the HMR isn't just for restarting your app, it's mainly for maintaining UI state during development, so it might take 1s to restart, and another 30 seconds to get your app into the state in which you are working.

I note though that the UI in your app isn't very complicated, would be interesting to see how this approach does with a complex application with multiple 'pages' and backend services, vs the equivalent in electron with MVVM and HMR.

**Comment by mherrmann** [comment]
I see, fair point about the 30s :-) My [file manager](https://fman.io) uses HMR in Python for easier plugin development (see "Reload plugins" [here](https://fman.io/docs/plugins-introduction)). So I also know from experience that it's possible in Python.
