### ISSUE TITLE
'fbs freeze' doesn't include all packages

### ISSUE THREAD

**Issue by sampdubs** [mherrmann/fbs#70]
I have code that uses pyrebase to communicate with Google's Firebase system. When I run 'fbs run' the application works just how I want it to - no errors. I can run 'fbs freeze' and that creates an executable. However, this executable doesn't work. Running from the command line reveals the problem: `pkg_resources.DistributionNotFound: The 'gcloud' distribution was not found and is required by the application
[14702] Failed to execute script main`
It seems like even though gcloud was installed with pyrebase from pip, fbs isn't detecting it and including it in the app. Is there some way to tell fbs freeze to include certain packages?
(I am using a mac with zsh instead of bash if that makes a difference)

**Comment by mherrmann** [comment]
Have you looked at the `hidden_imports` setting? See [here](https://build-system.fman.io/manual/#dependencies) in the Manual.

**Comment by sampdubs** [comment]
Yes, I added this line to base.json:
`"hidden_imports": ["gcloud"]`
Should I include pyrebase? Would that ensure that all dependencies are included?

**Comment by mherrmann** [comment]
I don't know, sorry. You will have to experiment, maybe using Google to help.

**Comment by sampdubs** [comment]
It seems like someone experienced a simmilar issue before, also working with Pyrebase [here](https://github.com/googleapis/google-cloud-python/issues/4780)

It seems like it doesn't work because the software is depreciated?
