### ISSUE TITLE
Unable to freeze tutorial despite good versions of pyinstaller/PyQt5

### ISSUE THREAD

**Issue by Boris-Edu** [mherrmann/fbs#71]
I use last Anaconda version, Python 3.5.6, good version from PyInstaller and PyQt5, and I only try to freeze the tutorial ; doesn't work.
"fbs_pyinstaller_hook.py']' returned non-zero exit status 1"

Link to the copy of my console : 
(https://ufile.io/gli7f)

**Comment by mherrmann** [comment]
Does it work with [vanilla Python 3.6](https://www.python.org/downloads/release/python-368/)?

**Comment by BorisDess** [comment]
Yes it does so I'm closing this issue.
