### ISSUE TITLE
Support for calling bash scripts from PyQT5

### ISSUE THREAD

**Issue by jsigee87** [mherrmann/fbs#78]
I was curious if fbs would support freezing PyQT5 apps that use `subcommand()` to run local bash scripts or bash commands. Thanks!

**Comment by mherrmann** [comment]
I don't know `subcommand()`. Maybe you mean `subprocess`? In any case, yes, fbs supports freezing PyQt5 apps that invoke bash scripts. I recommend using Python's standard `subprocess` module for this.

**Comment by jsigee87** [comment]
Thanks! It is definitely called `subprocess` you are correct. So custom bash scripts are compiled into the executable, or still need to remain nearby to be invoked properly?

(Thanks for the quick response also)

**Comment by mherrmann** [comment]
No, they're not compiled. You need to ship them with your application. It's easy though: see the [relevant section of the Manual](https://build-system.fman.io/manual/#resource-files).

**Comment by mherrmann** [comment]
(so you'd place the `.sh` script into `src/main/resources/base` for instance, then do `subrocess.run([self get_resource('my.sh')])`.)

**Comment by jsigee87** [comment]
Awesome, thanks! Wanted to make sure this approach would work for our use case. Closing.
