### ISSUE TITLE
How to package app include opencv-python and pyqt5?

### ISSUE THREAD

**Issue by Jzhenli** [mherrmann/fbs#79]
Hi, I try to create a simple camera app installer for windows that include pyqt5 and opencv-python, it runs well under the command 'fbs run', but when runs the command 'fbs freeze', it will always fail. I wanna to know if it's possible for the fbs to create app that include third lib such as opencv-python? if yes, would you give a simple demo? thanks.

**Comment by mherrmann** [comment]
Have you tried the tips at https://build-system.fman.io/troubleshooting ?

**Comment by Jzhenli** [comment]
> Have you tried the tips at https://build-system.fman.io/troubleshooting ?

yes, I have try the tips you mentioned, but it seems no 'ImportError' in the log.

**Comment by mherrmann** [comment]
And any error messages when you run the binary produced by `freeze --debug` on the command line?

**Comment by Jzhenli** [comment]
the log file so long, I find 'error' as key word and can not find useful messages.

**Comment by mherrmann** [comment]
I suspect that the cause for the problem is hidden somewhere in those error messages.
