### ISSUE TITLE
Application closes silently when excepting

### ISSUE THREAD

**Issue by jorgeja** [mherrmann/fbs#80]
Hi,
Sometimes when i run my program it closes silently when excepting. By silent i mean that I do not get any exception traceback or message. Currently in my program i use two exception handlers made using the methods in the tutorial. I have one sentry exception handler and one custom that uses the logging module and logs to a file. 

If you have encountered these silent exceptions, how do you deal with them correctly?

**Comment by mherrmann** [comment]
Hi,

I could only think of freezing your app with `freeze --debug` and then running it from the command line, to see if maybe some info is shown in the console. If that fails, I'd add logging statements to the code and see which is the last entry in the log file. The crash then likely happens between this and the next logging statement.

No, I have not encountered these silent exceptions before.

**Comment by jorgeja** [comment]
Thank you for the quick reply! I will do some more debugging and try your suggestions.

**Comment by mherrmann** [comment]
Okay :-) I'll close this for now.
