### ISSUE TITLE
Package can't find DLL after freeze. Any tips?

### ISSUE THREAD

**Issue by andrewjsauer** [mherrmann/fbs#81]
A specific package in the app can't locate a DLL file after running `fbs freeze` and running the executable. Upon debugging, a DLL file can't be found even though it's within the package and runs fine outside of the executable. 

I've tried a couple workarounds as suggested [here ](https://github.com/mherrmann/fbs/issues/38) but to no avail. On another note, fbs has been great! Just need to get past this..

Running on Windows 10. Conda environment. Python 3.6.7.

**Comment by mherrmann** [comment]
Hi, by "it's inside the package", do you mean the DLL is in the Python package, or in the `target/YourApp` directory?

**Comment by andrewjsauer** [comment]
Hey! The former, it's inside my environments `site-packages/package` , I did try copy and pasting the DLL into the `target/YourApp` directory after freezing but nothin'. It's a RunTimeError that gets thrown within the package script itself when there's no file path specified

**Comment by mherrmann** [comment]
Hm, maybe the package has its own logic for locating the DLL? Which package is it?

**Comment by andrewjsauer** [comment]
It does.. Hmm.. It's this package, https://github.com/chkothe/pylsl/tree/master/pylsl

**Comment by mherrmann** [comment]
I see. Then I suppose you will have to configure / teach it to find the DLL somehow.

**Comment by mherrmann** [comment]
By the way, is this for a commercial project?

**Comment by andrewjsauer** [comment]
Gotcha, so even though the logic to find the DLL works on `run`, after `freeze`, there needs to be a new path to find the DLL?

Nah, very new to Python, just messing around at the moment.

**Comment by andrewjsauer** [comment]
Going to close this as I can see this is not fbs related
