### ISSUE TITLE
could I edit .spec of PyInstaller?

### ISSUE THREAD

**Issue by liuh886** [mherrmann/fbs#82]
I am getting used to loadIUi('\main.ui') during coding

which means I need to package .ui like this, otherwise Fail to execute script main:

Pyinstaller --add-data="main.ui" main.py

Looks like fbs didn't support --add-data arguments.

So, I am trying to edit .spec under /target/PyInstaller directory and doesn't work.

How to loadUi() and package .ui under using fbs?

**Comment by mherrmann** [comment]
It should work if you add `main.ui` to `src/main/resources/base` and call `loadIUi(self.get_resource('main.ui'))` from your `ApplicationContext`'s `run(...) method. See the [tutorial](https://github.com/mherrmann/fbs-tutorial) for an example of this and [the relevant section of the Manual](https://build-system.fman.io/manual/#resource-files).

In other words: I don't think fiddling with .spec files is the right approach here.

**Comment by mherrmann** [comment]
Also see the section "Qt Designer and Python" on [this page](https://build-system.fman.io/qt-designer-download).

**Comment by liuh886** [comment]
thanks, please close the issue.
class MyAPP():
        a = AppContext()
        print(a.get_resource('main.ui'))

I got the path of .ui
