### ISSUE TITLE
Error for execute command: fbs buildvm arch

### ISSUE THREAD

**Issue by dnkorpushov** [mherrmann/fbs#83]
While execute command "fbs buildvm arch" i receive error:
Sending build context to Docker daemon  11.26kB
Step 1/15 : FROM base/devel:2018.04.01
**manifest for base/devel:2018.04.01 not found**
 On the https://hub.docker.com/r/base/devel  says:
"Deprecated repository, use archlinux/base instead!"
Can you fix this problem? Can i have workaround for resolve this problem?
PS
Sorry for my bad english

**Comment by mherrmann** [comment]
Fixed in [release 0.7.1](https://github.com/mherrmann/fbs/releases/tag/v0.7.1).
