### ISSUE TITLE
self-executable installer support?

### ISSUE THREAD

**Issue by katakombi** [mherrmann/fbs#85]
I'm developing a service to deliver pre-installed windows applications - https://github.com/dolmades/dolmades-cli.
`fbs` really seems exactly like what I was looking for. Except I want to support user-space installation (no .deps/.rpms etc).
Is it possible to create a self-executable installer file similar to `AppImage` and/or `makeself` with `fbs` which does not require root privileges?

**Comment by mherrmann** [comment]
Have you seen #49?

**Comment by katakombi** [comment]
No, I didn't. Thanks for the ref!

**Comment by mherrmann** [comment]
Okay, closing this as a duplicate.
