### ISSUE TITLE
Spawns multiple copies when frozen

### ISSUE THREAD

**Issue by theArtechnology** [mherrmann/fbs#87]
I'm using Lubuntu, Python 3.6.7, PyQt5 v5.12. Same issue from there:
https://github.com/pyinstaller/pyinstaller/issues/4110 except that I could not resolve the issue that way. It keeps spawning multiple window when executing the frozen script.

**Comment by mherrmann** [comment]
You mean it opens multiple windows when you launch it multiple times?

**Comment by theArtechnology** [comment]
I launch once, it creates multiple windows and it never ends. I have to log out to kill the process because, the windows keep popping up.

**Comment by mherrmann** [comment]
I don't think that's a bug in fbs. Do you have a minimal reproducible example?

**Comment by theArtechnology** [comment]
Step:
- fbs startproject
- pip install sklearn
- import sklearn
- fbs freeze
then open the executable.

**Comment by mherrmann** [comment]
If `excludes=['sklearn.externals.joblib']` works for PyInstaller, you could probably write a [custom fbs build script](https://build-system.fman.io/manual/#custom-commands) that overwrites [fbs's built-in one](https://github.com/mherrmann/fbs/blob/883a10dcc70f5d3580e57576073e06cd56d1106f/fbs/builtin_commands/__init__.py#L92) and calls [`run_pyinstaller`](https://github.com/mherrmann/fbs/blob/883a10dcc70f5d3580e57576073e06cd56d1106f/fbs/freeze/__init__.py#L15) with some `extra_args` that have the same effect as the `excludes=...` statement.

**Comment by theArtechnology** [comment]
Thanks, unfortunately, it doesn't work:

`from fbs.cmdline import command
from os.path import dirname
from fbs.freeze.linux import freeze_linux, remove_shared_libraries
from fbs.freeze import _generate_resources, run_pyinstaller
from shutil import copy
import fbs.cmdline

@command
def freeze(debug=False):
    """
    Compile your code to a standalone executable
    """
    require_existing_project()
    if not _has_module('PyInstaller'):
        raise FbsError(
            "Could not find PyInstaller. Maybe you need to:\n"
            "    pip install PyInstaller==3.4"
        )
    # Import respective functions late to avoid circular import
    # fbs <-> fbs.freeze.X.
    app_name = SETTINGS['app_name']
    if is_mac():
        from fbs.freeze.mac import freeze_mac
        freeze_mac(debug=debug)
        executable = 'target/%s.app/Contents/MacOS/%s' % (app_name, app_name)
    else:
        executable = join('target', app_name, app_name)
        if is_windows():
            from fbs.freeze.windows import freeze_windows
            freeze_windows(debug=debug)
            executable += '.exe'
        elif is_linux():
            if is_ubuntu():
                print("Ubuntu")

                excludes=['--exclude-module sklearn.externals.joblib'] 
                run_pyinstaller(extra_args=excludes, debug=debug)
                _generate_resources()
                copy(path('src/main/icons/Icon.ico'), path('${freeze_dir}'))
               

                remove_shared_libraries(
                    'libstdc++.so.*', 'libtinfo.so.*', 'libreadline.so.*', 'libdrm.so.*'
                )
                remove_shared_libraries('libgpg-error.so.*')
                
                remove_shared_libraries('libgtk-3.so.*')
                
                remove_shared_libraries('libgio-2.0.so.*')
            elif is_arch_linux():
                from fbs.freeze.arch import freeze_arch
                freeze_arch(debug=debug)
            elif is_fedora():
                from fbs.freeze.fedora import freeze_fedora
                freeze_fedora(debug=debug)
            else:
                from fbs.freeze.linux import freeze_linux
                print("Linux")
                excludes=['--exclude-module sklearn.externals.joblib'] 
                run_pyinstaller(extra_args=excludes, debug=debug)
                _generate_resources()
                copy(path('src/main/icons/Icon.ico'), path('${freeze_dir}'))
          
                remove_shared_libraries(
                    'libstdc++.so.*', 'libtinfo.so.*', 'libreadline.so.*', 'libdrm.so.*'
                )
        else:
            raise FbsError('Unsupported OS')
    _LOG.info(
        "Done. You can now run `%s`. If that doesn't work, see "
        "https://build-system.fman.io/troubleshooting.", executable
    )


if __name__ == '__main__':
    project_dir = dirname(__file__)
    fbs.cmdline.main(project_dir)`

**Comment by theArtechnology** [comment]
Finally, I have got a solution:
- `import multiprocessing` (in the main.py or before sklearn import)
- then call ` multiprocessing.freeze_support() `under `__name__ == '__main__'` or before importing sklearn respectively.

This will solve the issue of infinite loop and windows will stop popping up. 

But sklearn won't work, it will say that there are missing modules, such as `typedefs` and will report the module as such `sklearn.neighbors.typedefs` for example. Everytime there will be a module missing, include it before importing sklearn like this: `import sklearn.neighbors.typedefs`. fbs will do the job of including the module automatically.

This will make sklearn work and stop the infinite loop.

**Comment by mherrmann** [comment]
Thanks for sharing!

**Comment by komodovaran** [comment]
Sorry for reopening. This is related to https://github.com/pyinstaller/pyinstaller/issues/4110

Even using the fix above, I still had a lingering extra process that I couldn't get rid of. Everything works if you install `joblib==0.11`, even with the current version of `sklearn==0.21.2`.
