### ISSUE TITLE
ERROR: Tcl/Tk improperly installed on this system

### ISSUE THREAD

**Issue by hargun-singh** [mherrmann/fbs#88]
The command 'fbs freeze' throws the error 'Tcl/Tk improperly installed on this system' when 'matplotlib' is imported in my python code. The command works fine when I don't import matplotlib.

**Comment by mherrmann** [comment]
Looks similar to [PyInstaller issue 3753](/pyinstaller/pyinstaller/issues/3753). Are you on Python 3.7?

**Comment by hargun-singh** [comment]
I am using python 3.6.5 but making changes to hook-_tkinter.py did the trick for me as explained in PyInstaller issue 3753. 
Thankyou so much for your help. fbs is a great tool.

**Comment by mherrmann** [comment]
My pleasure :-)
