### ISSUE TITLE
Feature: Resource class

### ISSUE THREAD

**Issue by d4rkm0nkey** [mherrmann/fbs#95]
This is a feature request. I am not really sure whether it belongs here.
When using resources like pictures or files (qss, ui, etc.) they have to be put in the resource folder.
To access them someone can use ApplicationContext.get_resource().
I think this is rather inconvenient. It would be much better to have a resource class (like in Android) that automatically builds an object with all file paths of files in the resource folder.
For example, if the resource folder looks like this:

- resources
  - ui
    - main_window.ui
    - other_window.ui
  - images
    - logo.jpg
  - style
    - dark_design.qss
    - light_design.qss

It would be nice to have an object automatically generated that has an object structure like this:
```
{
  ui: {
      main_window: "{absolute_path}/ui/main_window.ui",
      other_window: "{absolute_path}/ui/other_window.ui"
  },
  images: {
    logo: "{absolute_path}/images/logo.jpg"
  },
  style: {
     dark_design: "{absolute_path}/style/dark_design.qss",
     light_design: "{absolute_path}/style/light_design.qss"
  }
}
```
This object should be accessible in every module of the project. Let's call it R like in Android.
To get any resource path for example of the main_window.ui file, you can then simply use R.ui.main_window and get the correct resource path.

I think this would be way easier to use. What do you think about this?

**Comment by mherrmann** [comment]
Thank you for the request.

I don't think this is a good idea. Referencing `R` in all your modules adds an implicit dependency of - all modules - on whatever manages resources in the background. What if you want to use different files for testing? Globals - of which `R` would be an example - look tempting but always come back to haunt you.

Of course, if you want something like this, you can easily create your own wrapper around Application context that acts like the `R` you describe.

**Comment by mherrmann** [comment]
I hope this didn't come across as harsh; it's just my honest - and admittedly very direct - opinion.
