### ISSUE TITLE
fbs installer on macOS returns: mktemp: too few X's in template ‘createdmg’

### ISSUE THREAD

**Issue by j9ac9k** [mherrmann/fbs#96]
I've been migrating my pyside2 application into fbs.  I'm attempting to create an installer on macOS, but I get the following error:

```
$ pipenv run fbs installer
Loading .env environment variables…
mktemp: too few X's in template ‘createdmg’
Traceback (most recent call last):
  File "/Users/ognyan/Developer/fred/.venv/bin/fbs", line 10, in <module>
    sys.exit(_main())
  File "/Users/ognyan/Developer/fred/.venv/lib/python3.7/site-packages/fbs/__main__.py", line 17, in _main
    fbs.cmdline.main()
  File "/Users/ognyan/Developer/fred/.venv/lib/python3.7/site-packages/fbs/cmdline.py", line 32, in main
    fn(*args)
  File "/Users/ognyan/Developer/fred/.venv/lib/python3.7/site-packages/fbs/builtin_commands/__init__.py", line 157, in installer
    create_installer_mac()
  File "/Users/ognyan/Developer/fred/.venv/lib/python3.7/site-packages/fbs/installer/mac/__init__.py", line 21, in create_installer_mac
    ], stdout=DEVNULL)
  File "/Users/ognyan/.pyenv/versions/miniconda3-latest/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/Users/ognyan/Developer/fred/.venv/lib/python3.7/site-packages/fbs/installer/mac/yoursway-create-dmg/create-dmg', '--volname', 'Fred', '--app-drop-link', '170', '10', '--icon', 'Fred.app', '0', '10', '/Users/ognyan/Developer/fred/target/Fred.dmg', '/Users/ognyan/Developer/fred/target/Fred.app']' returned non-zero exit status 1.
```

So this is running on Python 3.7 which I know is not official supported; but I have no reason to suspect that's the issue.

If it makes any difference, I'm also having trouble with fbs freeze

```
$ pipenv run fbs freeze
Loading .env environment variables…
3358 ERROR: Hidden import 'distutils' not found
3391 ERROR: Hidden import 'distutils.dist' not found
3391 ERROR: Hidden import 'dist' not found
28170 ERROR: Can not find path ./libshiboken2.abi3.5.12.dylib (needed by /Users/ognyan/Developer/fred/.venv/lib/python3.7/site-packages/PySide2/QtWidgets.abi3.so)
28188 ERROR: Can not find path ./libshiboken2.abi3.5.12.dylib (needed by /Users/ognyan/Developer/fred/.venv/lib/python3.7/site-packages/PySide2/QtGui.abi3.so)
28208 ERROR: Can not find path ./libshiboken2.abi3.5.12.dylib (needed by /Users/ognyan/Developer/fred/.venv/lib/python3.7/site-packages/PySide2/QtCore.abi3.so)
28508 ERROR: Can not find path ./libshiboken2.abi3.5.12.dylib (needed by /Users/ognyan/Developer/fred/.venv/lib/python3.7/site-packages/PySide2/QtNetwork.abi3.so)
29113 ERROR: Can not find path ./libshiboken2.abi3.5.12.dylib (needed by /Users/ognyan/Developer/fred/.venv/lib/python3.7/site-packages/PySide2/libpyside2.abi3.5.12.dylib)
Done. You can now run `target/Fred.app/Contents/MacOS/Fred`. If that
doesn't work, see https://build-system.fman.io/troubleshooting.
$ target/Fred.app/Contents/MacOS/Fred
/Users/ognyan/Developer/fred/target/Fred.app/Contents/MacOS/distutils/__init__.py:14: UserWarning: The virtualenv distutils package at %s appears to be in the same location as the system distutils?
Traceback (most recent call last):
  File "src/main/python/fbs_main.py", line 8, in <module>
    from src.main.python.FredApp import Fred, FredApp
  File "/Users/ognyan/Developer/fred/.venv/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "src/main/python/FredApp.py", line 10, in <module>
    from controllers.controller import MainController
  File "/Users/ognyan/Developer/fred/.venv/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "src/main/python/controllers/controller.py", line 7, in <module>
    from qtpy.QtCore import QModelIndex, QObject, QUrl, Signal
  File "/Users/ognyan/Developer/fred/.venv/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages/qtpy/__init__.py", line 65, in <module>
  File "/Users/ognyan/Developer/fred/.venv/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "distutils/__init__.py", line 44, in <module>
ImportError: cannot import name 'dist' from 'distutils' (/Users/ognyan/Developer/fred/target/Fred.app/Contents/MacOS/distutils/__init__.pyc)
[27232] Failed to execute script fbs_main
```

The distutils issue appears to be a problem with virtualenv and pyinstaller here:

https://github.com/pyinstaller/pyinstaller/issues/4064

I'm working on removing `qtpy` as a dependency (which is what uses distutils from what I can tell).

Any other suggestions?

**Comment by j9ac9k** [comment]
Got around the fbs freeze issue by installing virtualenv 16.1 as my pipenv dependency... unfortunately still getting the same error with respect to `fbs installer`

**Comment by mherrmann** [comment]
Does it work if you apply [this patch](https://github.com/andreyvit/create-dmg/commit/0a98f89653e6509e9379ac2ce33c106c335601d3)?

**Comment by j9ac9k** [comment]
I only applied the change on line 235 (as the other code doesn't appear to be there any more) and it worked.

**Comment by j9ac9k** [comment]
and now I can't replicate the error so feel free to disregard.

**Comment by mherrmann** [comment]
You mean you cannot reproduce the error even without the patch I sent you?

**Comment by j9ac9k** [comment]
Sorry for the confusion.

For the patch you sent me, i only made the change they show on line 235. `create-dmg` does it's thing without error and everything works.

Regarding the error, i thought the `dmg` it created had an error something along those lines, but I could never replicate that error again, so i'm chalking that up to user error.

The patch you lined to, specifically the change from `APPLESCRIPT=$(mktemp -t createdmg)` to `APPLESCRIPT=$(mktemp -t createdmg.tmp.XXXXXXXXXX)` is very much needed.

**Comment by mherrmann** [comment]
I see, thank you for letting me know. I just released [fbs 0.7.4](https://github.com/mherrmann/fbs/releases/tag/v0.7.4) that applies the same patch as you to fix the problem.

**Comment by Vyeadiai** [comment]
I am not sure if this is fixed. I have the latest fbs 0.7.4.

`Thrive-MacBook-Air:client thrive$ pip freeze
altgraph==0.16.1
boto3==1.9.130
botocore==1.12.130
docutils==0.14
fbs==0.7.4
future==0.17.1
jmespath==0.9.4
macholib==1.11
pefile==2018.8.8
PyInstaller==3.4
Pyro4==4.75
PySide2==5.12.2
python-dateutil==2.8.0
s3transfer==0.2.0
serpent==1.28
shiboken2==5.12.2
sip==4.19.8
six==1.12.0
typing==3.6.6
urllib3==1.24.1
Thrive-MacBook-Air:client thrive$ fbs freeze
9052 ERROR: Can not find path ./libshiboken2.abi3.5.12.dylib (needed by /Users/thrive/.pyenv/versions/3.6.8/Python.framework/Versions/3.6/lib/python3.6/site-packages/PySide2/QtCharts.abi3.so)
9055 ERROR: Can not find path ./libshiboken2.abi3.5.12.dylib (needed by /Users/thrive/.pyenv/versions/3.6.8/Python.framework/Versions/3.6/lib/python3.6/site-packages/PySide2/QtNetwork.abi3.so)
9061 ERROR: Can not find path ./libshiboken2.abi3.5.12.dylib (needed by /Users/thrive/.pyenv/versions/3.6.8/Python.framework/Versions/3.6/lib/python3.6/site-packages/PySide2/QtCore.abi3.so)
9068 ERROR: Can not find path ./libshiboken2.abi3.5.12.dylib (needed by /Users/thrive/.pyenv/versions/3.6.8/Python.framework/Versions/3.6/lib/python3.6/site-packages/PySide2/QtWidgets.abi3.so)
9075 ERROR: Can not find path ./libshiboken2.abi3.5.12.dylib (needed by /Users/thrive/.pyenv/versions/3.6.8/Python.framework/Versions/3.6/lib/python3.6/site-packages/PySide2/QtGui.abi3.so)
9080 ERROR: Can not find path ./libshiboken2.abi3.5.12.dylib (needed by /Users/thrive/.pyenv/versions/3.6.8/Python.framework/Versions/3.6/lib/python3.6/site-packages/PySide2/QtQml.abi3.so)
9087 ERROR: Can not find path ./libshiboken2.abi3.5.12.dylib (needed by /Users/thrive/.pyenv/versions/3.6.8/Python.framework/Versions/3.6/lib/python3.6/site-packages/PySide2/QtQuick.abi3.so)
9476 ERROR: Can not find path ./libshiboken2.abi3.5.12.dylib (needed by /Users/thrive/.pyenv/versions/3.6.8/Python.framework/Versions/3.6/lib/python3.6/site-packages/PySide2/libpyside2.abi3.5.12.dylib)
Done. You can now run
`target/PyInstallerFail.app/Contents/MacOS/PyInstallerFail`. If that
doesn't work, see https://build-system.fman.io/troubleshooting.
Thrive-MacBook-Air:client thrive$ 
`

**Comment by mherrmann** [comment]
This is a completely different error(?) It does not mention `create-dmg` at all.
