### ISSUE TITLE
Scapy Issues

### ISSUE THREAD

**Issue by SpaceyEeyore** [mherrmann/fbs#99]
Hi, I'm having issues with importing scapy. 

In one of my src files, I have import scapy.all as scapy. I have tried adding scapy to the hidden includes after the first failure, but it still does not seem to work. The program will run successfully, but just won't finish the modules that are using scapy.all. Any suggestions? (I don't see any scapy folder in the target directory).

The program runs fine with fbs run, just not after performing a fbs freeze and running the .exe

**Comment by SpaceyEeyore** [comment]
The issue was my own fault. If I add scapy.all in hidden_imports and  modify the import statement to remove "as scapy" (import scapy.all), then scapy is properly imported and can run.

**Comment by SpaceyEeyore** [comment]
Hi, seems that I'm having this issue again and I'm not sure what is going on. I thought it worked in my last build, but I'm having issues again after updating my project and running fbs clean and then fbs freeze. 

My import statement:

`import scapy.all`

My base.json file:
```
{
    "app_name": "Test_Application",
    "author": "SpaceyEeyore",
    "main_module": "src/main/python/TestApplication/main.py",
    "version": "0.0.1",
    "hidden_imports": ["scapy.all"]
}

```

**Comment by mherrmann** [comment]
And which error message do you get when you run your app from the command line?

**Comment by SpaceyEeyore** [comment]
I apologize it seems to be my own issues with Scapy. I will close this issue. As previously written, scapy is able to work when adding "hidden_imports": ["scapy.all"] to the base.json file.
